### ISSUE TITLE
Improve Documentation

### ISSUE THREAD

**Issue by markus-wa** [markus-wa/demoinfocs-golang#1]
- [x] Complete basic GoDoc
- [x] Improve README.md
- Add more examples
  - [x] ~~`AdditionalEventEmitters`~~
  - [x] `ServerClasses`
- [x] ~~Explain some lingo & quirks of CS:GO~~ -> will be done on a per-question basis
- [x] Document more fields that aren't immediately obvious
- [x] ~~Maybe document #64 a bit more in depth~~

Notes by @micvbang:
>I think it would be nice to see some general documentation on some of the lingo and quirks of the game on the roadmap
>One example could be the life-cycle of grenades (e.g. for fire nades: weapon entity -> projectile entity -> inferno entity)
Another example could be what entity ids are, and why (id reuse) regular users of the library probably want to use the UniqueID instead
(This probably is an extension of bullet 1) documentation on some of the fields that are not immediately, e.g. Player.UserID. I think it would be nice to explain what this is, when compared to e.g. EntityID and SteamID

**Comment by zoidbergwill** [comment]
The tests are a pretty great place to see some example use cases, but it would definitely be awesome to have nicer docs.

**Comment by markus-wa** [comment]
I'm hoping to improve on this once I find some time, hopefully soon.

Is there anything you would like to see added / changed specifically?

**Comment by zoidbergwill** [comment]
I guess the first bit would be getting started using the library, which I figured out from the tests:

https://sourcegraph.com/github.com/markus-wa/demoinfocs-golang/-/blob/demoinfocs_test.go#L34

and then which events are dispatched, and what they look like:

https://sourcegraph.com/github.com/markus-wa/demoinfocs-golang/-/blob/packet_handlers.go#L101

However the code is easy enough to read that I don't think it's a huge issue. A bunch of it is also difficult with how little documentation Valve has for the demo format. 😞
