### ISSUE TITLE
Maps metadata outdated

### ISSUE THREAD

**Issue by o40** [markus-wa/demoinfocs-golang#101]
**Describe the bug**
The metadata related to radar images seem outdated and should be updated according to the information in SteamApps/common/Counter-Strike Global Offensive/csgo/resource/overviews/*.txt

Using this outdated metadata will cause incorrect translation functionality in the metadata functions.

**To Reproduce**
Use the TranslateScale function from metadata to translate positions for example de_dust2 (which seem broken). Get a ingame coordinate from a corner somewhere on the map and then try to draw it on the radar image (like in the heatmap example).

**Expected behavior**
The position on the radar image should be the same as the ingame position.

**Library version**
Don't know. Latest and greatest.

**Comment by markus-wa** [comment]
Fixed by #103 - thank you for your contribution!

> Don't know. Latest and greatest.
😉
