### ISSUE TITLE
Rank Update event not triggering

### ISSUE THREAD

**Issue by allenymin** [markus-wa/demoinfocs-golang#111]
The rank update event does not trigger. There is no case for it in handleUserMessage

**Comment by markus-wa** [comment]
You're right.

Would you like to create a PR?
This would be a great first contribution.

**Comment by allenymin** [comment]
Yeah I'm working on it. Although I don't fully understand how it works at the lower levels.

**Comment by markus-wa** [comment]
Thanks for the fix in #112 !
