### ISSUE TITLE
Player additional information

### ISSUE THREAD

**Issue by quancore** [markus-wa/demoinfocs-golang#115]
**Higher goal**
There are several fields for players can easy being retrieved from a demo file. My interest is: whether a player is in a buy zone, whether a player in a bomb zone (and the name of the bomb zone), how many seconds alive in this round, whether he is walking, whether he is jumping (I do not know it is possible).
**Describe the solution you'd like**
Most of the fields are in a demo file and implemented here: https://github.com/saul/demofile/blob/c6d6555/src/entities/player.ts

**Comment by markus-wa** [comment]
You can also use `Player.Entity` for this. But I agree, this should be supported natively.

**Comment by markus-wa** [comment]
On that note, it would probably be better to create functions on the `Player` struct instead of the ugly `OnUpdate` stuff we do now.

**Comment by markus-wa** [comment]
The branch `player-additional-info` now contains these changes (and includes #114)

New functions:
- `TeamState.Members()`
- `TeamState.CurrentEquipmentValue()`
- `TeamState.RoundStartEquipmentValue()`
- `TeamState.FreezeTimeEndEquipmentValue()`
- `TeamState.CashSpentThisRound()`
- `TeamState.CashSpentTotal()`
- `Player.IsInBombZone()`
- `Player.IsInBuyZone()`
- `Player.IsWalking()`
- `Player.IsScoped()`
- `Player.CashSpentThisRound()`
- `Player.CashSpentTotal()`

**Comment by quancore** [comment]
Is there API breaking changes?

**Comment by markus-wa** [comment]
Yes, in package `sendtables`, which is why I'm not yet sure when/if I'll merge it in the current state:
* `Entity.FindProperty()` now returns `IProperty` instead of `*Property` (#114)
* `Entity.Properties()` now returns `[]IProperty` instead of `[]Property`

**Comment by quancore** [comment]
> Yes, in package `sendtables`, which is why I'm not yet sure when/if I'll merge it in the current state:
> 
> * `Entity.FindProperty()` now returns `IProperty` instead of `*Property`
> * `Entity.Properties()` now returns `[]IProperty` instead of `[]Property`

Anything on higher layers like teamState, Player etc.?

**Comment by markus-wa** [comment]
> Anything on higher layers like teamState, Player, etc.?

no

> And when you will merge?

as I said:
> [...] I'm not yet sure when/if I'll merge it in the current state

**Comment by xXxhaxmeister42xXx** [comment]
Would you mind adding even more player status information like Player.IsPlanting or Player.IsReloading?

While IsPlanting proved to be fairly easy to determine via the BombPlant-Events (an additional event.BombPlantAborted might help to more easily identify fake plants), reloading status seems to be more of a challenge.


I failed to get anything useful out of `msg.CCSUsrMsg_ReloadEffect` (networked reload sound effect? would have been good enough for what i wanted) and the player entity.
[This](https://github.com/markus-wa/demoinfocs-golang/blob/d03a884d868fd585560885d7f8fefc38759895b9/game_events.go#L108) would be triggered when reloading is complete?

What i came up with during experimenting so far is the following, which
- would require adding handlers for each weapon class individually? Not sure how to look for base classes
- seems to produce quite a few "noones gun reloaded"
- has incomplete reloads (maybe interrupted by round start or weapon switch?)

```go
parser.RegisterEventHandler(func(events.DataTablesParsed) {
  parser.ServerClasses().FindByName("CAK47").OnEntityCreated(func(entity *sendtables.Entity) {
    entityCName:= entity.FindPropertyI("m_AttributeManager.m_Item.m_szCustomName").Value().StringVal
    //might want to watch m_iClip1 or m_iPrimaryReserveAmmoCount as well?
    entity.FindPropertyI("m_bReloadVisuallyComplete").OnUpdate(func(val sendtables.PropertyValue){
      ownHa := entity.FindPropertyI("m_hOwnerEntity").Value().IntVal
      owner := parser.GameState().Participants().FindByHandle(ownHa)
      ownerName:= "noone"
      if owner!=nil {
        ownerName = owner.Name
      }
      reload:= "reloaded"
      if val.IntVal==0 {
        reload = "reloading"
      }
      fmt.Printf("%d  %s's %s (%s) %s\n", entity.ID(), ownerName, entity.ServerClass().Name(), entityCName, reload)
    })
  })
})
```

**Comment by markus-wa** [comment]
Hey @xXxhaxmeister42xXx

Thanks for your suggestions. Could you open a new issue for this?

**Comment by xXxhaxmeister42xXx** [comment]
I haven't been to sure since this is quite similar. I created #132
