### ISSUE TITLE
Question: yaw, pitch

### ISSUE THREAD

**Issue by quancore** [markus-wa/demoinfocs-golang#116]
I could not see in player struct yaw and pitch angles. However, there are viewangle variables in the struct. Are there correspond to yaw and pitch? If yes, what is exactly the view angles? I need to understand because I need to calculate crosshair replacement.

**Comment by markus-wa** [comment]
That's `Player.ViewDirectionX` & `ViewDirectionY`. 🙂

**Comment by Mateeox** [comment]
I am not really sure what these values represent. Pitch should be in range 0-180 (178), however I found that it was going over this value (220, 250).

**Comment by markus-wa** [comment]
`ViewDirectionY` (pitch) should be `270° (=-90) - 90°`. If you have a demo where it's `90 - 270` please link it so I can take a look 🙂.

`ViewDirectionX` (yaw) should be `0° - 360°`

This seems to be a good visualization: http://www.ctralie.com/Teaching/COMPSCI290/Materials/EulerAnglesViz/
