### ISSUE TITLE
Question: Weapon zoom level

### ISSUE THREAD

**Issue by quancore** [markus-wa/demoinfocs-golang#118]
I could not find any explanation of what is the meaning of numbers in zoom level of a weapon. For example, I am observing 0, 1, 2 for the zoom level of AWP. Is 2 meaning the most zoomed (focused)?

**Comment by markus-wa** [comment]
Yes

**Comment by markus-wa** [comment]
Documented with a3bc604, thanks for bringing my attention to it.
