### ISSUE TITLE
Double increment on TickDone

### ISSUE THREAD

**Issue by quancore** [markus-wa/demoinfocs-golang#120]
**Describe the bug**
TickDone event has been initiated with 2 ticks increment rather than 1 tick. So tick value goes like 0, 2, 4, 6 ... I understand that after tick done, game state tick will be incremented by 1 and it will give 1 extra when I probe ingametick. However, even for the situation, it should be continuous for this case like 1,2,3,4,5....

**To Reproduce**
https://www.hltv.org/stats/matches/mapstatsid/81984/avant-vs-ex-paradox
Code:
```go
	analyser.parser.RegisterEventHandler(func(e events.TickDone) {
		// because tick has been done, getting game tick will be +1
		origTick := analyser.parser.GameState().IngameTick()
		// prevTick := (origTick - 1)
		// if prevTick < 0 {
		// 	prevTick = 0
		// }

		analyser.log.WithFields(logging.Fields{
			"origTick": origTick,
			// "tickDone": prevTick,
		}).Info("ticks ")
}
```

**Expected behavior**
It should be continuous.

**Comment by markus-wa** [comment]
`TickDone` is a bit of a misnomer unfortunately.
It's actually triggered on the end of a demo-frame, not a tick.

While the `GameState.IngameTick()` returns the actual tick number. If you need something that increments by one on each frame then `Parser.CurrentFrame()` should work.

I will try to document this soon(TM).

**Comment by quancore** [comment]
I need to check some conditions on every tick in a continuous fashion without skipping using an event callback. Can you suggest anything?

**Comment by markus-wa** [comment]
No, demos can't differentiate between ticks, only frames. Sorry 😕

Maybe store the last tick nr and check for all the ticks between? Does that work?

Otherwise I'll need more details on what you're trying to do to help out.

**Comment by quancore** [comment]
> No, demos can't differentiate between ticks, only frames. Sorry 
> 
> Maybe store the last tick nr and check for all the ticks between? Does that work?
> 
> Otherwise I'll need more details on what you're trying to do to help out.

Thank you for your answer. I will do as follows. I will divide total tick number to total frame named tickFrameRatio. After that, for each tickdone, I will check skipped ticks using tickFrameRatio. Is it make sense to you?

**Comment by markus-wa** [comment]
I think there are some demos where `TickFrameRatio` is broken.

I would suggest:
```go
var oldTick int
parser.RegisterEventHandler(func(events.TickDone) {
    newTick = parser.GameState().IngameTick()
    for currentTick := oldTick; currentTick < newTick; currentTick++ {
        // do stuff with currentTick
    }
    oldTick = newTick
})
```

**Comment by markus-wa** [comment]
Documented in e9cf7cd
