### ISSUE TITLE
Team ID changing

### ISSUE THREAD

**Issue by quancore** [markus-wa/demoinfocs-golang#123]
**Describe the bug**
Team ID  changing when teams switched, however, it is documented that it should remain the same
**To Reproduce**
https://www.hltv.org/download/demo/30215 (overpass)
```

**Comment by markus-wa** [comment]
@quancore please provide the failing code

**Comment by markus-wa** [comment]
@quancore not sure if you saw my last comment. I'd like to get it fixed, and your code would be really helpful, without that I'm not quite sure if I understand the issue correctly.
! �

**Comment by quancore** [comment]
Thank you for your response. I have solved the issue by a workaround and currently, I have focused to finish my master thesis that why I cannot supply a code block. If I found the time, I will try to provide.

**Comment by markus-wa** [comment]
I will close this for now.
Feel free to re-open this with additional info.
