### ISSUE TITLE
M4a4 detection issue

### ISSUE THREAD

**Issue by xavier-rodet** [markus-wa/demoinfocs-golang#124]
**Describe the bug**
M4a4 is always detected as M4a1 (events.Kill, events.PlayerHurt, events.WeaponFire)

**To Reproduce**
HLTV demo : https://www.hltv.org/download/demo/50987
(With "vitality-vs-fnatic-m1-mirage.dem" file) 

Code:
```go
func analyze(filePath string) {

    var isGameLive bool

    var round Round
    round.Number = 0

    f, err := os.Open(filePath)
    if err != nil {
        panic(err)
    }
    defer f.Close()

    p := dem.NewParser(f)

    header, err := p.ParseHeader()
    if err != nil {
        panic(err)
    }

    mapName := header.MapName
    fmt.Printf("%s\n", mapName)

    // Match Started
    p.RegisterEventHandler(func(e events.MatchStart) {

        isGameLive = true
        round.Number = 1
    })

    // Round Started
    p.RegisterEventHandler(func(e events.RoundStart) {

        if(isGameLive) {

            // Prepare new round
            round = Round{Number: (round.Number + 1)}

            fmt.Printf("Round %d has just started\n", round.Number)
        }
    })


    // Register handler on kill events
    p.RegisterEventHandler(func(e events.Kill) {

        if(isGameLive) {

            fmt.Printf("Player %s Kill %s with %s\n", e.Killer.Name, e.Victim.Name, e.Weapon.Weapon)
        }
    })


    // Player get hurt
    p.RegisterEventHandler(func(e events.PlayerHurt) {

        // If game is live AND player got hurt by a player
        if(isGameLive && e.Attacker != nil) {

            // Show only rifles
            if(common.EqClassRifle == e.Weapon.Class()) {

                fmt.Printf("Player %s Hit Player %s with %s\n", e.Attacker.Name, e.Player.Name, e.Weapon.Weapon.String())

            }
        }
    })

    //  Player fire (for shots)
    p.RegisterEventHandler(func(e events.WeaponFire) {

        if(isGameLive && common.EqUnknown != e.Weapon.Weapon && common.EqClassRifle == e.Weapon.Class()) {

            fmt.Printf("Player %s Shot with %s\n", e.Shooter.Name, e.Weapon.Weapon.String())
        }
    })

    // Parse to end
    err = p.ParseToEnd()
}
```

**Expected behavior**
M4a4 weapon should be detected as M4a4 and not M4a1

**Library version**
Current master repository

**Additional context**
Look for:

> Round 11 has just started
> ...
> Player RpK Shot with M4A1
> Player RpK Hit Player Brollan with M4A1
> Player Brollan Shot with AK-47
> Player RpK Shot with M4A1
> Player RpK Hit Player Brollan with M4A1
> Player Brollan Shot with AK-47
> Player RpK Shot with M4A1
> Player RpK Hit Player Brollan with M4A1
> Player RpK Shot with M4A1
> Player Brollan Shot with AK-47
> Player Brollan Hit Player RpK with AK-47
> Player RpK Shot with M4A1
> Player RpK Hit Player Brollan with M4A1
> Player RpK Kill Brollan with M4A1

**Comment by markus-wa** [comment]
Thanks for the bug report @xavier-rodet!

Would you like to submit a PR? The issue seems to be this line: https://github.com/markus-wa/demoinfocs-golang/blob/master/common/equipment.go#L212

**Comment by xavier-rodet** [comment]
Done!
Great job btw, it's insanely faster than the C# Project :)

**Comment by markus-wa** [comment]
Thanks! I appreciate the support 😄
