### ISSUE TITLE
Datetime of when the game was played ?

### ISSUE THREAD

**Issue by xavier-rodet** [markus-wa/demoinfocs-golang#127]
Hey,

I wonder if it is possible to get the datetime of when the game was played ?
Or it isn't stored in the .dem file ?

Thanks

**Comment by markus-wa** [comment]
Unfortunately that info doesn't seem to be anywhere.

This has previously been discussed in our Gitter as well (https://gitter.im/csgodemos/demoinfo-lib).

From Gitter:
> @quancore: [...] Can I get the version of game which played?

> @markus-wa: probably, I'll check if I can find something. Is there nothing in the header?

> @quancore: I have checked but, no luck.

> @markus-wa: It seems like the game version isn't networked :(
On another parser: saul/demofile#59
But I'm pretty sure the map version must be somewhere, since the game needs to know which version to download to play the demo
No clue where it could be [...]

> @quancore: is ther any info about date of the match?

> @markus-wa: Not that I'm aware of, no

> @micvbang: I've looked a lot for a date and haven't found it yet :'(

So the date doesn't seem to be in the demo. But maybe if you can find the map version you can infer it from there. Sadly I was never able to find out how to get the map version, but if you do please let me know.

**Comment by xavier-rodet** [comment]
Thanks for the Gitter.

Right now i think that those kind of infos might be stored in Steam servers, and could be retrieved through Steam API from the "match id" contained within the ShareCode. (just a though)

If i find anything i'll let you know !

**Comment by xavier-rodet** [comment]
I found a way to get the demo datetime from [node-csgo](https://github.com/joshuaferrara/node-csgo), like this :
```js
// ...
var scDecoder = new csgo.SharecodeDecoder("CSGO-xxxxx-xxxxx-xxxxx-xxxxx-xxxxx");
var decode = scDecoder.decode();

// ...
CSGOCli.requestGame(decode.matchId, decode.outcomeId, parseInt(decode.tokenId, 10));
CSGOCli.on("matchList", function(list) {

	if (list.matches && list.matches.length > 0) {

		// match datetime is stored here
		var timestamp = list.matches[0].matchtime;
		var datetime = new Date(timestamp * 1000);
		console.log("Game played at ", datetime.toLocaleString());
	}
});
```
They are doing this through cs protobufs.


In your project you have the protobuf file "cstrike15_gcmessages.pb.go" with : 
```go
type CDataGCCStrike15V2_MatchInfo struct {
	Matchid            uint64                                           `protobuf:"varint,1,opt,name=matchid" json:"matchid"`
	Matchtime          uint32                                           `protobuf:"varint,2,opt,name=matchtime" json:"matchtime"`
	Watchablematchinfo *WatchableMatchInfo                              `protobuf:"bytes,3,opt,name=watchablematchinfo" json:"watchablematchinfo,omitempty"`
	RoundstatsLegacy   *CMsgGCCStrike15V2_MatchmakingServerRoundStats   `protobuf:"bytes,4,opt,name=roundstats_legacy,json=roundstatsLegacy" json:"roundstats_legacy,omitempty"`
	Roundstatsall      []*CMsgGCCStrike15V2_MatchmakingServerRoundStats `protobuf:"bytes,5,rep,name=roundstatsall" json:"roundstatsall,omitempty"`
}
```
And

```go
func (m *CDataGCCStrike15V2_MatchInfo) GetMatchtime() uint32 {
	if m != nil {
		return m.Matchtime
	}
	return 0
}
```
I wonder if you can use it to extract datetime from the demo ? (i'm new to Go and Protobufs)

**Comment by xavier-rodet** [comment]
About the game version, if found this (still in your "cstrike15_gcmessages.pb.go" file) : 

```go
type CMsgGCCStrike15V2_MatchmakingStart struct {
	AccountIds      []uint32              `protobuf:"varint,1,rep,name=account_ids,json=accountIds" json:"account_ids,omitempty"`
	GameType        uint32                `protobuf:"varint,2,opt,name=game_type,json=gameType" json:"game_type"`
	TicketData      string                `protobuf:"bytes,3,opt,name=ticket_data,json=ticketData" json:"ticket_data"`
	ClientVersion   uint32                `protobuf:"varint,4,opt,name=client_version,json=clientVersion" json:"client_version"`
	TournamentMatch *TournamentMatchSetup `protobuf:"bytes,5,opt,name=tournament_match,json=tournamentMatch" json:"tournament_match,omitempty"`
	PrimeOnly       bool                  `protobuf:"varint,6,opt,name=prime_only,json=primeOnly" json:"prime_only"`
}

func (m *CMsgGCCStrike15V2_MatchmakingStart) GetClientVersion() uint32 {
	if m != nil {
		return m.ClientVersion
	}
	return 0
}
```

and

```go
type CMsgGCCStrike15V2_MatchmakingServerMatchEnd struct {
	Stats             *CMsgGCCStrike15V2_MatchmakingServerRoundStats `protobuf:"bytes,1,opt,name=stats" json:"stats,omitempty"`
	Confirm           *CMsgGCCStrike15V2_MatchmakingGC2ServerConfirm `protobuf:"bytes,3,opt,name=confirm" json:"confirm,omitempty"`
	Rematch           uint64                                         `protobuf:"varint,4,opt,name=rematch" json:"rematch"`
	ReplayToken       uint32                                         `protobuf:"varint,5,opt,name=replay_token,json=replayToken" json:"replay_token"`
	ReplayClusterId   uint32                                         `protobuf:"varint,6,opt,name=replay_cluster_id,json=replayClusterId" json:"replay_cluster_id"`
	AbortedMatch      bool                                           `protobuf:"varint,7,opt,name=aborted_match,json=abortedMatch" json:"aborted_match"`
	MatchEndQuestData *CMsgGC_ServerQuestUpdateData                  `protobuf:"bytes,8,opt,name=match_end_quest_data,json=matchEndQuestData" json:"match_end_quest_data,omitempty"`
	ServerVersion     uint32                                         `protobuf:"varint,9,opt,name=server_version,json=serverVersion" json:"server_version"`
}

func (m *CMsgGCCStrike15V2_MatchmakingServerMatchEnd) GetServerVersion() uint32 {
	if m != nil {
		return m.ServerVersion
	}
	return 0
}
```

But i have no clue if it can be used directly from a demo file ...

**Comment by markus-wa** [comment]
Yeah it seems like `node-csgo` is making direct CSGO/Steam API calls. I doubt this info is in the demo.

While certainly doable, this is out of scope for this project. Maybe it could be it's own library but I'm not sure if it's a 1h or 10 day project.

Another, possibly easier, approach (depending on your use-case) would be to expose `node-csgo` as a microservice and do a simple `http.Get()` to look up the match data.

What kind of app are you developing?

**Comment by xavier-rodet** [comment]
Sure, if it needs to request Steam API calls than i agree that this feature is clearly out of scope for this project !
(I just wanted to show it to you, in case it could be requested directly from the demo)

It's not an issue for me as i'm building a webservice for CS:GO statistics, so i'll use node-csgo  for this part.

I'll notice you of my project when it is released !

**Comment by markus-wa** [comment]
> It's not an issue for me as i'm building a webservice for CS:GO statistics, so i'll use node-csgo for this part.

Awesome!

And yeah thanks for letting me know, I hadn't heard of `node-csgo` and it seems quite interesting. I might even create a sample project that shows how to use it with Go for others who are interested in this, similar to the [https://github.com/markus-wa/demoinfocs-golang/tree/master/examples/web-assembly](WASM example) (which actually might be of interest to you if you want to let clients parse demos in your app without using server resources!).

> I'll notice you of my project when it is released !

Yes please do 🙂, I'd also happily add the site to the `Projects using demoinfocs-golang` section in the readme.

**Comment by xavier-rodet** [comment]
Oh thanks, your WASM sample could have interested me but I'll handle this process with your library directly on my server within a full GO Web API (using [Gin](https://gin-gonic.com/)).

**Comment by markus-wa** [comment]
github.com/saiko-tech/csgo-centrifuge/ solves some of these issues - allowing you to get the workshopID from the map-version you get from a demo

that way the right radar image can be used and the date can be estimated by looking at the workshop map update date
