### ISSUE TITLE
Rank Update proto uses int32 for SteamID

### ISSUE THREAD

**Issue by allenymin** [markus-wa/demoinfocs-golang#128]
The rank update proto uses an int32 for 'account_id' which converts the actual int64 SteamIDs so it isn't the same when the event fires.

**Comment by markus-wa** [comment]
You are right, thanks for the report!

I wonder what the account_id might be then in that case. I'll try to investigate soon(TM).

**Comment by allenymin** [comment]
I think if you just change the proto to int64 instead of int32 it may fix itself

**Comment by markus-wa** [comment]
The proto is the official one from the game, we can't change it or it will break the parsing 🙁

**Comment by markus-wa** [comment]
It turns out `AccountID` is actually the 32-bit SteamID. I've deprecated `RankUpdate.SteamID` and added `RankUpdate.SteamID32`. `RankUpdate.SteamID` also still contains the 32-bit ID and is now documented accordingly.
