### ISSUE TITLE
Calculating money earned by players

### ISSUE THREAD

**Issue by xavier-rodet** [markus-wa/demoinfocs-golang#129]
**Higher goal**
I want to calculate the money earned from players in a game. For this i just need to compare their money between start & end of the rounds.

**Describe the solution you'd like**
I would like to access all 10 Players struct from `events.RoundStart` & `events.RoundEndOfficial`  (i need to count money from kills after `events.RoundEnd` to be as precise as possible).
Those events could give access to `Players []*Player` (would be fine for me) or `TerroristState *common.TeamState` and `CounterTerroristState *common.TeamState` (cleaner way ?)

**Additional context**
I still need `WinnerState *common.TeamState`  and `LoserState *common.TeamState` from  `events.RoundEnd` to access the money from players for the last round of the game!

**Comment by markus-wa** [comment]
I see there's `CCSPlayer.m_iMatchStats_CashEarned.000` - `CCSPlayer.m_iMatchStats_CashEarned.029`.

Maybe you can use `Player.Entity.FindProperty(fmt.Sprintf("m_iMatchStats_CashEarned.%03d", parser.GameState().TotalRoundsPlayed())).Value().IntValue`

I will look into supporting this natively in the future.

**Comment by xavier-rodet** [comment]
Thanks,

I'll play with it to see if it fit my needs, i'll come back to you then for confirmation.

By the way, is there any documentation about listing thoses entities properties ? (i found this repo : https://github.com/L33T/CSGO-Reflection but maybe you have a better source ?)

**Comment by markus-wa** [comment]
> By the way, is there any documentation about listing thoses entities properties ? (i found this repo : https://github.com/L33T/CSGO-Reflection but maybe you have a better source ?)

Here 🙂:
- debugging: https://github.com/markus-wa/demoinfocs-golang#debugging
  - e.g. `go run -tags debugdemoinfocs -ldflags '-X github.com/markus-wa/demoinfocs-golang.debugServerClasses=YES' app.go`
- sample output: https://github.com/markus-wa/demoinfocs-golang/wiki/Server-Classes
  - this might differ slightly between older and newer demos, some properties are only available for games played after certain updates

**Comment by xavier-rodet** [comment]
Good to know 👍 

So after some tests, it looks like `m_iMatchStats_CashEarned` is giving me the total money of the player, so it's pretty useless!

However my main issue was to access Players entities at `events.RoundStart` and `events.RoundEndOfficial` but i'm now retaining players pointers (on connection) to access them at any events i wish ! (I don't know why i didn't think about it before).

This way i can do any calculation i need 🙂

**Comment by markus-wa** [comment]
> However my main issue was to access Players entities at events.RoundStart and events.RoundEndOfficial but i'm now retaining players pointers (on connection) to access them at any events i wish ! (I don't know why i didn't think about it before).

What about `Parser.GameState().Participants().Playing()`?

Keeping every connected player might be slightly dangerous due to reconnects etc.

**Comment by xavier-rodet** [comment]
Thanks,

It seems to be a great solution 👍
