### ISSUE TITLE
I want to contribute

### ISSUE THREAD

**Issue by jnettome** [markus-wa/demoinfocs-golang#13]
Hey Markus! 
First of all, congrats for this excellent project and the good code you're writing.
I would love to help on it and discuss few ideas, can you send me an email or gimme yours?
Salut !

**Comment by markus-wa** [comment]
Thanks!
Sent you a mail.

**Comment by markus-wa** [comment]
We've now got a gitter, woo!

https://gitter.im/csgodemos/demoinfo-lib
