### ISSUE TITLE
Player additional status information

### ISSUE THREAD

**Issue by xXxhaxmeister42xXx** [markus-wa/demoinfocs-golang#132]
**Higher goal**
Higher abstraction level for player status information.

**Describe the solution you'd like**
Add more information like
`Player.IsPlanting`
Player is currently planting the bomb, taking plant abort and bomb planted into account
`Player.IsReloading`
Currently reloading a weapon (and therefore is unable to shoot)
`Player.IsFiring`
Player currently firing a round (Might even treat knife separately?). in case someone wants to render with flashy effects

possibly
`Player.IsAirborne`
not standing on the ground because jumping or falling
`Player.CarryingHostage`
might not be that important since this is mainly focused on defuse maps

**Describe alternatives you've considered**
One could probably retrieve that status information manually, but if given status information isnt too expensive to calculate it would be nice if the parser provides it without much of additional event handling.

(see my attempt, fairly new to Go and demo analyzing tho (: )
<details>
<summary>expand</summary>

quoted from [here](https://github.com/markus-wa/demoinfocs-golang/issues/115#issuecomment-515065745)

> While IsPlanting proved to be fairly easy to determine via the BombPlant-Events (an additional event.BombPlantAborted might help to more easily identify fake plants), reloading status seems to be more of a challenge.
> 
> I failed to get anything useful out of msg.CCSUsrMsg_ReloadEffect (networked reload sound effect? would have been good enough for what i wanted) and the player entity.
> This would be triggered when reloading is complete?
> 
> What i came up with during experimenting so far is the following, which
> - would require adding handlers for each weapon class individually? Not sure how to look for base classes
> - seems to produce quite a few "noones gun reloaded"
> - has incomplete reloads (maybe interrupted by round start or weapon switch?)
> 
> ```go
> parser.RegisterEventHandler(func(events.DataTablesParsed) {
>   parser.ServerClasses().FindByName("CAK47").OnEntityCreated(func(entity *sendtables.Entity) {
>     entityCName:= entity.FindPropertyI("m_AttributeManager.m_Item.m_szCustomName").Value().StringVal
>     //might want to watch m_iClip1 or m_iPrimaryReserveAmmoCount as well?
>     entity.FindPropertyI("m_bReloadVisuallyComplete").OnUpdate(func(val sendtables.PropertyValue){
>       ownHa := entity.FindPropertyI("m_hOwnerEntity").Value().IntVal
>       owner := parser.GameState().Participants().FindByHandle(ownHa)
>       ownerName:= "noone"
>       if owner!=nil {
>         ownerName = owner.Name
>       }
>       reload:= "reloaded"
>       if val.IntVal==0 {
>         reload = "reloading"
>       }
>       fmt.Printf("%d  %s's %s (%s) %s\n", entity.ID(), ownerName, entity.ServerClass().Name(), entityCName, reload)
>     })
>   })
> })
> ```
</details>

**Comment by markus-wa** [comment]
Yeah I could see this being useful.
For some we should maybe also add events, like `WeaponReload`.

Since for some use-cases it's interesting to know when exactly something starts/ends (in which case events are nice). And other times it's nice to be able to tell what state a player is in when some other event happened  (e.g. was the killed player planting, reloading etc.)

I will have to see if/when I can get to this. Otherwise PRs are always welcome.

**Comment by markus-wa** [comment]
Just some implementation hints for future me (or anyone, really).

- `Player.IsPlanting`
  TBD, unclear how we can know if the player aborted a plant.

- `Player.IsReloading`
  should be deducible by using `weapon_reload`, detecting weapon switches (`m_hActiveWeapon`) and `m_iClip1`

- `Player.IsFiring`
  I don't think this is valuable, as it's an instant action, I suggest to use `events.WeaponFire` instead.
  If we were to add it we'd have to set some arbitrary time how long the player was 'firing' after `weapon_fired`, this is not something I'd want in the lib. If needed it's better to do this in the consumer app.

- `Player.IsAirborne`
  TBD, will have to see how we can get this info.

- `Player.CarryingHostage`
  Some possibly related attributes: `m_bIsGrabbingHostage` (might be just during the pickup time), `m_hCarriedHostage` & `m_hCarriedHostage`

**Comment by xXxhaxmeister42xXx** [comment]
I'll try to cross-check events.WeaponReload with m_bReloadVisuallyComplete to see if that property of the currently equipped gun is viable for Player.IsReloading. I guess i'm able to create a PR when i'm done with experimenting.

The plant would at least be aborted if the player uncrouches, moves, or switches weapon.
I'm not sure if +attack/-attack commands of the player are somehow extractable, but i imagine they have to be somewhere. If they are, this would solve both IsPlanting and IsFiring.

**Comment by markus-wa** [comment]
> I'm not sure if +attack/-attack commands of the player are somehow extractable

I doubt that, unfortunately, since this is only needed for the server 🙁

**Comment by xXxhaxmeister42xXx** [comment]
Well, i finally came back to working on this and after some trial and error m_bReloadVisuallyComplete at last allows the retrieval of some non-complete-bullshit information (for 2nd reload [attempt] and after). Due to sources initialization of that property i dont really have an idea on how to properly use this for the reloading status.

<details><summary>Code</summary>

```go
reloadWeapon:= make(map[int]bool)
reloadPlayer:= make(map[int]int)
parser.RegisterEventHandler(func(e events.RoundStart){
	reloadPlayer = make(map[int]int)
	fmt.Printf("%d RoundStart\n", parser.GameState().IngameTick());
})
...

for _, v := range gamestate.Participants().Playing() {
    rp, rpex:= reloadPlayer[v.UserID]
    if !rpex {
        rp = 0
    }
    reloading:= false
    if v.ActiveWeapon()!=nil {
        class:= v.ActiveWeapon().Class();
        _, rwex:= reloadWeapon[v.ActiveWeapon().EntityID]
        if class==common.EqClassPistols || class==common.EqClassSMG || class==common.EqClassHeavy || class==common.EqClassRifle {
            prop:= state.Entities()[v.ActiveWeapon().EntityID].FindPropertyI("m_bReloadVisuallyComplete");
            if prop!=nil {
                if prop.Value().IntVal==0 {
                    reloading = rwex
                } else {
                    reloadWeapon[v.ActiveWeapon().EntityID] = true
                }
            }
        }
    }
    if reloading {
        if rp==0 || rp!=v.ActiveWeapon().EntityID {
            if rp!=0 {
                fmt.Printf("%d bReloadVis ended %s [rp!=ActiveWeapon]\n", state.IngameTick(), v.Name)
            }
            fmt.Printf("%d bReloadVis start %s %s\n", state.IngameTick(), v.Name, v.ActiveWeapon().Weapon)
            reloadPlayer[v.UserID] = v.ActiveWeapon().EntityID
        }
    } else if rp!=0 {
        if v.ActiveWeapon()==nil {
            fmt.Printf("%d bReloadVis ended %s [no active weapon]\n", state.IngameTick(), v.Name);
        }else if rp==v.ActiveWeapon().EntityID {
            fmt.Printf("%d bReloadVis ended %s %s [reload complete]\n", state.IngameTick(), v.Name, v.ActiveWeapon().Weapon)
        } else {
            fmt.Printf("%d bReloadVis ended %s [switched weapon]\n", state.IngameTick(), v.Name)
        }
        reloadPlayer[v.UserID] = 0
    }
}
```
</details>
<details><summary>Sample round output</summary>

```
XY is reloading is event.WeaponReload

40858 RoundStart
40998 bReloadVis start Panda Glock-18
41103 bReloadVis ended Panda [switched weapon]
41518 bReloadVis start Pancake MP9
41553 bReloadVis ended Pancake [switched weapon]
41643 bReloadVis start Pancake MP9
41663 bReloadVis ended Pancake [switched weapon]
41818 bReloadVis start Bear Desert Eagle
41853 bReloadVis ended Bear [switched weapon]
42398 unfreeze
43528 bReloadVis start Pancake MP9
43548 bReloadVis ended Pancake [switched weapon]
44028 bReloadVis start Pancake MP9
44038 bReloadVis ended Pancake [switched weapon]
44363 bReloadVis start Pancake MP9
44813 Squid is reloading his AK-47
45193 Suspect is reloading his p250
45538 Squid is reloading his AK-47
45538 bReloadVis start Squid AK-47
45688 bReloadVis ended Squid AK-47 [reload complete]
45993 bReloadVis start Duck USP-S
46013 bReloadVis ended Duck [switched weapon]
46398 bReloadVis ended Pancake [switched weapon]
46543 bReloadVis start Pancake MP9
46838 Squid is reloading his AK-47
46838 bReloadVis start Squid AK-47
46868 bReloadVis ended Pancake [switched weapon]
46983 bReloadVis ended Squid AK-47 [reload complete]
47218 bReloadVis start Pancake MP9
47228 bReloadVis ended Pancake [switched weapon]
47468 Squid is reloading his AK-47
47468 bReloadVis start Squid AK-47
47618 bReloadVis ended Squid AK-47 [reload complete]
48193 Squid is reloading his AK-47
48193 bReloadVis start Squid AK-47
48338 bReloadVis ended Squid AK-47 [reload complete]
48468 bReloadVis start Pancake MP9
49448 bReloadVis ended Pancake [switched weapon]
49763 bReloadVis start Pancake MP9
51158 Goat is reloading his MP7
51463 Bear is reloading his AK-47
51688 Suspect is reloading his XM1014
51688 bReloadVis ended Pancake [switched weapon]
51748 bReloadVis start Bear Desert Eagle
51768 bReloadVis ended Bear [switched weapon]
52178 bReloadVis start Pancake MP9
52898 Pancake is reloading his MP9
53008 bReloadVis ended Pancake MP9 [reload complete]
53103 Helix is reloading his AK-47
53223 Bear is reloading his AK-47
53223 bReloadVis start Bear AK-47
53368 bReloadVis ended Bear AK-47 [reload complete]
53398 bReloadVis start Bear Desert Eagle
53418 bReloadVis ended Bear [switched weapon]
54298 Goat is reloading his MP7
54298 bReloadVis start Goat MP7
54418 bReloadVis ended Goat [no active weapon]
56008 Squid is reloading his AK-47
56008 bReloadVis start Squid AK-47
56158 bReloadVis ended Squid AK-47 [reload complete]
```
</details>

m_flPostponeFireReadyTime miiight be my next shot, depending on what it takes into account for firing delay. Any idea what ```m_iState``` could be?
(According to [this](https://www.unknowncheats.me/forum/counterstrike-global-offensive/157216-auto-reload.html#post1312784) there might even be an m_bInReload? already a few years old)

**Comment by markus-wa** [comment]
Thanks for the analysis @xXxhaxmeister42xXx !

>Any idea what m_iState could be?

Not yet, I'll try to look into it.

> According to this there might even be an m_bInReload? already a few years old

Nope 🙁:
```terminal
$ go test -run TestDemoSet -tags debugdemoinfocsc -ldflags '-X github.com/markus-wa/demoinfocs-golang.debugServerClasses=YES' | grep 'm_bInReload' | wc -l
0
```

**Comment by markus-wa** [comment]
I think `m_iState` is about being active or holstered: https://github.com/ValveSoftware/source-sdk-2013/blob/master/sp/src/game/client/c_basecombatweapon.cpp#L53

**Comment by xXxhaxmeister42xXx** [comment]
It might not be a network var https://github.com/ValveSoftware/source-sdk-2013/blob/0d8dceea4310fde5706b3ce1c70609d72a38efdf/mp/src/game/shared/basecombatweapon_shared.h#L574

> PS: it doesn't seem to include reload as a state based on my experiments.

Yeah, but there has to be something so CS knows the reload started. Something stupidly obvious like [this](https://github.com/ValveSoftware/source-sdk-2013/blob/0d8dceea4310fde5706b3ce1c70609d72a38efdf/mp/src/game/shared/sdk/weapon_sdkbase.cpp#L145), but retrievable after the sound update.
The SDK link is quite useful, if just volvo would release some updates x(

_[Memo to myself](https://github.com/ValveSoftware/source-sdk-2013/blob/0d8dceea4310fde5706b3ce1c70609d72a38efdf/mp/src/game/shared/basecombatweapon_shared.cpp#L1986) to look for animations._

**Comment by markus-wa** [comment]
> It might not be a network var

Yeah in that case it won't be in the demo :(
