### ISSUE TITLE
Extended message event handling

### ISSUE THREAD

**Issue by xXxhaxmeister42xXx** [markus-wa/demoinfocs-golang#137]
Coming from #132 ```msg.CCSUsrMsg_ReloadEffect``` i finally noticed that
https://github.com/markus-wa/demoinfocs-golang/blob/03b772fa0c411fc23ac9869f3cc0877ab8cd2597/parsing.go#L254
only dispatches General/Server-[netmessages](https://github.com/markus-wa/demoinfocs-golang/blob/master/msg/netmessages.pb.go).
(Shouldn't it be ```int(msg.NET_Messages_net_SetConVar): func()  ...``` instead of a fixed ```6: func() ...``` in the [example](https://github.com/markus-wa/demoinfocs-golang/tree/master/examples/net-messages)? Might also want to add the protobuf import and that you have to use NewParserWithConfig)

This would mean both ```msg.CCSUsrMsg_ReloadEffect``` and [#127](https://github.com/markus-wa/demoinfocs-golang/issues/127#issuecomment-509226535) ```CDataGCCStrike15V2_MatchInfo```/```CMsgGCCStrike15V2_MatchmakingStart.ClientVersion```/```CMsgGCCStrike15V2_MatchmakingServerMatchEnd.ServerVersion```
are currently not accessible with this library?

Regarding match play time: i did at least find something for map version: CSVCMsg_ServerInfo contains a map checksum.
For 2D replay, promting the user to select a radar image might still be favourable :-)
https://github.com/markus-wa/demoinfocs-golang/blob/2764a36308e6f36a1108a3cafa6c0a1726460ea5/msg/netmessages.pb.go#L1903
```go
pcfg := demo.DefaultParserConfig
pcfg.AdditionalNetMessageCreators = map[int]demo.NetMessageCreator{
	int(msg.NET_Messages_net_SetConVar): func() proto.Message {return new(msg.CNETMsg_SetConVar)},
	int(msg.SVC_Messages_svc_ServerInfo): func() proto.Message {return new(msg.CSVCMsg_ServerInfo)},
}
parser := demo.NewParserWithConfig(demo, pcfg)
parser.RegisterNetMessageHandler(func(m *msg.CSVCMsg_ServerInfo){
	fmt.Println(fmt.Sprintf("ServerInfo crc:%d map:%s", m.MapCrc, m.MapName))
})
```

**Comment by markus-wa** [comment]
You should be able to handle any user messages by handling `msg.CSVCMsg_UserMessage`. I can try to give a better explanation when I'm back home later this week.

Maybe user_messages.go helps.

But in general I agree, the example has a few issue.

**Comment by markus-wa** [comment]
This should work for reloads (or any other user message)
```
parser.RegisterNetMessageHandler(func(um *msg.CSVCMsg_UserMessage) {
	reload := new(msg.CCSUsrMsg_ReloadEffect)
	reload.Unmarshal(um.MsgData) // TODO: add error check
	fmt.Println("reload:", *reload)
})
```

As for `CDataGCCStrike15V2_MatchInfo/CMsgGCCStrike15V2_MatchmakingStart.ClientVersion/CMsgGCCStrike15V2_MatchmakingServerMatchEnd.ServerVersion` I'm not sure what these are but if there are no net-messages with the corresponding IDs there is no way to parse them.

**Comment by markus-wa** [comment]
Just a quick question since there's quite a lot of different stuff in this issue:
do you expect any other changes besides the minor fixes in the example?

I could imagine adding events or getters for the map CRC but I don't think I really have time to do it myself in the near future. PR's are always welcome of course.

**Comment by xXxhaxmeister42xXx** [comment]
That does answer at least a part of my questions, thanks.

> do you expect any other changes besides the minor fixes in the example?

No, i primarily wanted to know how to access these messages. ->
```go
pcfg := democs.DefaultParserConfig
pcfg.AdditionalNetMessageCreators = map[int]democs.NetMessageCreator{
  //Does this have any [negative] impact, since user messages are already dispatched by default?
  int(msg.SVC_Messages_svc_UserMessage): func() proto.Message {return new(msg.CSVCMsg_UserMessage)},
}
parser := democs.NewParserWithConfig(demo, pcfg)

parser.RegisterNetMessageHandler(func(m *msg.CSVCMsg_UserMessage){
  switch(m.MsgType){
  case int32(msg.ECstrike15UserMessages_CS_UM_ReloadEffect):
    reload := new(msg.CCSUsrMsg_ReloadEffect)
    err := reload.Unmarshal(m.MsgData)
    if err==nil {
      fmt.Println(fmt.Sprintf("reload: %d %d @ %f/%f/%f", reload.Entidx, reload.Actanim, reload.OriginX, reload.OriginY, reload.OriginZ))
    }
  }
})
```

CDataGCCStrike15V2/CMsgGCCStrike15V2 might be wrapped like the user messages?
The only structs with a "type" and ```[]byte```s i found are
<details>
<summary>expand</summary>

https://github.com/markus-wa/demoinfocs-golang/blob/2764a36308e6f36a1108a3cafa6c0a1726460ea5/msg/netmessages.pb.go#L3196-L3199
https://github.com/markus-wa/demoinfocs-golang/blob/2764a36308e6f36a1108a3cafa6c0a1726460ea5/msg/netmessages.pb.go#L3248-L3252
https://github.com/markus-wa/demoinfocs-golang/blob/2764a36308e6f36a1108a3cafa6c0a1726460ea5/msg/netmessages.pb.go#L3420-L3430
(CMsgGCCStrike15V2_GC2ClientTextMsg in msg/cstrike15_gcmessages.pb.go L6209 as well)
</details>

I'll keep looking, but this might take from a while to eternity if i forget about it :D

I dont think an event for the mapcrc would be neccessary, using it to determine the map version should be rather tedious :^)
The ServerInfo as a whole might be more interesting, but not too hard to handle manually.

**Comment by markus-wa** [comment]
Cool, lmk if you find something. Might have a look as well if I find time.

Just a side note - I think this part isn't required:

```
pcfg.AdditionalNetMessageCreators = map[int]democs.NetMessageCreator{
  //Does this have any [negative] impact, since user messages are already dispatched by default?
  int(msg.SVC_Messages_svc_UserMessage): func() proto.Message {return new(msg.CSVCMsg_UserMessage)},
}
```

user messages are already parsed anyway so they should already get dispatched 🙂

**Comment by xXxhaxmeister42xXx** [comment]
Yeah sure. Although i currently don't have the highest expectations :(

Bad news for the CCSUsrMsg_ReloadEffect as well, while the next best demo in my replay folder that i used for testing (which happens to be a few years old) had these, they seem to be missing in more recent demo files.

**Comment by markus-wa** [comment]
Hmm, unfortunate. This might be linked to one of the sound updates from a while back.

I just saw there is a `weapon_reload` event. Does this provide the info you need?
Unfortunately there is no proper event for it, just a generic one.

```
p.RegisterEventHandler(func(e events.GenericGameEvent) {
	if e.Name == "weapon_reload" {
		player := gs.Participants().ByUserID()[int(e.Data["userid"].ValLong)]
		// TODO: do stuff with player position, ActiveWeapon() etc ...
	}
})
```

**Comment by markus-wa** [comment]
I've added `WeaponReload`. Maybe that helps you.

```go
parser.RegisterEventHandler(func(e events.WeaponReload) {
	fmt.Printf("%s is reloading his %s\n", e.Player.Name, e.Player.ActiveWeapon().Weapon)
})
```

```
kzy LJ∼ is reloading his USP-S
keev is reloading his USP-S
syrsoNR is reloading his USP-S
...
```

**Comment by markus-wa** [comment]
Note that `CDataGCCStrike15V2_MatchInfo` is a GC or GameCoordinator message. To my knowledge these are NOT contained in the demo but are used for CSGO to communicate with the matchmaking servers etc.

`CDataGCCStrike15V2_MatchInfo` is used in `CMsgGCCStrike15V2_MatchList`. I think this is the 'recent-matches' in the CSGO main menu.

Here's how to get the data you're asking for https://github.com/markus-wa/demoinfocs-golang/issues/127#issuecomment-509226535

**Comment by xXxhaxmeister42xXx** [comment]
> I've added WeaponReload. Maybe that helps you.

Most likely yes, thanks.

> Hmm, unfortunate.

:(

Yes, but that is for official MM, not for community servers.

According to this, CS might indeed be using the CRC for version checking,
[Which would leave only the CRC and network protocol version for determining the map version based on demo file data? :S]
https://steamcommunity.com/app/730/discussions/0/364042703853395015/

**Comment by markus-wa** [comment]
> According to this, CS might indeed be using the CRC for version checking,

I think so, yes.

**Comment by markus-wa** [comment]
> Regarding match play time: i did at least find something for map version: CSVCMsg_ServerInfo contains a map checksum.
For 2D replay, promting the user to select a radar image might still be favourable :-)

Over two years later I've got big news on this front :partying_face: 

[saiko-tech/csgo-centrifuge](https://github.com/saiko-tech/csgo-centrifuge) allows easily getting the correct radar image for any map version

### Usage

#### URL Formats
- `https://radar-overviews.csgo.saiko.tech/<map>/<crc>/radar.dds`
- `https://radar-overviews.csgo.saiko.tech/<map>/<crc>/radar.png`
- `https://radar-overviews.csgo.saiko.tech/<map>/<crc>/info.txt` - VDF format (Valve Data Format)

#### Examples

- https://radar-overviews.csgo.saiko.tech/cs_agency/2230463619/radar.dds
- https://radar-overviews.csgo.saiko.tech/cs_agency/2230463619/radar.png
- https://radar-overviews.csgo.saiko.tech/cs_agency/2230463619/info.txt
