### ISSUE TITLE
Binding a bot to a disconnected player

### ISSUE THREAD

**Issue by BestAwperEver** [markus-wa/demoinfocs-golang#139]
**Describe the bug**
When a player disconnects and a bot is added, sometimes the bot's entity has the same entityID as the one of already disconnected player. Since `bindNewPlayer` method first tries to get an already existing player by entityID, this leads to player mistakenly being treated as reconnected instead of adding a new bot-player.

**To Reproduce**
Matchmaking share link: steam://rungame/730/76561202255233023/+csgo_download_match%20CSGO-aDFev-GXaps-HXVym-k66e6-GLSKF

**Code**
Conditinal breakpoint at datatables.go:185, (`bindNewPlayer` first line) with `p.currentFrame == 74290` as the condition

**Expected behavior**
New bot-player with `userID == 22` added to the game.

**Library version**
v1.3.0

**Additional context**
I've faced this bug when collecting open-kills statistics. As a workaround, I manually check PlayerDisconnected and PlayerConnect events and track connected players in a separate data structure.

**Comment by markus-wa** [comment]
Thanks for the bug report!

Can you check if da8d275 solves the issue?

**Comment by BestAwperEver** [comment]
Seems like it does. Thank you for the fix!
