### ISSUE TITLE
mp5-sd weapon

### ISSUE THREAD

**Issue by qJkee** [markus-wa/demoinfocs-golang#140]
**Describe the bug**
In CS:GO we have a weapon named `mp5-sd`, but there is no such code for this gun [here](https://github.com/markus-wa/demoinfocs-golang/blob/master/common/equipment.go#L59)

**Library version**
e.g. v1.3.0

**Comment by markus-wa** [comment]
It's here: https://github.com/markus-wa/demoinfocs-golang/blob/master/common/equipment.go#L65

🙂

**Comment by qJkee** [comment]
Yea, I see, thanks)
But could you tag a new version with this weapon?
Because there is no MP5 in v1.3.0

**Comment by markus-wa** [comment]
Done!

https://github.com/markus-wa/demoinfocs-golang/releases/tag/v1.3.1
