### ISSUE TITLE
Raw events data

### ISSUE THREAD

**Issue by BestAwperEver** [markus-wa/demoinfocs-golang#141]
In some cases it would be quite handy to have access to event's raw information. E. g., in Kill event there is built-in flash assister and in PlayerFlashed there is ignored by library flash duration value which in not AFAIK always equal to player's flash duration because of flashes' overlaping. There is GenericGameEvent but it only "signals a otherwise unhandled event".

It is also could be usefull when there is some bug in the library, like the one in #139 where I could retrieve userid from the event and save some time investigating the origin of the problem 🙂

So, am I missing something? Is there some technique I can use for getting event's raw data?

**Comment by markus-wa** [comment]
It's your lucky day! There is `GenericGameEvent` which should contain everything you need.

Docs: https://godoc.org/github.com/markus-wa/demoinfocs-golang/events#GenericGameEvent

**Comment by BestAwperEver** [comment]
Oh I got it. The library actually does dispatch all known events as GenericGameEvent. That solves the problem.

However, there is another closely related quiestion I want to ask.

According to this [page](https://wiki.alliedmods.net/Counter-Strike:_Global_Offensive_Events), there are events that are not listed [here](https://github.com/markus-wa/demoinfocs-golang/blob/20b08974c6834e2f56dbf216ecbac7c6134a8ab2/game_events.go#L79). However, I never get a ParserWarn for [unknown event](https://github.com/markus-wa/demoinfocs-golang/blob/20b08974c6834e2f56dbf216ecbac7c6134a8ab2/game_events.go#L40). Does it mean that this [page](https://wiki.alliedmods.net/Counter-Strike:_Global_Offensive_Events) is outdated/wrong? It would be a pity because there are some very interesting events like `door_moving` or `item_purchase` which I'd like to have.

**Comment by BestAwperEver** [comment]
> It's your lucky day! There is `GenericGameEvent` which should contain everything you need.
> 
> Docs: https://godoc.org/github.com/markus-wa/demoinfocs-golang/events#GenericGameEvent

I was a bit mislead by its description 🙂 May be you can alter it to mention that all handled events are also dispatched here?

**Comment by markus-wa** [comment]
> I was a bit mislead by its description 🙂 May be you can alter it to mention that all handled events are also dispatched here?

Right, I forgot to adjust the comment when I changed it to be dispatched on all events, sorry.

Unfortunately `door_moving` & `item_purchase` (like many others) are never dispatched in CSGO demos (or at least I've never seen them so far).

You can check all available events in a demo and how often they occur with `go run -tags debugdemoinfocs examples/print-events/print_events.go -demo /path/to/replay.dem | grep GameEvent | cut -f2 -d' ' | sort | uniq -c`

(or you can also run your code in the same way with `-tag debugdemoinfocs` etc. - it doesn't have to be the example)

**Comment by markus-wa** [comment]
Fixed the `GenericGameEvent` docs in d47a55d

**Comment by BestAwperEver** [comment]
I see now. Thanks for your reply and also for your amazing job! Saved me hours and hours of investigation into CSGO depths 😄

**Comment by markus-wa** [comment]
No problem 🙂

Just a note that if an event occurs (or doesn't) in one demo it might *not* always be that way. Some events are only in old demos and some only in new ones for example.
