### ISSUE TITLE
ItemEquip with a nil player pointer

### ISSUE THREAD

**Issue by BestAwperEver** [markus-wa/demoinfocs-golang#142]
**Describe the bug**
In the demo linked below there is an event of item being equipped, but in the dispatched event the Player pointer appears to be `nil`. I researched it as far as I understand the library code and found that:
1) in the raw event data `userid` is 42;
2) `geh.gameState().playersByUserID[42]` is `nil`;
3) `geh.parser.rawPlayers[14].userID == 42`, so the player actually exists in the game. It is a bot btw.

Unfortunately, I cannot say what exactly is causing this behaviour. But there is several round restoring & restarting prior to the event so I assume it is somehow connected.

**To Reproduce**
https://www.hltv.org/download/demo/30352

Code:
Conditional breakpoint at game_events.go:67 (`playerByUserID` first line) with userID == 42 as the condition.

**Expected behavior**
e.Player pointing to the player with userid == 42.

**Library version**
v1.3.1

**Comment by markus-wa** [comment]
Thanks for the report!

So this seems to be yet another instance where we need to delay the event.

When the bot replaces the player. CSGO sends out a `item_equip` event for `EqKnife`.
This happens before the player entity is created.

By delaying the execution of the event handler function we should get this under control.

**Comment by markus-wa** [comment]
Can you try out the `issue-142` branch and verify if it fixes the issue?

**Comment by BestAwperEver** [comment]
Thank you for you reply!

For some reason, it didn't :( Still getting `nil` in the `geh.gameState().playersByUserID[userID]` at game_events.go:63 for `userID == 42`.

**Comment by markus-wa** [comment]
Strange, I'll have to look into it tomorrow.
Thanks for trying it out.

**Comment by BestAwperEver** [comment]
Looks like you have forgotten to actually append things so `delayedEventHandlers`? I think I've fixed it: I've replaced
```go
	delay := func(f gameEventHandlerFunc) gameEventHandlerFunc {
		return func(data map[string]*msg.CSVCMsg_GameEventKeyT) { f(data) }
	}
```
with
```go
	delay := func(f gameEventHandlerFunc) gameEventHandlerFunc {
		return func(data map[string]*msg.CSVCMsg_GameEventKeyT) {
			parser.delayedEventHandlers = append(parser.delayedEventHandlers, func() {
				f(data)
			})
		}
	}
```
and it resolved the issue for me :)

**Comment by BestAwperEver** [comment]
I also suspect that `item_remove` should also be delayed and the reason we don't have any troubles with it yet is that bot-players don't actually drop anything 😄

**Comment by markus-wa** [comment]
Awesome! Great work!

I will review/merge the pr tonight.

> I also suspect that item_remove should also be delayed

I think it's the opposite, if a player disconnects there will probably be `item_remove` events. If the event is delayed the player entity will already be destroyed.

A while ago i tried to delay all events until the end of a tick so everything is updated. but that ended very badly.

**Comment by BestAwperEver** [comment]
I'm glad that really worked :) I'm quite new to Go (in fact, I've learned it just to be able to use your library 😄) and still don't have enough confidence with it.
> I think it's the opposite, if a player disconnects there will probably be item_remove events. If the event is delayed the player entity will already be destroyed.

Sounds reasonable. I haven't thought of the moment when someone gets disconnected.

**Comment by markus-wa** [comment]
> in fact, I've learned it just to be able to use your library

Great to hear! Hope you're enjoying it 😄

I just merged the fix into master!
Let me know if you'd like a release/tag for it. If you don't need one I'll wait until there are a few more fixes/features until I tag it.

**Comment by BestAwperEver** [comment]
Thanks!

It is fine for now without a new release since it involves only bots which are not that much of importance 🙂
