### ISSUE TITLE
invalid memory address or nil pointer dereference with PlayerHurt

### ISSUE THREAD

**Issue by pnxenopoulos** [markus-wa/demoinfocs-golang#151]
Using the first game (on de_nuke) from this demo: [https://www.hltv.org/matches/2336336/heroic-vs-forze-european-champions-cup](https://www.hltv.org/matches/2336336/heroic-vs-forze-european-champions-cup)

I have a basic main function:

```
func main() {
	f, err := os.Open(ex.DemoPathFromArgs())
	defer f.Close()
	checkError(err)

	p := dem.NewParser(f)

	// Parse header
	header, err := p.ParseHeader()
	checkError(err)
	fmt.Println("Map:", header.MapName)

	// Register player damage
	p.RegisterEventHandler(func(e events.PlayerHurt) {
		attacker := e.Attacker.Name
		player_hurt := e.Player.Name
		fmt.Printf("%s attacked %s\n", attacker, player_hurt)
	})

	// Parse to end
	err = p.ParseToEnd()
	checkError(err)
}
```

It runs for quite a few rows then gives the following error:

```
facecrack attacked Snappi
232522 
facecrack attacked Snappi
232553 
FL1T attacked stavn
232578 
Snappi attacked facecrack
232615 
FL1T attacked stavn
232616 
panic: runtime error: invalid memory address or nil pointer dereference
[signal SIGSEGV: segmentation violation code=0x1 addr=0x78 pc=0x13b9065]

goroutine 9 [running]:
main.main.func1(0xc001ae2000, 0x0, 0x59, 0x0, 0xc00529f400, 0x0, 0x0, 0xb, 0x0, 0x0)
	/Users/pxenopoulos/Downloads/demoinfocs-golang/examples/print-events/print_events_copy.go:30 +0xd5
reflect.Value.call(0x13f2200, 0xc000a02010, 0x13, 0x148fde4, 0x4, 0xc003853a48, 0x1, 0x1, 0xc00212c6a8, 0x1267cd0da681a701, ...)
	/usr/local/go/src/reflect/value.go:460 +0x5f6
reflect.Value.Call(0x13f2200, 0xc000a02010, 0x13, 0xc003853a48, 0x1, 0x1, 0x50, 0xc00529f450, 0x100b896)
	/usr/local/go/src/reflect/value.go:321 +0xb4
github.com/markus-wa/godispatch.(*Dispatcher).Dispatch(0xc0000fa090, 0x1467d20, 0xc00529f450)
	/Users/pxenopoulos/go/pkg/mod/github.com/markus-wa/godispatch@v1.1.0/dispatch.go:48 +0x24f
github.com/markus-wa/demoinfocs-golang.gameEventHandler.dispatch(...)
	/Users/pxenopoulos/Downloads/demoinfocs-golang/game_events.go:55
github.com/markus-wa/demoinfocs-golang.gameEventHandler.playerHurt(0xc0000fa000, 0x0, 0xc00217fe60)
	/Users/pxenopoulos/Downloads/demoinfocs-golang/game_events.go:296 +0x3ee
github.com/markus-wa/demoinfocs-golang.(*Parser).handleGameEvent(0xc0000fa000, 0xc00b41bb80)
	/Users/pxenopoulos/Downloads/demoinfocs-golang/game_events.go:37 +0x16f
reflect.Value.call(0x13f1c40, 0xc00005e560, 0x13, 0x148fde4, 0x4, 0xc003853f68, 0x1, 0x1, 0xc0000bac98, 0x201b3063bfa15801, ...)
	/usr/local/go/src/reflect/value.go:460 +0x5f6
reflect.Value.Call(0x13f1c40, 0xc00005e560, 0x13, 0xc003853f68, 0x1, 0x1, 0x0, 0x0, 0x0)
	/usr/local/go/src/reflect/value.go:321 +0xb4
github.com/markus-wa/godispatch.(*Dispatcher).Dispatch(0xc0000fa020, 0x14726e0, 0xc00b41bb80)
	/Users/pxenopoulos/go/pkg/mod/github.com/markus-wa/godispatch@v1.1.0/dispatch.go:48 +0x24f
github.com/markus-wa/godispatch.(*Dispatcher).dispatchQueue(0xc0000fa020, 0xc00002e180)
	/Users/pxenopoulos/go/pkg/mod/github.com/markus-wa/godispatch@v1.1.0/dispatch.go:97 +0xf4
created by github.com/markus-wa/godispatch.(*Dispatcher).AddQueues
	/Users/pxenopoulos/go/pkg/mod/github.com/markus-wa/godispatch@v1.1.0/dispatch.go:83 +0x183
exit status 2
```

This using on Mac OSX using Go 1.13.1.

Any idea?

**Comment by markus-wa** [comment]
Hey @pnxenopoulos!

While I'm not sure which line is #30, I assume the Attacker is nil.


This is just a guess but maybe it's 'world' damage (falling etc.).

I will check the demo some time this weekend to see if that's the case.
If so we should probably document this 😅

**Comment by pnxenopoulos** [comment]
Hey!

That's what I was thinking, too. And it does seem like `e.Attacker` is `nil` in those cases. Let me know if there's anything I can do to help.

Love the parser. Thanks for your work.

**Comment by markus-wa** [comment]
Nice, thanks for the quick verification.

Actually, if you could create a PR that just adds a new comment after the field `Attacker` saying `May be nil if the player is taking world damage (e.g. fall damage).` that would be brilliant as I'm currently on mobile.

If not, no worries, I'll try to get to it some time over the coming days 🙂

And thanks for the support!

**Comment by pnxenopoulos** [comment]
I can get to that. I will say though, it seems in all cases (for this demo) that the Attacker is `nil`, that the `EquipmentElement` for the weapon is 0, which is `EqUnknown`. It also seems that these `PlayerHurt` events with `nil` Attacker occur all over the place: in rounds, in between rounds etc.

**Comment by markus-wa** [comment]
Hmm, ok. In that case let's wait a bit. I will try to analyze it further as well.

**Comment by markus-wa** [comment]
So it is deffo world damage. This includes fall damage and bomb damage.
I checked by re-watching the demo and every instance where it occurs in this demo it's one of the two.

I've updated the docs accordingly 🙂.

Please re-open if there is still something you think is incorrect/strange.
