### ISSUE TITLE
Weapon's entity is missing a property

### ISSUE THREAD

**Issue by BestAwperEver** [markus-wa/demoinfocs-golang#152]
**Describe the bug**
If a weapon has a tag given by player, it is stored in `m_szCustomName` entity's property and can be parsed from the demo. However, it is missing when parsing using the library.

**To Reproduce**
http://replay189.valve.net/730/003373135669235810461_0315868020.dem.bz2

If this demo is parsed and dumped using [Valve's official tool](https://github.com/ValveSoftware/csgo-demoinfo), there is an entry for weapon custom tag on line 282076:
```
(line 282058) Table: DT_WeaponDEagle
...
(line 282076) Field: 409, m_szCustomName = CS Best Commandor
```
[first 282096 lines of demodump.log](https://github.com/markus-wa/demoinfocs-golang/files/3718136/demodump.log)
(full log is about half a gigabyte so I cannot attach it here)
It also pops up later but this is the first entry.

Code:
```go
app.parser.RegisterEventHandler(func(e events.DataTablesParsed){
	weapons := app.parser.ServerClasses().FindByName("CDEagle")
	weapons.OnEntityCreated(func(entity *st.Entity){
		if prop := entity.FindPropertyI("m_szCustomName"); prop != nil {
			// prop is always nil
			prop.OnUpdate(func(val st.PropertyValue){
				fmt.Printf("m_szCustomName: %v\n", prop.Value())
			})
		}
	})
})
```

I've also exported `findByDataTableName()` method in case I got the class name wrong and tried to find entities by `DT_WeaponDEagle` table name but that didn't work either (found the same server class and `prop` again was always `nil`) .

**Expected behavior**
Deagle entity having `m_szCustomName` property with value `"CS Best Commandor"`

**Library version**
v1.3.3

**Additional context**
I realize it is not what the library is designed for but still I'd like to use it for the purpose of having weapon model information because I already got used to it 😄 
It would be nice if I'd be given some advice where should I look to fix this myself because I'm stuck for now. I'm not even sure if this is a bug, may be I just don't know where to look.

**Comment by BestAwperEver** [comment]
Got it! I should have looked for `"m_AttributeManager.m_Item.m_szCustomName"` instead. Case closed 😃

**Comment by markus-wa** [comment]
Ah, glad you already found the issue 😄
