### ISSUE TITLE
Unable to determine which flashbang grenade blinds which players

### ISSUE THREAD

**Issue by xavier-rodet** [markus-wa/demoinfocs-golang#158]
**Higher goal**
Currently we can detect which player is flashing which player, but we can't do it at the flashbang grenade scope which i really would like to know to dermine flash efficiency per flashbang.

**Describe the solution you'd like**
[events.PlayerFlashed](https://godoc.org/github.com/markus-wa/demoinfocs-golang/events#PlayerFlashed) should hold the [Projectile *common.GrenadeProjectile](https://godoc.org/github.com/markus-wa/demoinfocs-golang/common#GrenadeProjectile)

**Comment by markus-wa** [comment]
Good idea!

I've created #159 - please review 🙂
