### ISSUE TITLE
Unable to determine which grenades damaged which players

### ISSUE THREAD

**Issue by xavier-rodet** [markus-wa/demoinfocs-golang#160]
**Higher goal**
Like i'm doing with the flashes now (thanks to you!) i would like to determine damaging grenades (HE, molotov, incendiary) efficiency per grenade !

Currently grenade events (like [GrenadeProjectileThrow](https://godoc.org/github.com/markus-wa/demoinfocs-golang/events#GrenadeProjectileThrow)) give access to a [GrenadeProjectile](https://godoc.org/github.com/markus-wa/demoinfocs-golang/common#GrenadeProjectile), while [PlayerHurt](https://godoc.org/github.com/markus-wa/demoinfocs-golang/events#PlayerHurt) event give acces to an [Equipment](https://godoc.org/github.com/markus-wa/demoinfocs-golang/common#Equipment) (which is fine!).

However after some test, i can tell that the grenade `GrenadeProjectile.UniqueID()` is different from the grenade `Equipment.UniqueID()` (for the exact same grenade) which make it impossible to track from throwing to damaging !

**Describe the solution you'd like**
It would be awesome that they both share the same UniqueID because a Projectile is a Weapon ?

**Describe alternatives you've considered**
If Projectile & Equipment needs to be totally separated, the other solution would be to have access to the corresponding Equipment from a Projectile ?

I don't know which solution is the best/easier from behind the scene :p

**Comment by markus-wa** [comment]
Hmm, I see.

I'm not sure if this is possible since the grenade that's in a player's inventory is a completely different entity from the projectile.

I will look into it but can't promise anything 🙂

**Comment by xavier-rodet** [comment]
Indeed I was afraid it would not be easy to manage...

I'm also trying to find a way to do it!

**Comment by xavier-rodet** [comment]
Ok,

So here I am : 

The idea is to store (at the player level) all the grenades (Equipment) references from the moment a player Throw a grenade, to the moment where the grenade effect is ended.

This way we can simply retrieve the same Equipment reference  by simply requesting a Grenade Type for a specific player which will return the first Grenade found in our "storage" (or a new Equipment of the same type if not found).
	
Caution, there is two distinct "ending grenade effect" behaviours (which is the point when we want to delete the weapon reference) : 

- Inferno projectiles (Molotov & incendiary) works differently : their projectiles are destroyed BEFORE damaging players (damaged are done by flames, not by the projectile itself) : _GrenadeProjectileThrow -> GrenadeProjectileDestroy -> FireGrenadeStart  -> PlayerHurt -> **FireGrenadeExpired**_

- Others projectiles (like HE) are destroyed AFTER damaging players which is great : _GrenadeProjectileThrow -> HeExplode -> PlayerHurt -> **GrenadeProjectileDestroy**_

I made the changes on my fork that you can find [here](https://github.com/markus-wa/demoinfocs-golang/compare/master...xavier-rodet:Grenade-Consistency?expand=1).

However the code is probably broken or not perfect as i'm not really familiar with golang 😄

**Note:** Currently, i'm even sure it won't work because _GrenadeEvent.Thrower_ seems to be nil and i need it to clear inferno grenades reference when they expired.

Please tell me what do you think about it ?
Do you want me to make A PR of it ? (this won't be merged until you review it right ?)

**Comment by markus-wa** [comment]
Thanks for your inestivation @xavier-rodet !

Yes please create a PR. I think we will need a couple of changes on where and how we store the info but I'll give more details in the PR.

For infernos/mollies we might be able to store some infos about the last thrown grenade by a given player like the hack we do to get `PlayerFlashed.Projectile` 🙂

**Comment by xavier-rodet** [comment]
Done !

Glad it could help 😃

**Comment by markus-wa** [comment]
I merged the PR.

Thanks a lot for all the effort that went into this @xavier-rodet !

🎉🎉
