### ISSUE TITLE
Identify bots that are controlled by players (Player.IsBot)

### ISSUE THREAD

**Issue by xavier-rodet** [markus-wa/demoinfocs-golang#164]
**Describe the bug**
I'm not totally sure if it was intended like that but in my opinion `IsBot` should be `true` if :
- a player is a Bot
- **a player is a Bot controlled by a Player** (seems not to be the case)

**To Reproduce**
Demo : https://gofile.io/?c=ORPE2u

Round 6, player "njr" got killed, then take control of the bot and got killed again.

Code:
```go
parser.RegisterEventHandler(func(e events.Kill) {

	e.Victim.IsBot // Is false on both death
})
```

**Expected behavior**
On his second death, `IsBot` should be set to `true`

**Comment by BestAwperEver** [comment]
While you cannot get the information you need directly from `common.Player`'s fields, you are still able to retrieve it from the player's entity's properties, e.g.
```go
if e.Victim.Entity.FindPropertyI("m_bIsControllingBot").Value().IntVal == 1 {
    // process situation when e.Victim was controlling a bot
}
```
Hope that will help!

**Comment by xavier-rodet** [comment]
Thanks, it does works !

After all i think we should keep the actual `IsBot` behaviour and just add the method `IsControllingBot()` as they are two different cases.

**Comment by markus-wa** [comment]
I'm thinking of adding a `Player.ControllingPlayer()` which would return the player controlling the bot if `IsBot == true` or return `nil` if false.

**Comment by xavier-rodet** [comment]
Well I don't think this is the right way to do it because currently when a Player is controlling a Bot, the Player entity IS already the controlling player, so `Player.ControllingPlayer()` doesn't make sense to me.

We should do this : 
- leave current `IsBot` logic : it is true ONLY when it's a bot (not controlled by a player)
- add the method IsControllingBot() which return true when it's a player controling a bot by doing this checking : 
```go
return player.Entity.FindPropertyI("m_bIsControllingBot").Value().IntVal == 1
```

It simple and doesn't break anything IMO, but maybe i'm missing something ? 😄

**Comment by markus-wa** [comment]
> the Player entity IS already the controlling player (not the Bot)

interesting, thanks for the hint.

However I'm still missing which player is controlling which bot in this situation, no?

What if there are multiple bots? `m_bIsControllingBot` would then just say the player is controlling *a* bot, but not which one, right?

I will run some tests and report back 🙂

**Comment by markus-wa** [comment]
Ah I see, we can use `m_iControlledBotEntIndex` to get the bot that is being controlled
