### ISSUE TITLE
add AllByUserID() method to IParticipants

### ISSUE THREAD

**Issue by BestAwperEver** [markus-wa/demoinfocs-golang#167]
**Higher goal**
In some cases I need to be able to get a (just) disconnected player by their user id. This is not possible as it is right now mainly because `IParticipants.ByUserID()` checks `v.IsConnected` before appending user to the return map. 

**Describe the solution you'd like**
Add `AllByUserID()` method to `IParticipants` interface which will return a (copy of) `playersByUserID` map, including disconnected users.

**Describe alternatives you've considered**
There is another `IParticipants.All()` method which returns all players despite of being connected of not, but it returns a list intead of a map, so it is not very convinient to use it for getting a player by user id.

**Additional context**
I faced this problem when processing `player_death` event with use of `GenericGameEvent` instead of `Kill`. When a user disconnects, they kill themselves, and in `Kill` event this is fine since inside a library it gets a `common.Player` pointer directly from `playersByUserID` map. However, when the same death is processed via `GenericGameEvent`, there is no way to get a `common.Player` pointer aside from iterating through list returned by `IParticipants.All()`.

**Comment by markus-wa** [comment]
Sounds reasonable 🙂

**Comment by markus-wa** [comment]
Thanks for implementing this @BestAwperEver

**Comment by BestAwperEver** [comment]
Well, as we say in Russia, initiative should be punishable 😄

**Comment by markus-wa** [comment]
😄
