### ISSUE TITLE
Persistent team id

### ISSUE THREAD

**Issue by zyphie** [markus-wa/demoinfocs-golang#17]
Currently, since CCSTeam entities don't switch on team-switches (players switch instead), the TeamState id field stays the same.

Id should stay consistent on team-switches, and then we can instead have a side field in TeamState to display which side a team is on (which is in effect what TeamState.id tells us currently).

A potential solution is to create logic on player switches. This logic detects team-switches:

```
	type TeamSwitch struct {
		tickPlayerSwitch int
		numPlayerSwitch  int
		teamSwitchDone   bool
	}

	ts := TeamSwitch{tickPlayerSwitch: -1}

	p.RegisterEventHandler(func(e events.PlayerTeamChangeEvent) {
		tick := p.GameState().IngameTick()
		numPlayers := len(p.GameState().PlayingParticipants())
		if tick > ts.tickPlayerSwitch {
			// First player switch, fix ts
			ts.numPlayerSwitch = 1
			ts.tickPlayerSwitch = tick
			ts.teamSwitchDone = false
		} else if tick == ts.tickPlayerSwitch {
			ts.numPlayerSwitch++
			if (ts.teamSwitchDone == false) && (ts.numPlayerSwitch >= numPlayers-1) {
				// We now assume we have a change of sides.
				// Creates a margin of one in case of missing event
				ts.teamSwitchDone = true
				fmt.Println("Change of sides")
			}
		}
	})
```

**Comment by markus-wa** [comment]
Oops, GitHub accidentially closed this.

**Comment by markus-wa** [comment]
Closing to clean up.

Please reopen if you think this isn't fixed yet.
