### ISSUE TITLE
nil weapon in PlayerHurt event

### ISSUE THREAD

**Issue by BestAwperEver** [markus-wa/demoinfocs-golang#171]
**Describe the bug**
In a demo provided there is a `PlayerHurt` event which hold `nil` pointer to `Weapon` instance and `WeaponString` is also `""`. In game a player was hurt with a decoy grenade.

**To Reproduce**
https://www.hltv.org/download/demo/54175
Map 2 -- Dust 2

Code:
Conditional breakpoint at `game_events.go:633` (`getThrownGrenade`) with `geh.parser.gameState.ingameTick == 328041` as the condition.

**Expected behavior**
`Weapon` pointer pointing to decoy grenade that a player was hurt with (or at least a new `Equipment` instance holding `EqDecoy` value)

**Library version**
v1.7.0

**Additional context**
Code reaches the line commented with
`// if it's not a smoke this should never be reached`
so something definitely went wrong 😃

**Comment by markus-wa** [comment]
hoping to find some time for this over the weekend.

I wonder if this is a timing issue, maybe the decoy is still available one frame before this.

**Comment by BestAwperEver** [comment]
I checked and the decoy gets deleted in the same tick but before the `PlayerHurt` event is dispatched.

The reason for this behaviour is that the decoy first "exploded", then got deleted, and then did a bit of damage. I think the solution would be to delay `deleteThrownGrenade` to the end of the tick.

Also decoy's `Owner` is `nil`. Don't really know where does this come from, but imo it should point to the actual thrower.

**Comment by markus-wa** [comment]
I've put out v1.7.1 with the fix from #174. LMK if there's an issue with it that I missed 🙂

happy holidays!

**Comment by BestAwperEver** [comment]
Sorry for the late response -- was quite ill recently 😞 

While this fix allows demo to be parsed without any issues I still think that we shouldn't delay the whole event. The reason is simple -- it breaks in-game event order (like any other event delaying) and we generally should avoid this. E.g. because now we get
```
DEBUG: tick 328041: DeStRoYeR/wY/ hurt Viva^JBO with Decoy Grenade in Generic (97 hp left, 3 damage)
DEBUG: tick 328041: DeStRoYeR/wY/'s decoy expired
```
instead of
```
DEBUG: tick 328041: DeStRoYeR/wY/'s decoy expired
DEBUG: tick 328041: DeStRoYeR/wY/ hurt Viva^JBO with Decoy Grenade in Generic (97 hp left, 3 damage)
```
we cannot tell inside `PlayerHurt` event if a player was hit by decoy projectile or by its explosion. Yes, we still can do many things to determine if a player was hit after the grenade actually exploded but you get the point 😃 Maybe there even already is an existing code somewhere which relies on these events being dispatched in particular order (although I doubt it).

I wonder if this
```go
func (geh gameEventHandler) decoyDetonate(data map[string]*msg.CSVCMsg_GameEventKeyT) {
	event := geh.nadeEvent(data, common.EqDecoy)
	geh.dispatch(events.DecoyExpired{
		GrenadeEvent: event,
	})

	geh.parser.delayedEventHandlers = append(geh.parser.delayedEventHandlers, func() {
		geh.deleteThrownGrenade(event.Thrower, common.EqDecoy)
	})
}
```
breaks anything (along with un-delaying the event)? If it doesn't it would be a better solution imo. It did work for me but I'm not sure if it was just a chance.

And happy holidays to you too!

**Comment by markus-wa** [comment]
Oh that's a great idea actually, I hadn't thought of that!

**Comment by markus-wa** [comment]
I've made the change in #175 and added you as co-author. Will merge it if Travis is happy.
