### ISSUE TITLE
make Inferno.Thrower() search inside playersByUserID as a fallback

### ISSUE THREAD

**Issue by BestAwperEver** [markus-wa/demoinfocs-golang#176]
**Higher goal**
Sometimes `Inferno.Thrower()` returns `nil` for connected and valid players. This happens when a player is dead and doesn't have corresponding entity. The goal of this proposion is to make `Inferno.Thrower()` return valid `player` pointer in these cases.

**Describe the solution you'd like**
If a player cannot be found in `playersByEntityID` map, the library should try to match a player by entity id looking through the `playersByUserID`.

**Additional context**
Right now I use this as a workaround:
```go
thrower := inferno.Thrower()
if thrower == nil {
	throwerEntityID := inferno.Entity.FindPropertyI("m_hOwnerEntity").Value().IntVal & ((1 << 11) - 1)
	for _, p := range app.parser.GameState().Participants().All() {
		if p.EntityID == throwerEntityID {
			thrower = p
			break
		}
	}
}
if thrower != nil {
	…
}
```

**Comment by BestAwperEver** [comment]
I'd like to create a PR for this but I'm not sure where the changes should be made. There are several candidates:
`Inferno.Thrower`
`demoInfoProvider.FindPlayerByHandle`
and
`Participants.FindByHandle`

The first one is obviously the safest choice, the second one is also used in `Player.ControlledBot` and the last one is used in `Parser.bindBomb` and `Parser.bindGrenadeProjectiles` as well. The question is -- will it violate any current behaviour and if it does, should it?

I feel like the second one is the one we can safely modify but again I'm not sure.

**Comment by markus-wa** [comment]
I think we can do it directly in `Participants.FindByHandle`.

Just add it as a fallback to the existing code if no player is found. Shouldn't lead to any issues I would hope 🙂.
