### ISSUE TITLE
Bombsite with index 260 not found

### ISSUE THREAD

**Issue by vidosits** [markus-wa/demoinfocs-golang#180]
**Describe the bug**
I've came across a demo from 2 years ago, for which the parser crashes with
`panic: Bombsite with index 260 not found`
`in github.com/markus-wa/demoinfocs-golang.gameEventHandler.bombEvent()`
**To Reproduce**
Download from: [hltv](https://www.hltv.org/matches/2311540/outlaws-vs-bpro-esl-southeast-europe-championship-season-5-bulgaria-wild-card), 3rd map (cobblestone)

Code:
```
package main

import (
	dem "github.com/markus-wa/demoinfocs-golang"
	"os"
)

func main() {
	f, _ := os.Open("outlaws-vs-bpro-map3-cobblestone.dem")
	defer f.Close()
	
	dem.NewParser(f).ParseToEnd()	
}
```

**Expected behavior**
Parser shouldn't crash. 

**Library version**
e.g. v1.7.4

**Additional context**
Stepping into the `func bombEvent()` in `game_events.go` line 513, `t==nil`. Looking at `geh.parser.triggers` it's empty. I suspect the reason it's empty, is because the parser is looking for entities with `CBaseTrigger` class in `datatables.go` at line 160. This particular demo however does not have `CBaseTrigger`, it does however has `DT_BaseTrigger` with index 260, which has the exact same information.

**Comment by markus-wa** [comment]
Hey @vidosits, thanks for the bug report and detailed analysis!

Would you like to attempt a PR with a fix for this? Otherwise I will try to look into it over the next few days.

**Comment by vidosits** [comment]
Hey @markus-wa, well, I would be happy to. The are a couple of problems though:

- There are some demos that use the `DT_` prefix instead of `C`. E.g.: This demo has `DT_CSGameRulesProxy` instead of `CCSGameRulesProxy`, this is one of them
- However, the parser has no problem calling `bindGameRules()`, which uses `CCSGameRulesProxy` so I'm not sure why it has problem finding `DT_BaseTrigger` instead of `CBaseTrigger`

I think if you could explain that to me, because I'm not quite sure about all details of the parser implementation, then I could attempt a fix and a PR.

**Comment by vidosits** [comment]
What's particularly unfortunate is that the bombEvent() handler `panic()`s if the bombsite is not found in triggers and since it doesn't have a recover() attached this crashes the whole app.

**Comment by markus-wa** [comment]
I agree, the use of `panic` is really bad here.

As for why it works with GameRulesProxy and not the bombsites I'm not sure, I'll try to investigate.

**Comment by vidosits** [comment]
@markus-wa Could you point me towards the place where the handling of the `C` vs `DT_` prefix gets handled for other entities? All I could find were the hardcoded names of the `C` prefix entities (e.g.: `CCSPlayerResource`, `CBaseTrigger`, etc.) but surely the `DT_` prefix stuff happens somewhere, because I **have** processed demos before where there was `DT_CSPlayerResource` and that went without any errors. Maybe those demos had both of them? I'm not sure.

**Comment by vidosits** [comment]
Never mind, I just realized I'm confusing serverclass names with their datatable names. What's interesting is that inspecting the [appropriate line ](https://github.com/markus-wa/demoinfocs-golang/blob/c287ce326a03f7890fb7d33b2bee7d977beea95c/datatables.go#L164) the debugger shows that `CBaseTrigger` is indeed in the `serverClasses` slice.

**Comment by vidosits** [comment]
Okay. After further investigating there's a `Bomb Defused` event happening at the 16. frame of the demo. However at this time `p.stParser.ServerClasses().FindByName("CBaseTrigger").OnEntityCreated(func(baseTrigger *st.Entity) {}` event does not get fired, so the `triggers` slice is empty. Also, when I looked into the details of the `BombEvent` the defuser was `nil` so I used `delayIfNoPlayers` with `bombDefused` (and to be safe all of the bomb events, since they don't make much sense without players in the game) and the panic went away.

**Comment by markus-wa** [comment]
sorry for dropping the ball on this @vidosits, I currently have a lot going on with work and preparing to move countries later this month.

I'm glad you figured things out, thanks a lot for your continued analysis.

I don't think I will have time to do the fix myself over the next few weeks, but if you could create a PR then I could do a review and merge.
The solution with `delayIfNoPlayers` for bomb events sounds reasonable, so if that works for your demos I would say let's go for it! :smile:

**Comment by vidosits** [comment]
Hey, no problem, you didn't drop anything :) Hopefully, the PR is reasonable? I literally just added the couple of calls and that solved all instances of this particular problem for me. Good luck with work and moving!

**Comment by markus-wa** [comment]
v1.7.5 is now released with the fix: https://github.com/markus-wa/demoinfocs-golang/releases/tag/v1.7.5

I also filed #183 for making sure we don't panic on public APIs in general, though it might be a while until I get to it.

**Comment by vidosits** [comment]
Thanks so much Markus!

**Comment by markus-wa** [comment]
Thank **you** for the fix 😄
