### ISSUE TITLE
Implement fallback to svc_ServerInfo for corrupted demo headers with missing FrameRate

### ISSUE THREAD

**Issue by markus-wa** [markus-wa/demoinfocs-golang#184]
From Gitter: https://gitter.im/csgodemos/demoinfo-lib?at=5e3f038a340a8019bbade3e7

**Higher goal**
> Recently I've been having many issues with parsing demos from Europe Minor Qualifier ESL One Rio 2020.
It happens because demo header is corrupted so I'm not able to get correct FrameRate.

**Describe the solution you'd like**
> Possible fix: Get tick interval from svc_ServerInfo and use it to calculate tickrate for header.
> This fix was implemented recently on another parsing library https://github.com/saul/demofile/commit/66d04d1432a8ae02270f77dbece6167fa100e31e

**Describe alternatives you've considered**
\-

**Additional context**
\-

**Comment by BestAwperEver** [comment]
Until this is implemented I suggest everyone interested in getting the correct tickrate do the following:
```go
freezeTimeTickrate := int(.5 + float64(app.parser.GameState().IngameTick()-app.curRoundStartTick)/
	app.freezeTime.Seconds())

if correctTickrate(freezeTimeTickrate) {
	app.estimatedTickRate = int(.5 +
		(float64(app.estimatedTickRate*app.numRateEstimates+
			freezeTimeTickrate))/
			float64(app.numRateEstimates+1),
	)
	app.numRateEstimates++
}
```
at the end of every freezetime.
Here `app.freezeTime` is obtained via
```go
freezeTime, _ := strconv.ParseFloat(app.parser.GameState().ConVars()["mp_freezetime"], 32)
if freezeTime == 0 {
	Log("Cannot fetch mp_freezetime from cvars. Setting its value to 20.", Warning)
	freezeTime = 20
}
app.freezeTime = time.Duration(freezeTime) * time.Second
```
Yeah it is a bit hacky but it works.
