### ISSUE TITLE
Equipment.Class() returns wrong value

### ISSUE THREAD

**Issue by zyphie** [markus-wa/demoinfocs-golang#19]
Equipment.Class() currently:

`EquipmentClass(int(e.Weapon) / 100)`

This returns the wrong value (actual value - 1) as e.Weapon, or EquipmentElement, is rounded to the closest value.

E.g. glock has EquipmentElement value of 2. It should have an EquipmentClass of 1 (pistols), but the returned value is 0.

Naturally, as 2/100 = .02 ~ 0

Solution could be,
i) Add 100 to numerator:
`EquipmentClass(int(e.Weapon)+100 / 100)`
ii) Round to next integer:
`EquipmentClass(math.Ceil(int(e.Weapon) / 100))`

**Comment by markus-wa** [comment]
Hey @zyphie

I finally got around to this.

Please check if the fix on the `dev` branch works for you. If it does I will create a `v0.5.1` tag with the fix.

**Comment by markus-wa** [comment]
Oh and I went with the second solution as the first one doesn't account for `EqUnknown` and it's `EquipmentClass` both being 0

**Comment by zyphie** [comment]
It seems to work on the dev branch!

Thanks!
