### ISSUE TITLE
WeaponFiredEvent e.Weapon always default

### ISSUE THREAD

**Issue by viSual42** [markus-wa/demoinfocs-golang#20]
hi ;)
first of all very nice library! love it
have not done much in go and playing around with it at the moment
when i register on for example the WeaponFiredEvent the event variable Weapon as well as Player.ActiveWeapon is set to default Equipment ( if i'm correct its because they are both eventually coming from Parser.weapons)

dont know for sure but i think its because in 
[https://github.com/markus-wa/demoinfocs-golang/blob/4080117fb1ba6a5782e432cb2b82b594653410f5/datatables.go#L301](url)

>	eq := p.weapons[event.Entity.ID]

shouldnt it be 
> 	eq := &p.weapons[event.Entity.ID]

because you are filling eq with values afterwards but p.weapons never gets the value back

thank you
lukas

**Comment by markus-wa** [comment]
Hey @viSual42 

Thanks for the report!

Please check if the fix on the dev branch works for you. If it does I will create a `v0.5.1` tag with the fix.

**Comment by markus-wa** [comment]
Can you try it with the latest master version? Might be fixed with 44db23c.

**Comment by markus-wa** [comment]
If not, can you put a affected demo up for downloading somewhere?

**Comment by viSual42** [comment]
worked :D thx
just EqKnife needs a human readable string :)  but thats minor so for me its fixed ;)

**Comment by markus-wa** [comment]
Woops missed that one, here it is 2ea60f3

**Comment by markus-wa** [comment]
Note that we can't tell which kind of knife it is at the moment however even though the ingame killfeed would show that.

**Comment by viSual42** [comment]
no problem for me :)
