### ISSUE TITLE
another "no-panic" issue

### ISSUE THREAD

**Issue by BestAwperEver** [markus-wa/demoinfocs-golang#200]
I faced another debugging problem with new "no-panic" behaviour:
```go
var dummyInt int

p.RegisterEventHandler(func(e events.DataTablesParsed) {
	players := p.ServerClasses().FindByName("CCSPlayer")
	players.OnEntityCreated(func(playerEntity *st.Entity) {
		prop := playerEntity.FindPropertyI("m_bIsLookingAtWeapon")
		if prop != nil {
			prop.Bind(&dummyInt, st.ValTypeBoolInt)
		}
	})
})

err = p.ParseToEnd()
if err != nil {
	panic(err)
}
```

Since `dummyInt` is `int` and `st.ValTypeBoolInt` implies that it should be `bool`, we get this error at runtime with `v1.8.0` or newer:
```
panic: interface conversion: interface {} is *int, not *bool

goroutine 1 [running]:
main.main()
	C:/Users/admin/go/src/demoinfocs-test-cases/main.go:69 +0x1d5
```

where 69th line is, of cource, `panic(err)` so we cannot track down the issue exactly.

While with `v1.7.6` we got
```
panic: interface conversion: interface {} is *int, not *bool [recovered]
	panic: interface conversion: interface {} is *int, not *bool [recovered]
	panic: interface conversion: interface {} is *int, not *bool

goroutine 20 [running]:
github.com/markus-wa/godispatch.callConsumerCode.func1()
	C:/Users/admin/go/pkg/mod/github.com/markus-wa/godispatch@v1.2.1/dispatch.go:104 +0x8f
panic(0x874c60, 0xc000d8c3c0)
	C:/Program Files/Go/src/runtime/panic.go:522 +0x1c3
github.com/markus-wa/demoinfocs-golang.recoverFromUnexpectedEOF(...)
	C:/Users/admin/go/pkg/mod/github.com/markus-wa/demoinfocs-golang@v1.7.6/parsing.go:120
github.com/markus-wa/demoinfocs-golang.(*Parser).handlePacketEntities.func1(0xc000106000)
	C:/Users/admin/go/pkg/mod/github.com/markus-wa/demoinfocs-golang@v1.7.6/entities.go:14 +0x139
panic(0x874c60, 0xc000d8c3c0)
	C:/Program Files/Go/src/runtime/panic.go:522 +0x1c3
github.com/markus-wa/demoinfocs-golang/sendtables.(*Property).Bind.func2(0x0, 0x0, 0x0, 0x0, 0x0, 0x0, 0x0, 0x0, 0x0, 0x0)
	C:/Users/admin/go/pkg/mod/github.com/markus-wa/demoinfocs-golang@v1.7.6/sendtables/entity.go:372 +0x65
github.com/markus-wa/demoinfocs-golang/sendtables.(*Property).OnUpdate(...)
	C:/Users/admin/go/pkg/mod/github.com/markus-wa/demoinfocs-golang@v1.7.6/sendtables/entity.go:341
github.com/markus-wa/demoinfocs-golang/sendtables.(*Property).Bind(0xc000bf25e0, 0x83d580, 0xc00006e120, 0x6)
	C:/Users/admin/go/pkg/mod/github.com/markus-wa/demoinfocs-golang@v1.7.6/sendtables/entity.go:400 +0xb6
main.main.func1.1(0xc000058420)
	C:/Users/admin/go/src/demoinfocs-test-cases/main.go:62 +0x9e
github.com/markus-wa/demoinfocs-golang/sendtables.(*ServerClass).newEntity(0xc0004866e0, 0xc0003c8690, 0x1, 0x8800000000000000)
	C:/Users/admin/go/pkg/mod/github.com/markus-wa/demoinfocs-golang@v1.7.6/sendtables/sendtables.go:120 +0x2f5
github.com/markus-wa/demoinfocs-golang/sendtables.(*SendTableParser).ReadEnterPVS(0xc0000fc150, 0xc0003c8690, 0x1, 0xd59be0)
	C:/Users/admin/go/pkg/mod/github.com/markus-wa/demoinfocs-golang@v1.7.6/sendtables/st_parser.go:290 +0xcd
github.com/markus-wa/demoinfocs-golang.(*Parser).handlePacketEntities(0xc000106000, 0xc000888300)
	C:/Users/admin/go/pkg/mod/github.com/markus-wa/demoinfocs-golang@v1.7.6/entities.go:43 +0x26b
reflect.Value.call(0x84e0a0, 0xc0000644a0, 0x13, 0x8ea727, 0x4, 0xc000057f68, 0x1, 0x1, 0xc00008f470, 0x98afc0, ...)
	C:/Program Files/Go/src/reflect/value.go:447 +0x468
reflect.Value.Call(0x84e0a0, 0xc0000644a0, 0x13, 0xc000057f68, 0x1, 0x1, 0x6, 0xd38b20, 0xc000382000)
	C:/Program Files/Go/src/reflect/value.go:308 +0xab
github.com/markus-wa/godispatch.callConsumerCode(0x84e0a0, 0xc0000644a0, 0x13, 0xc000057f68, 0x1, 0x1)
	C:/Users/admin/go/pkg/mod/github.com/markus-wa/godispatch@v1.2.1/dispatch.go:107 +0x87
github.com/markus-wa/godispatch.(*Dispatcher).Dispatch(0xc000106020, 0x8d41e0, 0xc000888300)
	C:/Users/admin/go/pkg/mod/github.com/markus-wa/godispatch@v1.2.1/dispatch.go:93 +0x24e
github.com/markus-wa/godispatch.(*Dispatcher).dispatchQueue(0xc000106020, 0xc000058060)
	C:/Users/admin/go/pkg/mod/github.com/markus-wa/godispatch@v1.2.1/dispatch.go:155 +0xfc
created by github.com/markus-wa/godispatch.(*Dispatcher).AddQueues
	C:/Users/admin/go/pkg/mod/github.com/markus-wa/godispatch@v1.2.1/dispatch.go:141 +0x158
```

which is much more informative 😃

**Comment by markus-wa** [comment]
hmm that's rather surprising after the recent fix... will have to check what's up with that.

**Comment by markus-wa** [comment]
I guess that no-panic fun is over ...
Unfortunately we use `Entity.OnUpdate()` for both internal and external code, so we can't detect where the panic is coming from.

this means we'll be panicking again for *everything*, no more turning internal panics into errors.

**Comment by BestAwperEver** [comment]
Hey maybe that's not that bad. This panic-behaviour helped us to find and fix several problems in past 🙂

**Comment by markus-wa** [comment]
v1.10.0 is out with a fix.

> Hey maybe that's not that bad. This panic-behaviour helped us to find and fix several problems in past 

maybe so :slightly_smiling_face:

**Comment by markus-wa** [comment]
I went back and re-visited this topic.

We'll now return an `error` in case of a  `panic` in a sub-routine.
The error will include the whole stack trace.

This change is critical to preventing a long running application from shutting down when a corrupt demo is being parsed.
For instance in case of a web-server this will make sure the server doesn't crash due to someone uploading a POV demo that can't be parsed.

Hope this isn't causing any further debugging struggles.

**Comment by BestAwperEver** [comment]
Sounds reasonable, thanks for informing 🙂

Although in our case we just don't allow users to upload custom demo files as it might be dangerous -- for example, a user-uploaded demo may contain unapropriate amount of ticks and just load our worker potentially forever. This actually happened once with one of the pro teams trying to analyze their non-official match -- they just forgot to stop recording the demo after the match and we ended up with a demo with 20 million ticks or so 😃 Not that this has anything to do with your change, just an anecdote from our work

**Comment by markus-wa** [comment]
> a user-uploaded demo may contain unapropriate amount of ticks and just load our worker potentially forever

In a case like this I would suggest setting a timeout for the parsing and if `ParseToEnd() hasn't finished in x seconds calling `Parser.Cancel()`

But yeah if you don't need for your case it then even better 😄

**Comment by BestAwperEver** [comment]
Thanks for the suggestion, I actually see this method for the first time despite working with your library for almos over a year now 😃 I might as well set the timeout for about a 2M ticks just in case, even if we won't be parsing any custom demos. Who knows, may be there are matches from HLTV (which we allow our users to upload) which also have problems similar to the one I described.
