### ISSUE TITLE
Ability to use this library from other programming languages

### ISSUE THREAD

**Issue by d4rwel** [markus-wa/demoinfocs-golang#202]
I want to be able to call some of the library functions from another language, like C or Java.

More precisely, I want to use a player's position (X-,Y- and Z-coordinates) and their view angle (X- and Y-coordinates) from a replay parsed by this library in a Java/C project. 

An alternative way to get these informations would be using the output of [cs-demo-minifier](https://github.com/markus-wa/cs-demo-minifier), which in turn uses this library. In fact, this would suffice my needs. But the output doesn't provide the Y-coordinate for the view angle (see [this issue](https://github.com/markus-wa/cs-demo-minifier/issues/24)) And maybe it turns out, that I need some more information, which isn't provided in the output. Hence, direct access to the library provides more control over selected information.

[This article](https://medium.com/learning-the-go-programming-language/calling-go-functions-from-other-languages-4c7d8bcc69bf) describes how to compile Go packages into C shared libraries. Unfortunately I have no experience with the Go programming language, so I can't foresee any pitfalls or if this is implementable in this specific library at all.

I hope there is more demand for such a feature, so an implementation would be worthwile.

**Comment by d4rwel** [comment]
I've implemented a working prototype for this enhancement: 

https://github.com/d4rwel/demoinfocs-golang/tree/c-bindings/api/cbinds

Testing is not yet implemented as I haven't reasoned enough about how to approach it.

**Comment by markus-wa** [comment]
I think going forward this will be a non-goal and should be done in a separate project maintained by the community as the maintenance burden would be too great for this project.
