### ISSUE TITLE
Installation on Ubuntu 18.04

### ISSUE THREAD

**Issue by pnxenopoulos** [markus-wa/demoinfocs-golang#209]
I'm trying to install v2 on a fresh installation of Ubuntu 18.04

After I run `go get -u github.com/markus-wa/demoinfocs-golang/v2/pkg/demoinfocs`, I get the following error:

```
package github.com/markus-wa/demoinfocs-golang/v2/pkg/demoinfocs: cannot find package "github.com/markus-wa/demoinfocs-golang/v2/pkg/demoinfocs" in any of:
	/usr/local/go/src/github.com/markus-wa/demoinfocs-golang/v2/pkg/demoinfocs (from $GOROOT)
	/home/peter/go/src/github.com/markus-wa/demoinfocs-golang/v2/pkg/demoinfocs (from $GOPATH)
```

I'm using Go 1.14.3, any ideas on what may be happening? I'm rather new to using Go, particularly with regards to package management.

**Comment by markus-wa** [comment]
Hi @pnxenopoulos !

You will first need to create a Go Modules project (_outside_ of `GOPATH`!).

```
mkdir my-project
cd my-project
go mod init github.com/<YOUR_GITHUB_USER>/my-project
go get github.com/markus-wa/demoinfocs-golang/v2
```

I should probably add this to the README 😅

**Comment by pnxenopoulos** [comment]
Great, that did it! thank you.
