### ISSUE TITLE
Suggestion: Use updatable source for protobuf

### ISSUE THREAD

**Issue by TihonV** [markus-wa/demoinfocs-golang#215]
Hi, Markus! Can you use the relevant protobuf description?

It can be extracted from the "CS:GO" folder or you can found it [here](https://github.com/SteamDatabase/GameTracking-CSGO).

**Comment by markus-wa** [comment]
Unfortunately with the way Go works we can't automatically generate the latest version (has to do with `go get` amongst other things). Every time there is a change it needs to be manually adjusted.

But I should probably write a bot that creates a pull request every time upstream protos change 😅.

Anyway, I will update the protos later today and will pop out a new release.

**Comment by markus-wa** [comment]
fixed with #220 and #221 - protobufs are now up to date.

**Comment by markus-wa** [comment]
released with `v2.2.0`
