### ISSUE TITLE
Memory leak when using ParseHeader() or ParseNextFrame() without ParseToEnd()

### ISSUE THREAD

**Issue by markus-wa** [markus-wa/demoinfocs-golang#216]
**Describe the bug**
When `ParseHeader()` or `ParseNextFrame()` is called without `ParseToEnd()`, there is a memory leak causing the runtime to crash

**To Reproduce**
Code:
```go
package main
 
import (
    "bytes"
    "io/ioutil"
    "os"
 
    "github.com/markus-wa/demoinfocs-golang/v2/pkg/demoinfocs"
)
 
func main() {
 
    for {
        func() {
            demoFile, err := os.Open("match.dem")
            if err != nil {
                panic(err)
            }
            defer func() {
                if err := demoFile.Close(); err != nil {
                    panic(err)
                }
            }()

            demoData := demoinfocs.NewParser(demoFile)
 
            if _, err = demoData.ParseHeader(); err != nil {
                panic(err)
            }
        }()
    }
}
```

**Expected behavior**
No memory leak

**Library version**
v2.1.0

**Comment by BestAwperEver** [comment]
Hi @markus-wa, I'm still at v.1.10.0, should I tweak the code somehow or it is affecting only v2 branch?

**Comment by markus-wa** [comment]
@BestAwperEver - it's also affecting v1.x.

good shout on that, this should probably be backported to v1.

**Comment by markus-wa** [comment]
backport PR https://github.com/markus-wa/demoinfocs-golang/pull/224

**Comment by BestAwperEver** [comment]
Thanks!

**Comment by markus-wa** [comment]
v1.11.0 is out with the fix: https://github.com/markus-wa/demoinfocs-golang/releases/tag/v1.11.0
