### ISSUE TITLE
Go get fails to install

### ISSUE THREAD

**Issue by pinpox** [markus-wa/demoinfocs-golang#230]
**Describe the bug**
Go get failes to get the package

**To Reproduce**

`go get -u github.com/markus-wa/demoinfocs-golang/v2/pkg/demoinfocs`

**Expected behavior**
Installation

**Library version**
latest/any

**Additional context**
The installation instructions in the README don't seem to work correctly. I get this output:
```
✱ go get -u github.com/markus-wa/demoinfocs-golang/v2/pkg/demoinfocs

package github.com/markus-wa/demoinfocs-golang/v2/pkg/demoinfocs: cannot find package "github.com/markus-wa/demoinfocs-golang/v2/pkg/demoinfocs" in any of:
	/usr/lib/go/src/github.com/markus-wa/demoinfocs-golang/v2/pkg/demoinfocs (from $GOROOT)
	/home/pablo/.go/src/github.com/markus-wa/demoinfocs-golang/v2/pkg/demoinfocs (from $GOPATH)

~
```

**Comment by markus-wa** [comment]
Hi @pinpox , please refer to this section: https://github.com/markus-wa/demoinfocs-golang/blob/master/README.md#getting-started

It sounds like you tried to run `go get` outside of a Go Module directory.

**Comment by Z-a-r-a-k-i** [comment]
Looks like you forgot to do the go mod init part in your project folder

**Comment by markus-wa** [comment]
closing this and assuming it works now :slightly_smiling_face: - let me know if that isn't the case.
