### ISSUE TITLE
Missing round data with bug fix in v2

### ISSUE THREAD

**Issue by JohnRubado** [markus-wa/demoinfocs-golang#231]
**Describe the bug**
Missing round data with most recent fix for this issue

```
Error: Command failed: cd ./goParser && go run parse_1.go -demo C:\Work\demos\003424787573002731678_1597490921.dem 76561198180280426
panic: runtime error: invalid memory address or nil pointer dereference [recovered]
        panic: runtime error: invalid memory address or nil pointer dereference [recovered]
        panic: runtime error: invalid memory address or nil pointer dereference
[signal 0xc0000005 code=0x0 addr=0x10 pc=0x7eed10]
```
**To Reproduce**
Parse any gotv demo with most recent release of v2, and there is a chance you will miss lots of round data later in the demo.

**Expected behavior**
Parse a demo with roundStart and roundEnd events, p.GameState().TotalRoundsPlayed() often misses many rounds

**Library version**
 v2.3.0

**Additional context**
I had originally prevented the parser in v1 from crashing due to the error above by changing this code in dispatch.go
```
func callConsumerCode(h reflect.Value, args []reflect.Value) {
	defer func() {
		r := recover()
		if r == nil {
			return
		}

		panic(consumerCodePanic{value: r})
	}()

	h.Call(args)
}
```
to
```
func callConsumerCode(h reflect.Value, args []reflect.Value) {
	defer func() {
			recover()
	}()
	defer func() {
		r := recover()
		if r == nil {
			return
		}

		panic(consumerCodePanic{value: r})
	}()

	h.Call(args)
}
```

I am aware that this swallows any kind of error, but for my purposes it has always returned all the data for me and never caused any issues so far, and the most recent fix in v2 for the error above has lead to missing data in my demos. I added the dispatch.go edit to v2 and am now getting all round data returned.

**Comment by markus-wa** [comment]
can you provide a demo and code? this does not reproduce for me.

**Comment by JohnRubado** [comment]
I am going to figure out exactly which chunk of code is causing it and I will update you. I trimmed down my code to be only RoundStart and RoundEnd events. This got rid of the issue without having to use an edit on dispatch.go

**Comment by JohnRubado** [comment]
The error is in the kill event handler. Referencing
```
e.Killer.SteamID64
```
seems to randomly cause the issue. If I comment out the lines inside kill event handler, I get all rounds. I will provide the associated demo when it is done uploading to dropbox.
```
package main

import (
	"fmt"
	"os"
	"github.com/markus-wa/demoinfocs-golang/v2/pkg/demoinfocs/msg"
	"github.com/gogo/protobuf/proto"
	dem "github.com/markus-wa/demoinfocs-golang/v2/pkg/demoinfocs"
	ex "github.com/markus-wa/demoinfocs-golang/v2/examples"
	events "github.com/markus-wa/demoinfocs-golang/v2/pkg/demoinfocs/events"
)

func main() {

	f, err := os.Open(ex.DemoPathFromArgs())
	checkError(err)

	defer f.Close()
	defer func(){
		if r := recover(); r != nil{
			fmt.Println("Recovered in main: ", r)
		}
	}()

	p := dem.NewParserWithConfig(f, dem.ParserConfig{
		MsgQueueBufferSize: 250000,
		AdditionalNetMessageCreators: map[int]dem.NetMessageCreator{
			4: func() proto.Message { return new(msg.CNETMsg_Tick) },
		},
	})

	
	defer p.Close()

	p.RegisterEventHandler(func(e events.RoundStart){
		fmt.Println(p.GameState().TotalRoundsPlayed())
	}) 

	p.RegisterEventHandler(func(e events.Kill){
	          var steamid uint64 = e.Killer.SteamID64
	          useid(steamid)
	})

	p.ParseToEnd()
}

func checkError(err error) {
	if err != nil {
		panic(err)
	}
}

func useid(id uint64){
	if id == 1{
		fmt.Println("placeholder")
	}
}

```

**Comment by JohnRubado** [comment]
How I run it when it is named parse.go
```
go run parse.go -demo ./003425619158128132230_1704969837.dem
```
Test demo file
https://www.dropbox.com/s/99w634cwi9hvu48/003425619158128132230_1704969837.zip?dl=0

**Comment by markus-wa** [comment]
This doesn't seem to be related to v2, it also happens with v1.

Looking at the [docs](https://pkg.go.dev/github.com/markus-wa/demoinfocs-golang/v2@v2.3.0/pkg/demoinfocs/events?tab=doc#Kill), `Kill.Killer` and `Kill.Victim` may be nil so you need to add a nil check to your code.

so:

```go
p.RegisterEventHandler(func(e events.Kill) {
	if e.Killer != nil { // IMPORTANT
		var steamid uint64 = e.Killer.SteamID64
		useid(steamid)
	}
})
```

this works for me:
```
=== RUN   TestIssue231
0
1
2
3
4
5
6
7
8
9
10
11
12
13
14
15
16
17
18
19
20
21
22
23
24
25
26
27
--- PASS: TestIssue231 (1.06s)
PASS

Process finished with exit code 0
```

**Comment by markus-wa** [comment]
this happened at tick `12478` (and also twice later on). looking at the demo, this was a bomb kill (=no killer).

**Comment by JohnRubado** [comment]
Thanks a ton for your help. Thats what I get for swallowing any error! Learned my lesson

**Comment by markus-wa** [comment]
no worries :smile: glad I could help!
