### ISSUE TITLE
Question about frame / tick / tickrate

### ISSUE THREAD

**Issue by Purple-CSGO** [markus-wa/demoinfocs-golang#232]
The struct `Kill` does not have member like `tick`, so how to know when/which tick this frag happens?

It seems this project use frame to describe time?? but how to get the tickrate of a demo? since it's not always the same and people don't want to manually judge it.

I'm working on a demo tool so I want the exact tick of certain event. Thx a lot for this repo btw. GJ!

**Comment by markus-wa** [comment]
Hey @Purple-CSGO 

The current tick is returned by `Parser.GameState().IngameTick()`.

The tick rate is `Parser.TickRate()`

**Comment by markus-wa** [comment]
See https://pkg.go.dev/github.com/markus-wa/demoinfocs-golang/v2/pkg/demoinfocs?tab=doc

**Comment by markus-wa** [comment]
closing this as I assume this answered the question. let me know if there's anything else I can help with :slightly_smiling_face:
