### ISSUE TITLE
Get client eye position

### ISSUE THREAD

**Issue by 87andrewh** [markus-wa/demoinfocs-golang#236]
**Higher goal**
I would like an Entity.EyePosition() function that accurately returns player eyes' Z coordinates, even when jumping or in the middle of the duck or un-duck animation.
I suspect that IsDucking() is not accurate enough for my purposes.

**Describe the solution you'd like**
In SourceMod, I use GetClientEyePosition(), which is accurate. I also think cl_showpos returns an accurate location.

**Describe alternatives you've considered**
None.

**Additional context**
I don't need the position to be extremely accurate in the XY plane, as I don't think there is a simple native way to access precise eye locations for both CT and T models in all animations. But an accurate Z should be obtainable.

**Comment by markus-wa** [comment]
Would be a nice feature.

Here's some notes, either for my future self or whoever want's to implement it.

SM's `GetClientEyePosition()` seems to be based on `CServerGameClients->ClientEarPosition`:
- https://github.com/alliedmodders/sourcemod/blob/4bebdc18a2e4820b234a85c3a1e38eb868a84bf2/extensions/sdktools/vnatives.cpp#L696-L718
- https://github.com/ValveSoftware/source-sdk-2013/blob/master/sp/src/game/server/gameinterface.cpp#L3089-L3102
- https://sourcegraph.com/github.com/ValveSoftware/source-sdk-2013@0d8dceea4310fde5706b3ce1c70609d72a38efdf/-/blob/mp/src/game/shared/baseentity_shared.cpp#L132-136
- https://sourcegraph.com/github.com/ValveSoftware/source-sdk-2013@0d8dcee/-/blob/mp/src/game/client/c_baseentity.cpp#L1707-1712
- https://sourcegraph.com/github.com/ValveSoftware/source-sdk-2013@0d8dceea4310fde5706b3ce1c70609d72a38efdf/-/blob/mp/src/game/client/c_baseentity.cpp#L4317-4394
- https://sourcegraph.com/github.com/ValveSoftware/source-sdk-2013@0d8dceea4310fde5706b3ce1c70609d72a38efdf/-/blob/mp/src/game/shared/baseentity_shared.cpp#L158-161

so it looks like it's
`C_BaseEntity::CalcAbsolutePosition() + localdata.m_vecViewOffset`

not sure if this bit here is needed or not:  https://github.com/alliedmodders/sourcemod/blob/4bebdc18a2e4820b234a85c3a1e38eb868a84bf2/extensions/sdktools/vnatives.cpp#L711-L715

**Comment by 87andrewh** [comment]
The highlighted part just writes the position by reference. Without it, GetClientEyePosition() would do nothing.

**Comment by markus-wa** [comment]
It also seems to do some translation with `LocalToPhysAddr()` (and `sp_ftoc`?) Which I didn't look into yet.

**Comment by 87andrewh** [comment]
Oh yeah, SourcePawn is weird.
All types are converted to and passed as cell_t, which is int32.
sp_ftoc() encodes floats as cell_t.
pContext->LocalToPhysAddr(params[2], &addr) links params[2] to &addr, allowing you to edit params[2] through addr, which is the way that information is passed back to the caller.

For some context, a SourcePawn script calls GetClientEyePosition(), which is C++ code. GetClientEyePosition() returns information to the the SourcePawn script by editing the params by reference.

**Comment by markus-wa** [comment]
Ahh makes sense, cheers for the explanation!

**Comment by billfreeman44** [comment]
Maybe this helps? https://github.com/saul/demofile/discussions/290

**Comment by markus-wa** [comment]
Interesting thread @billfreeman44 

I think what we should probably do as a quick win is expose something like `EyeHeight()`.
Then let users do the calc manually.

Calling into source code is probably out of scope for this project.

I guess in the meantime people can just use good old `Player.Entity.PropertyValueMust(....`

**Comment by markus-wa** [comment]
or we actually may get away with `PositionEyes()` and just `Position() + m_vecViewOffset[2]`

**Comment by markus-wa** [comment]
finally got around to this (really should have done so sooner considering how easy it turned out to be)

we now have `Player.PositionEyes()`

:partying_face:
