### ISSUE TITLE
Get unique demo file identifier and time

### ISSUE THREAD

**Issue by pinpox** [markus-wa/demoinfocs-golang#239]
Is it possible to get an unique identifier of a demo file and the time it was recorded?

I'm trying to check if a certain demo file has already been parsed for a app I build that let's users upload demo files.

**Comment by markus-wa** [comment]
for the unique identifier I'd recommend just MD5 hashing the file.
the time of the demo is not stored unfortunately, but maybe if you read through #127 or #137 you'll find something that's useful for whatever you're trying to do (`CSVCMsg_ServerInfo.MapCrc` or [`node-csgo`](https://github.com/joshuaferrara/node-csgo))

hope that helps

**Comment by Julien2313** [comment]
It is stored in the .info file. If you have the [sharecode ](https://developer.valvesoftware.com/wiki/Counter-Strike:_Global_Offensive_Access_Match_History), if you [convert it](https://gitlab.com/Julien2313/csgo-demos-analyzer/-/blob/develop/backend/workers/downloaderinfo/downloaderinfo.go#L197), you will be able to use [boiler](https://github.com/akiver/boiler-writter) to download the .info of the demo. Then, using [protobuf](https://gitlab.com/Julien2313/csgo-demos-analyzer/-/blob/develop/backend/model/demoInfo.proto), extract time and ID (protobuf aren't the same if you download the .info from the game or from boiler #geniusValve

**Comment by pinpox** [comment]
@Julien2313 That sound good, thanks! The problem for me here is that I don't have the share link at the moment. I just load the demo files into a webapp I'm building. Is it possible to download the file just by link from the app itself (along with the .info file)?
In that case, I would refactor my application to take the sharecodes as input instead of the demo files, which also would make the "import" process easier for the user.

**Comment by Julien2313** [comment]
`Is it possible to download the file just by link from the app itself` what app are you talking about ?

Not sure if I answer your question, but I didn't find a way, from the .dem, to retrieve the .info. At the moment, I'm asking users to provide their steamID, current sharecode and a key, so I can use the valve's API to download .info, and inside, their is a link for the .dem available 1 month.

**Comment by pinpox** [comment]
> `Is it possible to download the file just by link from the app itself` what app are you talking about ?
Sorry if I was unclear, I meant the app I'm building. 

Asking the user to enter a `steamID`, a `sharecode` and a `key` sounds like a lot of work for the end-user. So there is no easy way to get all information about a match? If so, I'll use the time when the .dem was uploaded to my app as time when the match took place, should be good enough.

If the user enters *only* a sharecode, would it be possible to get the demo file for me?

**Comment by Julien2313** [comment]
> Asking the user to enter a steamID, a sharecode and a key sounds like a lot of work for the end-user.

It's only one time, then you'll be able to get every new match from the API.

> So there is no easy way to get all information about a match?

From my researchs, if you only have .dem, you won't find the ID or the time.

> If the user enters only a sharecode, would it be possible to get the demo file for me?

Mmmh, I guess it's enough, as a shace code is unique for a game, and the same for the 10 players IG. You'll need to get from it the .info and then the .dem

**Comment by markus-wa** [comment]
Thanks for jumping in here @Julien2313 - +1 on all that, I haven't found another way to et the match ID or time either :disappointed: 

Didn't actually know it was all in the `.info` file, so good to know that!

**Comment by Julien2313** [comment]
So strange they didn't put it in the .dem... I can't understand why ?

**Comment by pinpox** [comment]
> It's only one time, then you'll be able to get every new match from the API.

If I have multiple user that participated in the same match, will the ID of the match be the same for both? 

I would like to avoid duplication of matches if multiple if my users played together. My current approach is to manually upload dem files, but it would be great to automate the downloading process

**Comment by Julien2313** [comment]
> If I have multiple user that participated in the same match, will the ID of the match be the same for both?

Yes

> Also, if I just md5 the dem, will the hash be the same for two Dems of the same match downloaded by two different players/accounts?

> I would like to avoid duplication of matches if multiple if my users played together. My current approach is to manually upload dem files, but it would be great to automate the downloading process

Don't hesitate to check my project on GitLab, I have a Go routine that checks every hours if users have played a new game, if yes, I download the .info from boiler, I store in my DB the unique ID (so, even if the 10 players are connected, I won't be able to register more than 1 entry in my DB) and then send the order to another Go routine to download the .dem.

I don't know, I work if the ID :/ But for me, I guess yes as I download from an URL I think not linked to an user. But, if you download it from the game, idk, but certainly yes ?

You might want to dev your project alone, that's up to you, but with your questions, I think you want to do the same things (analyze demos for users that are register in a website, and give them stats). If yes, my project is open source ;) ha ha

**Comment by pinpox** [comment]
> Don't hesitate to check my project on GitLab, I have a Go routine that checks every hours if users have played a new game, if yes, I download the .info from boiler, I store in my DB the unique ID (so, even if the 10 players are connected, I won't be able to register more than 1 entry in my DB) and then send the order to another Go routine to download the .dem.

Thanks for the link, I have looked at (and bookmarked ;) ) your project! In case you want to take a look, the app I'm building is over here: https://github.com/megaclan3000/megaclan3000 The demo-parsing functionality is not in the master branch yet, it's in the branch `parse-demo` for now. I'm not sure I can use/integrate your analyzer directly, but I will take a few of the methods I think. For the demo-parsing part all I need is to get the demos of a list of steamIDs and parse them into this [struct](https://github.com/megaclan3000/megaclan3000/blob/080570ce911fa82b78660501c3569a5e75cae453/internal/demoparser/match.go#L16)

The WebUI showing fancy statistics is mostly done, I'm now working on downloading the files. Another question I'm debating over is in what database I could save and use those structs. For now I think I'll go with mongoDB and marshal `InfoStruct` into JSON, but maybe there is a better way.

@Julien2313 @markus-wa Thanks for the help and the great parsing library! I'll keep this issue updated for future reference when I have a working solution.
<details>
  <summary>Some Screenshots</summary>

![image](https://user-images.githubusercontent.com/1719781/93016538-40edac80-f5c2-11ea-9fdb-85590c610190.png)
![image](https://user-images.githubusercontent.com/1719781/93016560-76929580-f5c2-11ea-8a0a-cb4c690ca63f.png)
![image](https://user-images.githubusercontent.com/1719781/93016566-85794800-f5c2-11ea-9df6-404c72ca3cf5.png)
![image](https://user-images.githubusercontent.com/1719781/93016576-97f38180-f5c2-11ea-8c7c-fe893ca9d75c.png)

</details>

**Comment by markus-wa** [comment]
@pinpox 
> Also, if I just md5 the dem, will the hash be the same for two Dems of the same match downloaded by two different players/accounts?

should be the same, though I haven't tested this. if you've recently played with someone you know you could ask them to download the demo and sen it to you, then compare hashes with your download. (bit cumbersome but hey, it works).

also let me know when you've implemented some parsing stuff in megaclan3000 - it looks really cool!

**Comment by Julien2313** [comment]
Ooooh, niiice WebUI ! I'm a very bad front end developer, so mine is really... bad :( 

https://csgofacts.com/

I really like the way you choose to show duels !

**Comment by pinpox** [comment]
> It is stored in the .info file.
> 
> One way to di it : If you have the [sharecode ](https://developer.valvesoftware.com/wiki/Counter-Strike:_Global_Offensive_Access_Match_History), if you [convert it](https://gitlab.com/Julien2313/csgo-demos-analyzer/-/blob/develop/backend/workers/downloaderinfo/downloaderinfo.go#L197), you will be able to use [boiler](https://github.com/akiver/boiler-writter) to download the .info of the demo. Then, using [protobuf](https://gitlab.com/Julien2313/csgo-demos-analyzer/-/blob/develop/backend/model/demoInfo.proto), extract time and ID (protobuf aren't the same if you download the .info from the game or from boiler #geniusValve
@Julien2313 Did you remove the code? I was trying to look up how to download matches from the key, but the link is dead

**Comment by Julien2313** [comment]
Oops, I was testing gitlab settings, forgot to reset de visibility xD

**Comment by pinpox** [comment]
I'm trying to understand what boiler does exactly, I would like to not have to call an external binary. It probably just converts the matchID to some link?

**Comment by Julien2313** [comment]
> I'm trying to understand what boiler does exactly, I would like to not have to call an external binary. It probably just converts the matchID to some link?

From my researches, no...
I'm ehre too !

**Comment by pinpox** [comment]
@markus-wa just wanted to say thanks for the great parser before closing this issue. I decided to go with hashing the file as ID for now, since I wanted to deploy my app and need a quick and easy way to identify matches.

The app is live at https://megaclan3000.de/ , the "Matches" page makes heavy use of your library to get the needed data and save them to a postgreSQL database in the format I need for displaying it. 

The app is completely open-source even thought it's very tailored to my group of players. Code is available at https://github.com/megaclan3000/megaclan3000 in case you want to list it as example or anyone wants to know how it's build under the hood.

**Comment by markus-wa** [comment]
thanks @pinpox - added the repo to the readme :slightly_smiling_face:
