### ISSUE TITLE
IsDucking() seems incorrect

### ISSUE THREAD

**Issue by 87andrewh** [markus-wa/demoinfocs-golang#241]
**Describe the bug**
After examining a demo, IsDucking() seems to not be true when a player is ducked.
Instead, it is true for several frames proceeding the actual duck.

**To Reproduce**

[duck_bug.zip](https://github.com/markus-wa/demoinfocs-golang/files/5213380/duck_bug.zip)

**Expected behavior**
IsDucking() should be true when the player is actually in the ducking state.

**Library version**
I think v1.11.0

**Additional context**
Some digging:
https://forums.alliedmods.net/archive/index.php/t-60764.html
https://github.com/alliedmodders/sourcemod/blob/dea3ef70a2ce94e1cb86e0283c8e3babf7ab98ef/core/smn_entities.cpp#L2558
https://github.com/alliedmodders/sourcemod/blob/81dc80fbd14b7eba3c20bc22a60629fc874015de/plugins/include/entity_prop_stocks.inc#L131

**Comment by markus-wa** [comment]
Thanks for the report @87andrewh , I think this would be a good candidate for a PR contribution (maybe even hacktoberfest in two weeks? though fixing it sooner would be nice as well)

> Library version
> I think v1.11.0

How come you're not on v2.x ? - not that this would fix it but still.
