### ISSUE TITLE
PlayerHurt.HealthDamage could be improved

### ISSUE THREAD

**Issue by Julien2313** [markus-wa/demoinfocs-golang#244]
**Higher goal**
`PlayerHurt.HealthDamage` returns the theoretical damages given, not the reals ones.

**Describe the solution you'd like**
Having a new fields with the real value. In example, if a AWP kill someone with HS with 15HP left, I'd like `PlayerHurt.HealthDamage` to returns 15, not 450

**Describe alternatives you've considered**
At the moment I get the real value by getting all the participants, find the victim, and if `PlayerHurt.Health == 0` I change my value of damage by the current health of the player (hopefully, this is never updated before the event)

**Comment by Julien2313** [comment]
If you accept this update, I'd be glade to do it

**Comment by markus-wa** [comment]
I think this would be reasonable enough to add if named and documented accordingly yeah. Bht I would like to better understand why you need this - mostly out of curiosity.

If you'd like to make a PR that'd be cool

**Comment by Julien2313** [comment]
What bht means ? xD

I'm giving "impacts points" for players during a game. One of the way to get points is to deal damage. That's why I need to "real" value :D

**Comment by markus-wa** [comment]
Bht is just a typo. Was supposed to be "but" 😄. And yeah that usecase makes sense, thanks for explaining

**Comment by markus-wa** [comment]
closing as #247 implemented this, thanks for the contribution!
