### ISSUE TITLE
Where did you get the image used to make the heat map?

### ISSUE THREAD

**Issue by Murilobdo** [markus-wa/demoinfocs-golang#245]
I am in doubt about the size of the image, I already have the points calculated according to your example but I am not finding a correct size image to make the heat map

**Comment by markus-wa** [comment]
I see you closed the issue, not sure if that was an accident or if you found the images.

anyway, if you look at that [example](https://github.com/markus-wa/demoinfocs-golang/blob/master/examples/heatmap/heatmap.go#L82) you will find the map is located in [`assets/maps`](https://github.com/markus-wa/demoinfocs-golang/tree/master/assets/maps) (courtesy of [@zoidbergwill/csgo-overviews]( https://github.com/zoidbergwill/csgo-overviews)).
and the corresponding [translations](https://github.com/markus-wa/demoinfocs-golang/blob/master/examples/heatmap/heatmap.go#L50) can be found in the [`metadata`](https://pkg.go.dev/github.com/markus-wa/demoinfocs-golang/v2@v2.3.0/pkg/demoinfocs/metadata) package (might be out of date, if so feel free to open a PR)
