### ISSUE TITLE
add a field "color" in common.Player

### ISSUE THREAD

**Issue by Julien2313** [markus-wa/demoinfocs-golang#248]
**Higher goal**
I'd like to have the current color of the player in the game. When I play with friends, we are used to use always the same color, and this kind of graph would be easier to read (or colors in a map)
![image](https://user-images.githubusercontent.com/8778771/98441390-3a7d3c00-20fe-11eb-9cab-d11fd55c9ec3.png)

**Describe the solution you'd like**
Adding a field "color" in common.Player

**Additional context**
I have no idea if this information is stored in the demo, but I don't know how to check if it is or not.
Once again, I'd be glade to do it (but I'd need you to explain me a little bit how to find this information and catch it, if it exists).

**Comment by markus-wa** [comment]
hey, you can check if it's in the demo by looking at the replay in CS:GO and making sure that player colors match the ones you actually had during the game.

If it's in there it will probably be on one of these two entities:
- CCSPlayer
- CCSPlayerResource

then you can investigate the available properties (see https://github.com/markus-wa/demoinfocs-golang/wiki/Server-Classes)

`CCSPlayerResource.m_iCompTeammateColor.000` - `CCSPlayerResource.m_iCompTeammateColor.064` looks like a good place to start (i just searched for "color" in that list and looked for anything that might fit). if it's indeed this property, you would do something like [this](https://github.com/markus-wa/demoinfocs-golang/blob/master/pkg/demoinfocs/common/player.go#L312)

hope that helps

**Comment by Julien2313** [comment]
> hey, you can check if it's in the demo by looking at the replay in CS:GO and making sure that player colors match the ones you actually had during the game.

I tried it, but when I replay a demo, there are no colors

Thanks for the help, I'll try it this evening
