### ISSUE TITLE
Add a new event "partyID"/field in common.Player "partyID"

### ISSUE THREAD

**Issue by Julien2313** [markus-wa/demoinfocs-golang#251]
> – End of match scoreboard will now display which players were playing as a party when skill groups are revealed.
https://blog.counter-strike.net/index.php/2020/08/31374/

**Higher goal**
I'd like to be able to display which player were playing together.

**Describe the solution you'd like**
Idk how it's implemented in the demo, but for the parser, an ID of a party, 0 if there is none would be great. All the players with the same ID started the game together. Could be in the new event, called at the same time as Ranks.

For older demos, this information will be missing, so every ID will be 0.

I'm looking in the demo properties (with a new one, as this is a new feature), but didn't find anything for now.

**Comment by markus-wa** [comment]
have you tried running this command on the demo? the current property list might be incomplete for new demos:

    go run -tags debugdemoinfocs -ldflags '-X github.com/markus-wa/demoinfocs-golang/v2/pkg/demoinfocs.debugServerClasses=YES' examples/print-events/print_events.go -demo test/cs-demos/default.dem

**Comment by Julien2313** [comment]
Yes, I've done it. I didn't find (for now) anything like "party" "together" etc

**Comment by markus-wa** [comment]
I can give it a go as well if you like (no promises that I can fin anything though :smile:). can you send me a demo that has this feature?

**Comment by Julien2313** [comment]
This one should have it : http://replay195.valve.net/730/003446389375158452407_0725340149.dem.bz2

**Comment by markus-wa** [comment]
Hi @Julien2313 - sorry for the late reply here.

Looking at that demo (I downloaded it before it expired) or any other demo, I can't see any evidence of this feature being included in demos (scoreboard never shows any links between players).

I also checked `UserMessage` 81 (`CS_UM_DeepStats`) which would contain a field called `mates` - but this message was never dispatched during that demo.

Therefore I will assume that this is not stored in demos and only available during the live game. If anyone can find evidence of this data in demos I'm happy to re-open.

**Comment by Julien2313** [comment]
Hello @markus-wa :)
I just checked other websites, and in example, they are providing it here :
https://csgo-stats.com/match/CSGO-kGW3u-UF8Rx-X3XLW-UqzR7-dLaxJ

I'll check further. Maybe in the .demo.info ?

**Comment by markus-wa** [comment]
Ah vool, thanks for that link. I've reopened this then. Really makes me wonder where that data is coming from 🤔

**Comment by markus-wa** [comment]
I guess in theory they could be looking at steam friends which isn't the same thing, but would give the same reault 90% of the time.

**Comment by saul** [comment]
I did a bit of digging as part of a similar request for my NodeJS demo parsing library: https://github.com/saul/demofile/issues/196#issuecomment-757469550

**Comment by markus-wa** [comment]
Ah, interesting, thanks @saul :pray: !
I'll follow in your footsteps then and close this as well unless anything new comes up :slightly_smiling_face: 

@Julien2313  - I remember there was some talk around usage of node-csgo in #127 if you're interested.

**Comment by Julien2313** [comment]
Ok alright, so if it's from the sharecode, it could be in the .dem.info :)
Anyway, I'm already using boiler-writter, so I'll give it a look

Thank you @saul and @markus-wa
