### ISSUE TITLE
Possibility to get the round time

### ISSUE THREAD

**Issue by pbuzulan** [markus-wa/demoinfocs-golang#256]
**Higher goal**
There is no function implemented that can extract the round time from a demo.

**Describe the solution you'd like**
An idea could be: get at what time a bomb has been planted.

**Describe alternatives you've considered**
There are no alternatives.

**Comment by markus-wa** [comment]
I'm afraid this issue suffers from the same issue as #257 .

I have instead opted to add the following features
- `GameState.Rules().RoundTime()`
- `GameState.Rules().FreezeTime()`
- `GameState.Rules().BombTime()`

see #265
