### ISSUE TITLE
Possibility to get bomb time after bomb plant

### ISSUE THREAD

**Issue by pbuzulan** [markus-wa/demoinfocs-golang#257]
**Higher goal**
There is no function implemented that can extract the bomb timer after planted.

**Describe the solution you'd like**
An idea could be: get at what time a bomb has been defused.

**Describe alternatives you've considered**
There are no alternatives.

**Comment by markus-wa** [comment]
Hey, unfortunately this won't be possible.

There are a lot of edge cases where it's not clear what the bomb timer is (old demos, different gamemodes). 
To implement this we'd have to make some assumptions about these scenarios (e.g. what version of the game was the match played on).
However, this library aims to provide consistent and accurate information and these assumptions should only be made in consumer code.

I was hoping this would be easy but unfortunately I currently really don't see a way to support this reliably :disappointed:
