### ISSUE TITLE
Get GameMode/GameType

### ISSUE THREAD

**Issue by Julien2313** [markus-wa/demoinfocs-golang#267]
Hello,
I'd like to know by just parsing the header of the demo, the gameType/gameMode of the game ?

I'm allowing user to upload their own demo, and I'd like to know, without asking them, if it's a competitive game of just a DM.

Is it possible at this time ?

**Comment by markus-wa** [comment]
Hi @Julien2313 - The game-mode / game-type is not included in the file's demo header so this is not possible.

I recommend parsing until it's available and then aborting via `Parser.Cancel()`. alternatively`Parser.ParseNextFrame()` might also be interesting.

**Comment by Julien2313** [comment]
It works cleanly, thank you :)
