### ISSUE TITLE
Error wrong bombsite new map grind

### ISSUE THREAD

**Issue by Julien2313** [markus-wa/demoinfocs-golang#280]
**Describe the bug**
When trying to parse this game on the new map Grind, I got an error `panic: bomb not planted on bombsite A or B`

**To Reproduce**

Links to download demos : http://replay272.valve.net/730/003479822691228189340_1757036846.dem.bz2 (available 1 month since now)
http://replay187.valve.net/730/003480011012659216461_0088537034.dem.bz2

Code:
```go
package main

import (
	"bufio"
	"bytes"
	"compress/bzip2"
	"compress/gzip"
	"fmt"
	"io"
	"io/ioutil"
	"os"
	"path/filepath"

	"github.com/markus-wa/demoinfocs-golang/v2/pkg/demoinfocs"
)

func main() {
	demoFile, err := os.Open("path/to/demo")
	if err != nil {
		panic(err)
	}
	defer demoFile.Close()

	var demoUnzippedReader io.Reader
	switch filepath.Ext(demoFile.Name()) {
	case ".bz2":
		demoUnzippedReader = bzip2.NewReader(bufio.NewReader(demoFile))
	case ".gz":
		demoZippedReader, err := gzip.NewReader(demoFile)
		if err != nil {
			panic(err)
		}

		t, err := ioutil.ReadAll(demoZippedReader)
		if err != nil {
			panic(err)
		}
		demoUnzippedReader = bytes.NewReader(t)
	case ".dem":
		demoUnzippedReader = bufio.NewReader(demoFile)
	default:
		panic(err)
	}

	demoUnzippedBytes, err := ioutil.ReadAll(demoUnzippedReader)
	if err != nil {
		panic(err)
	}

	r := bytes.NewReader(demoUnzippedBytes)
	p := demoinfocs.NewParser(r)
	defer p.Close()

	demoHerader, err := p.ParseHeader()
	if err != nil {
		panic(err)
	}
	fmt.Println(demoHerader.MapName)

	err = p.ParseToEnd()
	if err != nil {
		panic(err)
	}
}

```

``` bash
de_grind
panic: bomb not planted on bombsite A or B

goroutine 1 [running]:
main.main()
        /home/julien/git/test-demoinfo/main.go:62 +0x83d
exit status 2
```

**Expected behavior**
Not getting an error

**Additional context**
The bomb in the round has never been planted anywhere in the round (occuring during the 5th for the first time) :( the only time it has been moved is when a player has been killed. nobody picked up the bomb again.

In previous round, someone (ok, it was me) died with the bomb, but the parser doesn't panic.
Maybe the demo is a little bite corrupted ? Idk :x But it appends 11 times during the parsing, so it's a bug corruption ? Ha ha. I guess this is "just" bad event on this map ? I can't tell you if this is happening on others demos on this map or not as I only have 1 demo on this one :(

Their is no such errors on the other new map Mocha

Thank you for your help :)

**Comment by Julien2313** [comment]
No no, digging to your code I understand ! Ha ha
Is their a way to avoid it to stop parsing the demo ?

I'm waiting you to do a game on it ! Ha ha
Yeah, I'll search another demo somewhere to check this

**Comment by markus-wa** [comment]
I'm afraid there's no way to prevent the crash as of now.

If it's critical for you I recommend temporarily forking the project and removing that panic - and hopefully I'll be able to get this sorted out properly by the end of next week and you can switch back to the official version.

**Comment by xiexiangchao** [comment]
this demo can reproduce this problem  http://replay234.wmsj.cn/730/003480539579251949579_0470276058.dem.bz2

**Comment by markus-wa** [comment]
thanks both for the additional samples.

tomorrow it's my first open-source Friday (:tada:), so should hopefully get around to it

**Comment by markus-wa** [comment]
I've removed the panic and replaced it with a `ParserWarn` event.
So after `go get -u github.com/markus-wa/demoinfocs-golang/v2/pkg/demoinfocs@v2.7.1` you should no longer see the panic.

However, this means `BombEvent. Site` may now be unknown/ undefined (meaning it's neither `BombsiteA` nor `BombsiteB`) - I'm not sure if this will be easily fixable

If you need bombsite information, I think a _workaround_ for now is that you do the following **in your code**:

```go
parser.RegisterEventHandler(func(planted events.BombPlanted) {
	if planted.Site != events.BombsiteA && planted.Site != events.BombsiteB && parser.Header().MapName == "de_grind" {
		planted.Site = events.BombsiteB
	}

	// handle event as usual
})
```

Hopefully I will be able to fix this properly at some point.

I have opened #284 to track the remaining issue of the missing bomb site information.

**Comment by Julien2313** [comment]
Thank you for your fix ! :)
