### ISSUE TITLE
Kills appears shows in-game demo viewer but not kill feed or demo

### ISSUE THREAD

**Issue by pnxenopoulos** [markus-wa/demoinfocs-golang#287]
Hi there,

I'm parsing the inferno demo from [https://www.hltv.org/matches/2337844/astralis-vs-liquid-blast-pro-series-global-final-2019](https://www.hltv.org/matches/2337844/astralis-vs-liquid-blast-pro-series-global-final-2019). It runs on an old version of Inferno, which you can get from the workshop at [https://steamcommunity.com/sharedfiles/filedetails/?id=2054468706](https://steamcommunity.com/sharedfiles/filedetails/?id=2054468706). In the fifth round, Stewie2K appears to get killed by Magisk, however, this does not show up in the kill feed, nor on the demo (I checked using the example code in the README which prints the kills). There is nothing showing this kill. What may be happening here?

Here's a photo:

![Screenshot from 2021-05-14 12-14-40](https://user-images.githubusercontent.com/42321130/118299185-6c58cc00-b4ae-11eb-9f20-93440caafca9.png)

**Comment by markus-wa** [comment]
HI @pnxenopoulos :wave: 

I've come across this before as well but there is nothing we can do unfortunately. As you noticed it doesn't show in the feed, and if it doesn't show in the feed the kill event is just not stored in the demo.

This answer is not very useful I'm afraid, but that's how it is sadly :disappointed:

**Comment by markus-wa** [comment]
closing this for now, let me know if you have further questions :)
