### ISSUE TITLE
New kill feed

### ISSUE THREAD

**Issue by AKaravas** [markus-wa/demoinfocs-golang#293]
CS:GO has added some new icons on the killing feed, like assisted flashed or through smoke. Is it possible to get those as well?

I guess on the kills array should be two or three entries with the name: IsThoughSmoke, IsAttackerFlashed, IsVictimFlashed and the old IsFlashed should be removed.

Best regards

**Comment by markus-wa** [comment]
These are already available with the latest version :slightly_smiling_face:  https://pkg.go.dev/github.com/markus-wa/demoinfocs-golang/v2@v2.8.1/pkg/demoinfocs/events#Kill

**Comment by AKaravas** [comment]
thanks again markus
