### ISSUE TITLE
Addition of de_ancient to the list of pre-defined map translations

### ISSUE THREAD

**Issue by luke1337go** [markus-wa/demoinfocs-golang#294]
Hi!
Would be nice if you could add de_ancient to your ["list of pre-defined map translations"](https://github.com/markus-wa/demoinfocs-golang/blob/f66ed2f8f3a4aaefc1af961f0d5ccd73b5821de2/pkg/demoinfocs/metadata/maps.go#L34) of the official maps, so that other applications can rebuild and update with the new map. 
Thank you for your effort, have a good day!
Luke

**Comment by markus-wa** [comment]
Hi Luke, I'll see if I can get around to this soon :tm: 

The whole metadata stuff probably needs updating anyway as maps will have changed (last actual changes to scales etc was 3 years ago, yikes!)

Note that it's pretty easy to override, change and add maps by going somthing like
```
metadata.MapNameToMap["de_ancient"] = metadata.Map{
  Name: "de_ancient",
  PZero: r2.Point{X: ..., Y: ...},
  Scale: ...,
}
```

Needs a bit of fiddling to get the scaling right but this example can be a good testing ground: https://github.com/markus-wa/demoinfocs-golang/tree/master/examples/heatmap

I also have some interesting ideas to automate all of this going forward but I'm not sure if/when I'll get to that (and not sure it would be part of this library).

I'm also always more than happy to review and approve any PR for this, so if you'd like to have a go please do :slightly_smiling_face: - that's probably the quickest path to get this in.

**Comment by markus-wa** [comment]
thanks to @srjnm 's PR #302 we've now got this in.

I also learned that these translations are much easier to get than just manually trying every possible value :sweat_smile: so I've added cs_office and cs_agency as a bonus
