### ISSUE TITLE
No thrower or grenade present in the FireStartedEvent

### ISSUE THREAD

**Issue by sirherrbatka** [markus-wa/demoinfocs-golang#301]
**Describe the bug**
I noticed that the thrower can't be found in the demo for the FireGrenadeStart event.

**To Reproduce**
Seen in both demos in this best of 3 https://www.hltv.org/matches/2346581/virtuspro-vs-vitality-iem-katowice-2021

Code:
```
func handleSmokeFireExpired(e *events.GrenadeEvent) {
	if e.Thrower == nil {
		log.Printf("No player for the granade expiration %d.\n", e.GrenadeType)
		return
	}
}
```

**Expected behavior**
Nothing gets logged.

**Library version**
e.g. v2.6.0

**Additional context**
Smokes work fine.

**Comment by markus-wa** [comment]
👋 @sirherrbatka - as the docs on that event say, thrower will always be nil as it isn't networked.

You can try using `InfernoStart.Inferno.Thrower()` instead 🙂

I might add some docs to redirect to `InfernoStart`

Do note that the two are not exactly equivalent, FireGrenadeStart is a game event, whereas InfernoStart is derived from the fire grenade's entity updates

**Comment by sirherrbatka** [comment]
Wow, ok, interesting. I assumed that smoke and fire grenades should work the same way but I see that this is not true. Thanks.

**Comment by markus-wa** [comment]
yeah, CS:GO demos are a bizzare and unpredictable thing :sweat_smile:
