### ISSUE TITLE
Player RawWeapons + Weapons are probably kinda broken

### ISSUE THREAD

**Issue by markus-wa** [markus-wa/demoinfocs-golang#31]
https://github.com/markus-wa/demoinfocs-golang/blob/de04794d31423c09faa17f772cd338b2e31cd55c/datatables.go#L279

https://github.com/markus-wa/demoinfocs-golang/blob/de04794d31423c09faa17f772cd338b2e31cd55c/game_events.go#L440

This doesn't make any sense.

`Player.Weapons` is never set and some code for the `RawWeapons` is never run because `cache[i2]` is always 0, that can't be right.
https://codecov.io/gh/markus-wa/demoinfocs-golang/src/master/datatables.go#L260

**Comment by micvbang** [comment]
Yep, agreed. Especially the code in datatables makes no sense.

**Comment by markus-wa** [comment]
Fixed according to https://github.com/markus-wa/demoinfocs-golang/pull/30#issuecomment-402944264
