### ISSUE TITLE
Extracting player location name in string form

### ISSUE THREAD

**Issue by pnxenopoulos** [markus-wa/demoinfocs-golang#311]
In-game, you can see the name of the part of the map you are in (e.g., "Tunnels", "Hut", etc.)

Is this possible to extract through the parser from the demos themselves? I know it is possible to use the `.nav` files and translate the player coordinates using some navigation file parsers out there, but it would be helpful if we could parse this information directly from the demo file.

**Comment by Piku7** [comment]
You can get it from entity's properties:
```
pl.Entity.PropertyValueMust("m_szLastPlaceName").StringVal
```

I tested it on de_mirage demo and I got following locations:
`
TopofMid Ladder  Apartments House BackAlley Connector Shop Stairs Scaffolding CTSpawn SideAlley Tunnel TSpawn Middle SnipersNest Jungle TunnelStairs TicketBooth BombsiteA Balcony Truck PalaceInterior BombsiteB Catwalk PalaceAlley TRamp
`

If you want to use translated names then you will have to parse csgo_*.txt files found in CSGO_DIRECTORY/csgo/resource:
```
"TicketBooth" "Ticket Booth" // English
"TicketBooth" "Θάλαμος εισιτηρίων" // Greek
"TicketBooth" "Budka biletowa" // Polish
```

**Comment by markus-wa** [comment]
Might be a good idea to have a function `Player.LastPlaceName()` since this question has come up more than once now.

If anyone would like to make a PR let me know, otherwise I'll try to implement it next week or so.

**Comment by markus-wa** [comment]
and thanks @Piku7 ! :heart:

**Comment by pnxenopoulos** [comment]
> Might be a good idea to have a function `Player.LastPlaceName()` since this question has come up more than once now.
> 
> If anyone would like to make a PR let me know, otherwise I'll try to implement it next week or so.

Threw this up: #312
