### ISSUE TITLE
README.md invalid Discord invite link

### ISSUE THREAD

**Issue by SteveBox0** [markus-wa/demoinfocs-golang#316]
The discord invite link included in the README.md is invalid. Could you please look at updating the readme.

https://discord.gg/69Y2MM7E

**Comment by markus-wa** [comment]
hi @SteveBox0 - thanks for bringing this to my attention!

That's rather embarrassing as I just set that up last week :sweat_smile: - I've fixed it now, please try again :slightly_smiling_face:

Cheers!
