### ISSUE TITLE
Door opened/broken event?

### ISSUE THREAD

**Issue by ericreinke** [markus-wa/demoinfocs-golang#319]
I was wondering if there was any research already done into "door open" or "door broken" events?  Less important but under the same strain; glass broken events?

If there is already any research already done with it

**Comment by markus-wa** [comment]
hey @ericreinke 

great question.

might be worth having a look at `CPropDoorRotating`, `CBasePropDoor` or `CBaseDoor` in  https://raw.githubusercontent.com/wiki/markus-wa/demoinfocs-golang/Server-Class-Properties.txt

but I'm not sure how to do it at this point

let me know if you figure something out

**Comment by ericreinke** [comment]
Oh wow thats probably exactly what I'm looking for.  There doesn't happen to be any documentation on the properties of all the classes, does there?

**Comment by markus-wa** [comment]
Not that I'm aware of I'm afraid

**Comment by markus-wa** [comment]
I'm assuming this can be closed?
