### ISSUE TITLE
ICE key creation error when decryption key is provided

### ISSUE THREAD

**Issue by akiver** [markus-wa/demoinfocs-golang#338]
**Describe the bug**

While parsing demos to investigate https://github.com/markus-wa/demoinfocs-golang/issues/326, I encountered an error with a few Valve demos when using `NetMessageDecryptionKey`.

The call to `ice.NewKey` fails, here is the stacktrace:

```
runtime error: index out of range [15] with length 15
stacktrace:
goroutine 40 [running]:
runtime/debug.Stack()
	Go/src/runtime/debug/stack.go:24 +0x7a
github.com/markus-wa/demoinfocs-golang/v2/pkg/demoinfocs.NewParserWithConfig.func1({0xa777a0, 0xc0006f6170})
	go/pkg/mod/github.com/markus-wa/demoinfocs-golang/v2@v2.13.0/pkg/demoinfocs/parser.go:354 +0x45
github.com/markus-wa/godispatch.(*Dispatcher).dispatchWithRecover.func1()
	go/pkg/mod/github.com/markus-wa/godispatch@v1.4.1/dispatch.go:197 +0x58
panic({0xa777a0, 0xc0006f6170})
	Go/src/runtime/panic.go:1047 +0x262
github.com/markus-wa/godispatch.callConsumerCode.func1()
	go/pkg/mod/github.com/markus-wa/godispatch@v1.4.1/dispatch.go:122 +0x7b
panic({0xa8d0e0, 0xc003cd1a70})
	Go/src/runtime/panic.go:1047 +0x262
github.com/markus-wa/ice-cipher-go/pkg/ice.NewKey(0x2, {0xc0000a9610, 0xf, 0x10})
	go/pkg/mod/github.com/markus-wa/ice-cipher-go@v0.0.0-20220126215401-a6adadccc817/pkg/ice/ice.go:202 +0x615
github.com/markus-wa/demoinfocs-golang/v2/pkg/demoinfocs.(*parser).handleEncryptedData(0xc0000ea000, 0xc003139680)
	go/pkg/mod/github.com/markus-wa/demoinfocs-golang/v2@v2.13.0/pkg/demoinfocs/net_messages.go:94 +0xa5
reflect.Value.call({0xa37200, 0xc0000e20f0, 0x13}, {0xad16a6, 0x4}, {0xc005fa3e80, 0x1, 0x1})
	Go/src/reflect/value.go:543 +0xc05
reflect.Value.Call({0xa37200, 0xc0000e20f0, 0x13}, {0xc005fa3e80, 0x1, 0x1})
	Go/src/reflect/value.go:339 +0xb7
github.com/markus-wa/godispatch.callConsumerCode({0xa37200, 0xc0000e20f0, 0x13}, {0xc005fa3e80, 0x1, 0x1})
	go/pkg/mod/github.com/markus-wa/godispatch@v1.4.1/dispatch.go:125 +0xaf
github.com/markus-wa/godispatch.(*Dispatcher).Dispatch(0xc0000fa000, {0xaa5b20, 0xc003139680})
	go/pkg/mod/github.com/markus-wa/godispatch@v1.4.1/dispatch.go:111 +0x2a6
github.com/markus-wa/godispatch.(*Dispatcher).dispatchWithRecover(0xc0000fa000, {0xaa5b20, 0xc003139680})
	go/pkg/mod/github.com/markus-wa/godispatch@v1.4.1/dispatch.go:202 +0xa8
github.com/markus-wa/godispatch.(*Dispatcher).dispatchQueue(0xc0000fa000, 0xc0000fa0c0)
	go/pkg/mod/github.com/markus-wa/godispatch@v1.4.1/dispatch.go:177 +0xf8
created by github.com/markus-wa/godispatch.(*Dispatcher).AddQueues
	go/pkg/mod/github.com/markus-wa/godispatch@v1.4.1/dispatch.go:162 +0x369
```

**To Reproduce**

Affected demo with its .info file https://mega.nz/file/XM0gkRaC#__1Z21ymvgvJIGowCOvA-Gv5IVkjRzsBtYU-kqUruHc

Code:

The error should occur with the snippet from the [v2.13.0](https://github.com/markus-wa/demoinfocs-golang/releases/tag/v2.13.0).

**Expected behavior**

No error.

**Library version**
v2.13.0

**Additional context**

I had the error 13 times out of 210 demos, I can upload more affected demos if needed.
When using my own implementation that I would like to remove it works fine and encrypted messages are correctly parsed.
I didn't find a Go ice implementation so I ported the ~C version~ JS version that I'm currently using, you can find it [here](https://github.com/akiver/go-ice) if that can help.

Thank you!

**Comment by markus-wa** [comment]
Hi @akiver thanks for the report!

would you be able to take a look at https://github.com/markus-wa/ice-cipher-go and see if you can spot the bug there?

**Comment by markus-wa** [comment]
`index out of range [15] with length 15` - the key should always be 16 bytes I think, so might be an issue with how we read the key?

**Comment by markus-wa** [comment]
yup, there's a mistake in key extraction :sweat:

**Comment by markus-wa** [comment]
should be fixed with https://github.com/markus-wa/demoinfocs-golang/pull/339

please verify

**Comment by akiver** [comment]
Tested, all affected demos are now OK, thanks!
