### ISSUE TITLE
Get player's button presses infomation

### ISSUE THREAD

**Issue by hx-w** [markus-wa/demoinfocs-golang#340]
**Higher goal**
I want to get player's button presses infomation in a tick frame, so I can know whether player is pressing `W A S D` or not (this is not meaning player is really moving front, left, back or right).

In sourcemod, player's button info will be encoded with [different button presses](https://github.com/alliedmodders/sourcemod/blob/01203a5a449b5e8a26e6f3fa6b91a3a8b9a68c07/plugins/include/entity_prop_stocks.inc#L99-L125) and I can get player's button by using function [`int GetClientButtons(int client)`](https://github.com/alliedmodders/sourcemod/blob/01203a5a449b5e8a26e6f3fa6b91a3a8b9a68c07/plugins/include/entity_prop_stocks.inc#L574-L594).

I noticed that there is no such method to get player's button presses in [Player](https://pkg.go.dev/github.com/markus-wa/demoinfocs-golang/v2@v2.13.1/pkg/demoinfocs/common#Player), and I tried with using     `player.Entity.PropertyValue("m_nButtons")` and got false, since there is no `"m_nButtons"` property in `player.Entity.ServerClass()`. So I wonder if there could be a method to implement this feature.

**Describe the solution you'd like**

It will be very nice if there is a `Buttons()` or `ButtonsPressing()` method which return a `int32` value that can be decoded in a specific way in [Player](https://pkg.go.dev/github.com/markus-wa/demoinfocs-golang/v2@v2.13.1/pkg/demoinfocs/common#Player). **Or** just tell me how to get `"m_nButtons"` or some properties relevant to button pressing else. 

**Describe alternatives you've considered**

There is a callback function [OnPlayerRunCmd](https://sm.alliedmods.net/new-api/sdktools_hooks/OnPlayerRunCmd) in sourcemod, and parameter `int& buttons` is what I metioned above.

If it is difficult to get button presses, I wish I can get player's **desired velocity** (`float vel[3]`) instead (not [actual velocity](https://pkg.go.dev/github.com/markus-wa/demoinfocs-golang/v2@v2.5.0/pkg/demoinfocs/common#Player.Velocity)).

> Player's desired velocity is presented as {450, 0, 0} when player pressing `W` even if he is not actually moving front.
> And {-450, 0, 0} when pressing `S`, {0, -450, 0} when pressing `A`, {0, 450, 0} when pressing `D` for example.
> The no-zero value may not awalys be 450 and `vel[2]` always be 0 based on my few testings.
> I hope these statements wont confuse you 😵‍💫 .

**Additional context**

None.

**Comment by markus-wa** [comment]
Thanks for the request.

This is unfortunately not possible as this information is not stored in the demo :disappointed:

**Comment by hx-w** [comment]
Thanks for the quick answer, I will let you know if I have an approach.
