### ISSUE TITLE
repository 'https://github.com/jteeuwen/imghash/' not found

### ISSUE THREAD

**Issue by JurreH23** [markus-wa/demoinfocs-golang#344]
When doing anything related to the maps, for example the heatmap the https://github.com/jteeuwen/imghash/ repository is needed but can not be found. This means I'm currently unable to do anything with these features because of the fact that the repository isn't there.

If there is a fix for this then I'd like to know.

**Comment by markus-wa** [comment]
hmm, this should have been fixed a long time ago if i remember correctly.

I'm away on holiday, but will take a look next week

**Comment by markus-wa** [comment]
make sure you're on the latest version

**Comment by markus-wa** [comment]
also, please include full steps or code to reproduce this

**Comment by JurreH23** [comment]
First I used the quick start guide to run the example on a demo I have and this works. Next I copied the heatmap.go code and ran it using "go run heatmap.go -demo /path/to/demo > out.jpg". It tells me I have to download a package using this command "go mod download github.com/dustin/go-heatmap". Next I do go mod tidy which is when it starts looking for the package I mentioned before.

**Comment by markus-wa** [comment]
you will need this in your `go.mod`: https://github.com/markus-wa/demoinfocs-golang/blob/master/go.mod#L17

I will see if I can make this more obvious or something

**Comment by JurreH23** [comment]
Thanks, it works now
