### ISSUE TITLE
Counter-Strike 2 Support [Work In Progress]

### ISSUE THREAD

**Issue by sparkoo** [markus-wa/demoinfocs-golang#382]
Hello,
what are plans for this lib with Counter Strike 2? Do you plan to port this library to it? Have you already checked the differences of demo format? Do you welcome any help with update?

P.S. thank you for the great work on this amazing library

**Comment by markus-wa** [comment]
Hi @sparkoo - this is in the works here: https://github.com/markus-wa/demoinfocs-golang/pull/383 :slightly_smiling_face:

**Comment by sparkoo** [comment]
wonderful. you're lightning fast ❤️

**Comment by osztenkurden** [comment]
Hey, thank you for doing so much good work. I've got a quick question - am I correct in saying that CS2 demos have fewer event types than CS:GO demos for now? Asking mostly about `player_hurt` event, it seems that it doesn't exist.

**Comment by markus-wa** [comment]
@osztenkurden I think `player_hurt` like many other events doesn't exist in CS2 MM demos. but if `cs2.exe` is started with `-dedicated` flag, I think the event works.

**Comment by markus-wa** [comment]
v4.0.0 is now out in beta, so I'm closing this issue :slightly_smiling_face:
