### ISSUE TITLE
Exposing vendored types to user, e.g. in OnPositionUpdate(r3.Vector)

### ISSUE THREAD

**Issue by micvbang** [markus-wa/demoinfocs-golang#40]
It may be that I'm just unaware of how this can be circumvented, but I'm having trouble using the callbacks that require the usage of vendored types, e.g. `Entity.OnPositionUpdate(r3.Vector)`. 

It makes sense that I can't just use the type as `r3.Vector` in my source, as it may be different from the vendored version. And the compiler won't let me import vendored packages, which I'm not absolutely certain that I understand why wouldn't work. Anyway, unless there's some way out of this that I can't see, I think we need to look at the types from vendored code used in callbacks to publicly exported code :slightly_smiling_face: 

The most obvious solution that I can come up with is to create the simplest possible wrappers for these types, e.g. where `r3.Vector` is used, one could create the type `Vector` and use it like so:

```
type Vector struct {
    r3.Vector
}

// example of internal use in demoinfocs-golang
func test(v r3.Vector) Vector {
    return Vector{v}
}
```

**Comment by markus-wa** [comment]
Interesting. I'm wondering if this might also be resolvable by switching from dep to vgo modules.

I'll experiment a bit with that and see where it takes me.

**Comment by micvbang** [comment]
Sounds good!

**Comment by markus-wa** [comment]
I got it working by either using dep or vgo. I'd suggest using dep for now since vgo still isn't supported by default until go 1.12

Let me know if this helps.

### Code

```
package main

import (
	"fmt"
	"os"

	r3 "github.com/golang/geo/r3"

	dem "github.com/markus-wa/demoinfocs-golang"
)

func main() {
	f, _ := os.Open("asdf")
	p := dem.NewParser(f)

	p.GameState().Entities()[0].OnPositionUpdate(func(pos r3.Vector) {
		fmt.Println(pos)
	})
}
```

### dep

`Gopkg.toml`
```toml
[[constraint]]
  branch = "master"
  name = "github.com/golang/geo"

[[constraint]]
  name = "github.com/markus-wa/demoinfocs-golang"
  branch = "v1.0.0"

[prune]
  go-tests = true
  unused-packages = true
```

### vgo

`go.mod`
```
module demoinfocs-consumer

require (
	github.com/golang/geo v0.0.0-20180826223333-635502111454
	github.com/markus-wa/demoinfocs-golang v0.0.0-20180826223333-710bc4b6373601
)
```

**Comment by markus-wa** [comment]
I'm not entirely sure what the right thing to do is here. Exposing the types seems like unnecessary code but forcing consumers to use dep or vgo doesn't seem right either, especially if someone just wants to do some quick testing.

**Comment by micvbang** [comment]
Cool, thank you!

I think your worries about forcing consumers to use dep or vgo are very reasonable. Since the wrapper types proposed above only have to be created once, and never are required to be updated, I don't think it's too much extra code to write/maintain. 

As far as I see it, the advantages to the consumer greatly outweigh the cost of the extra code/maintenance :slightly_smiling_face:

**Comment by markus-wa** [comment]
I totally agree with you. However, here's why I'm still somewhat reluctant.

I've decided to wait with the release of `v1.0.0` until `go 1.12 (vgo)` and I'm not sure how that version of go will handle this situation. For instance, if modules become the standard for any new app / library created with 1.12 this change wouldn't be neccessary.

The reason for waiting for vgo is that I'm not sure if it would be possible to switch from dep to vgo without a `v2.0.0`. In fact, I highly doubt it.

From the proposal:
> 10. Disallow use of vendor directories, except in one limited use: a vendor directory at the top of the file tree of the top-level module being built is still applied to the build, to continue to allow self-contained application repositories. (Ignoring other vendor directories ensures that Go returns to builds in which each import path has the same meaning throughout the build and establishes that only one copy of a package with a given import path is used in a given build.)

Also the library would potentially become non go-gettable if we were to stay with dep.

> In a later release (say, Go 1.13), we will end support for go get of non-modules. Support for working in GOPATH will continue indefinitely.


What I'd be open to is changing it to wrappers now with the intent to change it back for the final v1.0.0, if possible.
Then again, I'm also not completely statisfied with an API breaking change that's intended to be reverted, resulting in yet another one.

We could also let this sit until we get our hands on the first 1.12 RC, assuming that the `v1.0.0` branch is probably not being used by too many people.

What's your opinion on all this?

**Comment by micvbang** [comment]
Aha, I see. I appreciate your concerns and agree with you that it seems somewhat funny to make a change that we intend to roll back soon-ish.

What do you say that we keep it as-is for now, and if I or anyone else gets too frustrated with it, we make the change to expose internal wrapper type, and then roll it back when 1.12 is released?

**Comment by markus-wa** [comment]
Sounds good to me :)

**Comment by markus-wa** [comment]
Reopening so it stays visible

**Comment by markus-wa** [comment]
Closing this due to #61 getting merged
