### ISSUE TITLE
CS2 missing Victim in events.Kill events

### ISSUE THREAD

**Issue by Run1e** [markus-wa/demoinfocs-golang#410]
**Describe the bug**
In this demo, some `events.Kill` events does not have an `event.Victim`.

**To Reproduce**
Replay: http://replay192.valve.net/730/003636918966984638563_0319322389.dem.bz2

My events.Kill event handler looks roughly like this:

```
	p.RegisterEventHandler(func(e events.Kill) {
		if !gs.IsMatchStarted() {
			return
		}

		if gs.IsWarmupPeriod() {
			return
		}

		if e.Killer == nil {
			return
		}

		if e.Killer == e.Victim {
			return
		}
		
		// misc. other code here, where the properties of e.Victim are needed
	})
```

**Expected behavior**
`event.Victim` to be populated.

**Library version**
4.0.0-beta.0

**Comment by markus-wa** [comment]
I will close this and mark it as fixed given #412 has been merged

please comment and re-open if the issue persists :slightly_smiling_face:
