### ISSUE TITLE
map name is not available

### ISSUE THREAD

**Issue by penjiu** [markus-wa/demoinfocs-golang#414]
Describe the bug
map name cannot be accessed from header.mapName

To Reproduce
Code:
	demo, err := os.Open(demoFile)
	if err != nil {
		return nil, err
	}
	defer demo.Close()

	parser := dem.NewParser(demo)
	defer parser.Close()
	header, err := parser.ParseHeader()
	if err != nil {
		return nil, err
	}
       fmt.Println("map name: ", header.mapName)

Expected behavior
mapName can be printed in the console.

Library version
v4.0.0-beta.1

**Comment by markus-wa** [comment]
hi @penjiu - to get the map name you can 

```RegisterNetMessageHandler(msg *msgs2.CSVCMsg_ServerInfo) {
// msg.MapName
}```

When I have some time I will add necessary documentation / changes for this - possibly deprecating the header field and adding a new event `MapName`.

**Comment by penjiu** [comment]
it works!
thank you for the quick reply.
