### ISSUE TITLE
[CS2] Missing player data on some demos.

### ISSUE THREAD

**Issue by philliplakis** [markus-wa/demoinfocs-golang#419]
**Describe the bug**
Some demos fail to provide `PlayerConnect` event for the team, the missing data is also not available in `p.GameState().Participants().Playing()` 

**To Reproduce**
The below Faceit demo has 0 players connect.
https://demos-europe-west2.faceit-cdn.net/cs2/1-abf3157b-1865-4334-aef4-b98ce9ffe154-1-1.dem.gz 

The below Valve match has only 1 team connect.
http://replay129.valve.net/730/003636850833770938391_1171564125.dem.bz2

Code:
```go
func main() {
	f, err := os.Open("003636850833770938391_1171564125.dem")
	if err != nil {
		log.Panic("failed to open demo file: ", err)
	}
	defer f.Close()

	p := dem.NewParser(f)
	defer p.Close()

	p.RegisterEventHandler(func(e events.PlayerConnect) {
		log.Printf("~~~~~~~ New player connected: %v" , e.Player.SteamID64)
	})

	p.RegisterEventHandler(func(e events.MatchStart) {
		var players = p.GameState().Participants().Playing()
		for _, currPlayer := range players {
			var teamString = "Unknown"
			if currPlayer.Team == 2 {
				teamString = "T"
			} else {
				teamString = "CT"
			}
			log.Printf("****** Steamid: %v, on %s" , currPlayer.SteamID64, teamString)
		}
	})
	
	// Parse to end
	err = p.ParseToEnd()
	if err != nil {
		log.Panic("failed to parse demo: ", err)
	}
	
	log.Printf("Finished!")
}
```

**Expected behavior**
I expect all players that connect to a match to be returned in the event.

**Library version**
v4.0.0-beta.2

**Additional context**
I can supply a handful of demo url files that this issue is happening if that would help you.

**Comment by markus-wa** [comment]
can you check if https://github.com/markus-wa/demoinfocs-golang/pull/420 fixes this?

**Comment by philliplakis** [comment]
@markus-wa Yes, works well for the 5 examples i have. 🙏
