### ISSUE TITLE
Smoke grenade OnDestroy event not triggered as expected

### ISSUE THREAD

**Issue by micvbang** [markus-wa/demoinfocs-golang#42]
**Describe the bug**
In datatables.bindGrenadeProjectiles we assume that the projectile entity destroy-event is triggered _every time_ the entity no longer appears in the game. I still haven't found out _why_, but this does not seem to be the case. It looks to me like projectile destruction event is not triggered on smokes (more entities?) that do not expire normally, but are "removed" because the round has ended.

**To Reproduce**
I found the bug in round 4 of de_nuke in the following game: https://www.hltv.org/matches/2322780/liquid-vs-astralis-esl-pro-league-season-7-finals

```
package main

import (
	"log"
	"os"
	"sync"

	dem "github.com/markus-wa/demoinfocs-golang"
	"github.com/markus-wa/demoinfocs-golang/events"
)

func main() {
	f, err := os.Open("liquid-vs-astralis-m2-nuke.dem")
	if err != nil {
		log.Fatal(err)
	}

	p := dem.NewParser(f)
	_, err = p.ParseHeader()
	if err != nil {
		log.Fatal(err)
	}

	wg := &sync.WaitGroup{}

	roundNum := 0
	p.RegisterEventHandler(func(_ events.RoundOfficiallyEndedEvent) {
		roundNum++
	})

	p.RegisterEventHandler(func(_ events.RoundStartedEvent) {
		log.Printf("Round %+v just started. We expect there to be no projectiles. There are: %+v\n", roundNum, len(p.GameState().GrenadeProjectiles()))
	})

	err = p.ParseToEnd()
	if err != nil {
		log.Fatal(err)
	}

	wg.Wait()
}

```

**Expected behavior**
I expect GameState().GrenadeProjectiles() to only contain _active_ grenade projectiles, even those that did not expire normally

**Library version**
v1.0.0

A quick (and dirty) way to solve the problem is to simply reset the gameState.grenadeProjectiles map on RoundOfficiallyEnded event, like so (`game_events.go`):

```
...
case "round_officially_ended": // Round ended. . . probably the event where you get teleported to the spawn (=> You can still walk around between round_end and this?)
	for _, proj := range p.gameState.grenadeProjectiles {
		delete(p.gameState.grenadeProjectiles, proj.EntityID)
	}
	p.eventDispatcher.Dispatch(events.RoundOfficiallyEndedEvent{})
case ...
```

**Comment by markus-wa** [comment]
This feels familiar, maybe due to the round ending while smokes are still up?

Will look into it over the coming days.
