### ISSUE TITLE
Empty GameRules without calling ParseToEnd

### ISSUE THREAD

**Issue by statist32** [markus-wa/demoinfocs-golang#421]
**Describe the bug**
The GamesRules which are printed are an empty map.
If I call `parser.ParseToEnd` the map is not empty and contains most of the convars.
A `parser.ParseNextFrame` call still results in an empty map.

**To Reproduce**
Download a demo like any from the following [hltv event page](https://www.hltv.org/results?event=6334)

Code:
```go
package main

import (
	"fmt"
	"os"

	dem "github.com/markus-wa/demoinfocs-golang/v4/pkg/demoinfocs"
)

func main() {
	file_name := "fileName.dem"
	f, err := os.Open(file_name)
	defer f.Close()
	if err != nil {
		panic(err)
	}
	// Create new demoparser
	parser := dem.NewParser(f)
	defer parser.Close()

	if err != nil {
		panic(err)
	}
	// The printed map is empty without this function call
	// parser.ParseToEnd()

	fmt.Println(parser.GameState().Rules())
}
```

**Expected behavior**
The map with the convars should be printed without calling `parser.ParseToEnd`.

**Library version**
v4

**Additional context**
M1 - Arm - go 1.21.1

**Comment by markus-wa** [comment]
This is expected - the state is only valid as point in time - without parsing we don't know the rules, and the rules may change during the game, so calling ParseToEnd first will give you the rules at the end of the game
