### ISSUE TITLE
[CS2] incorrect simulationTimeDecoder logic 

### ISSUE THREAD

**Issue by oxiKKK** [markus-wa/demoinfocs-golang#433]
**Describe the bug**
Tickrate calculation inside simulationTimeDecoder is incorrect. The calculation for "frame/tick time" inside this function is supposed to be targeted towards 64 tickrate value, not 30. See below for proof.

Code:
```go
func simulationTimeDecoder(r *reader) interface{} {
	return float32(r.readVarUint32()) * (1.0 / 30)
}
```

Howerver, should be:
```go
func simulationTimeDecoder(r *reader) interface{} {
	return float32(r.readVarUint32()) * (1.0 / 64) // 64 is the cs2 tick-rate.
}
```
**Proof**

This is a decompiled function that is supposed to decode simulation time:

client.dll!"41 83 78 2C 02 75 44 41 83 78 28 01 75 3D 49 8B 10 0F 57 C0 48 85 D2 78 07 F3 48 0F 2A C2 EB 15"
![image](https://github.com/markus-wa/demoinfocs-golang/assets/28988905/33e53924-b435-4dd0-a536-fd791a532987)

(1.0 / 0.015625 is 64...)

The 30 was probably leftover from the dota parser, since the tickrate in dota2 is fixated to 30.

In other places I've also seen + 0.5, so I don't really know what is the right option.

client.dll!"48 8B 41 18 F3 0F 10 00 F3 0F 59 05 ?? ?? ?? ?? 41 C7 40 2C 02 00 00 00 41 C7 40 28 01 00 00 00 F3 0F 58 05 ?? ?? ?? ?? F3 0F 2C C0 48 63 C8 B8 01 00 00 00 49 89 08 C3"
![image](https://github.com/markus-wa/demoinfocs-golang/assets/28988905/76ce3974-7cc6-419d-b88f-1299fbfa840e)

**Comment by akiver** [comment]
Thank you!
Changed in https://github.com/markus-wa/demoinfocs-golang/pull/436
