### ISSUE TITLE
Writing custom logic inside `RegisterEventHandler` stops the demo from being entirely parsed and stops at half time.

### ISSUE THREAD

**Issue by noxterr** [markus-wa/demoinfocs-golang#445]
**Describe the bug**
I want to catch every event when a kill is done. Every time there is a kill, I want to save certain info about that in an element of a struct I have. Then, I'll append those elements into a slice and save them into the DB with GORM. The issue is that, when I try to create the element and append it to the slice, the caught events drop and stop at half-time, and I don't know why.

**To Reproduce**
Download this demo through [this link](https://cdn.noxter.me/demo.gz?download=1) of my CDN (will download a .zip containing the demo of [this game](https://www.faceit.com/en/csgo/room/1-54cc0018-af9a-4dca-a57d-22a9f13fbaaf))
The demo is of a CSGO game because CS2 has issues on demos now, so I won't use it for now.
Parse the demo according to [this repo's example](https://github.com/markus-wa/demoinfocs-golang#example) and modify the code like shown below

Code:
```go
type Player struct {
	Round_number               int           `json:"round_number"`
	Assister                   string        `json:"assister"`
	Victim                     string        `json:"victim"`
	Killer                     string        `json:"killer"`
}

var (
    players []Player
    round int
)

// Here resides the prior logic to registering an event that is available via the example

p.RegisterEventHandler(func(e events.Kill) {
	 fmt.Printf("Round %v: %s <%v> %s\n", round, e.Killer, e.Weapon, e.Victim)
	 player := Player{
		 Round_number:  round,
		 Killer:        e.Killer.Name,
		 Victim:        e.Victim.Name,
		 Assister:      e.Assister.Name,
		 AttackerBlind: e.AttackerBlind,
	 }

        players = append(players, player)
})

parsedDemo.RegisterEventHandler(func(e events.RoundEndOfficial) {
	round += 1
})

// Call my DB with players and save them [...]

```

**Expected behavior**
The expected behavior is that my slice (and so my table on the DB) should contain as many records as kills on the game, if not more (considering warmup), but instead, I get far fewer records.

**Library version**
v3

**Additional context**
 Using Windows 10, go 1.8.15. If something is missing and more info is required, just tell me and I'll provide as much as I can. If the error resides in some poorly written code, please don't hesitate to tell me as it will be a good starting point to improve.

Thanks for having read!

**Comment by akiver** [comment]
Hello,

Your program crashes with an `invalid memory address or nil pointer dereference` error because you are trying to access `Name` on a `nil` pointer.
`Killer`, `Victim`, and `Assister` may be `nil`, you have to check if it's `nil` before accessing `Name`.

```go
 player := Player{
	 Round_number:  round,
	 Killer:        e.Killer.Name, // <- may be nil
	 Victim:        e.Victim.Name, // <- may be nil
	 Assister:      e.Assister.Name, // <- may be nil
	 AttackerBlind: e.AttackerBlind,
 }
```

I'm closing it since it's not a parser issue.
