### ISSUE TITLE
Possible integration of Source1 (CS:S)?

### ISSUE THREAD

**Issue by derkalle4** [markus-wa/demoinfocs-golang#451]
Hi, I haven't found any other Issue regarding support for Source1 games, specifically CS:S. Would that be a possibility (I know it is not a priority).

Kind Regards,
Kalle

**Comment by markus-wa** [comment]
Hi @derkalle4 - thanks for the suggestion, but unfortunately this is outside the scope of this project.

Adding CS:S or other games support would increase the complexity a huge amount for what is a small user base.
Even CS2 has made things pretty complicated even though CS:GO and CS2 are incredibly similar in many ways.

So sadly CS:S support won't happen here.

**Comment by derkalle4** [comment]
No worries. Many thanks for the quick response :)
