### ISSUE TITLE
Kill events triggering before PlayerHurt events

### ISSUE THREAD

**Issue by Falderebet** [markus-wa/demoinfocs-golang#457]
**Describe the bug**
Kill and playerhurt events trigger in wrong chronological error order (may be due to sub-tick). See example:

```
"zorte<6><TERRORIST>" [490 -474 -160] killed "siuhy<15><CT>" [-946 -659 -263] with "awp"
"zorte<6><TERRORIST>" [490 -474 -160] attacked "siuhy<15><CT>" [-946 -659 -263] with "awp" (damage "108") (health "0")
```

**To Reproduce**
Download link to demo: 

https://drive.google.com/file/d/1NXLcl3n8roTLqyRDH2LBhWF1YItkisbA/view?usp=sharing

Round where it happens:
CT 15 | T 15

**Expected behavior**
That the kill events triggers after playerhurt events.

**Library version**
v4.0.0-beta.5

**Additional context**
This might be due to CS2 sub-tick.

**Comment by markus-wa** [comment]
I understand this can be problematic but I'm not sure this is something we will fix - that's the order the events are in the demos, so they are fired in this order.

**Comment by sirherrbatka** [comment]
What I personally do is store those events in a buffer, and handle them after parsing the frame. I had to do this because of weapon fire events popping up after player hurt events.
