### ISSUE TITLE
Nil property leading to panic

### ISSUE THREAD

**Issue by Julien2313** [markus-wa/demoinfocs-golang#462]
**Describe the bug**
When getting the position of the players on the event FrameDone, I get a panic in the function `func (e *Entity) Position() r3.Vector` when calling `cellXProp.Value().S2UInt64()` because `cellXProp` is nil.

**To Reproduce**
All the demo I tried have the issue, but you can also try on this BO3 : https://www.hltv.org/matches/2367258/g2-vs-ence-iem-sydney-2023

Code:
```go
func main() {
	reader, err := os.Open("g2-vs-ence-m1-ancient.dem")
	if err != nil {
		panic(err)
	}

	demoUnzippedReader := bufio.NewReader(reader)
	demoInfocsParser := demoinfocs.NewParser(demoUnzippedReader)
	demoInfocsParser.RegisterEventHandler(func(e events.FrameDone) {
		gs := demoInfocsParser.GameState()
		if gs.IsWarmupPeriod() || gs.IsFreezetimePeriod() {
			return
		}
		fmt.Println("tick: ", demoInfocsParser.GameState().IngameTick())

		for _, player := range demoInfocsParser.GameState().Participants().Playing() {
			if player == nil || player.Entity == nil {
				continue
			}

			fmt.Println(player.Entity.Position())
		}
	})

	if err := demoInfocsParser.ParseToEnd(); err != nil {
		panic(err)
	}
}
```

**Expected behavior**
Not to panic. Returning an error could be nice, but also could break a lot of code base.I don't know what could be the best value returned to be seen as invalide...

**Library version**
4.0.0-beta.5

**Comment by markus-wa** [comment]
Thanks for the report - I think `NaN,NaN,NaN` would be a reasonable return value.

If you have the time to look into it PRs are welcome of course!

**Comment by Julien2313** [comment]
But, I feel like there might be a weird bug, because it doesn't append everytime I run the code at the same tick... And for that, I'm unqualified to search deep in the code :(

**Comment by markus-wa** [comment]
Hmm, maybe a race condition? 🤔

**Comment by akiver** [comment]
Hi @Julien2313! 

I think it's because `player.Entity.Position()` tries to get the position from the player's controller but in CS2 the position is in the player's pawn entity.
You should try with `player.Position()` instead.

**Comment by markus-wa** [comment]
closing this - feel free to reopen if there's still an issue
