### ISSUE TITLE
[CS2] Inferno.Fires().ConvexHull2D() throwing "panic: property 'm_fireXDelta.0000' not found"

### ISSUE THREAD

**Issue by DemElvis** [markus-wa/demoinfocs-golang#465]
**Describe the bug**
"panic: property 'm_fireXDelta.0000' not found" is thrown, when accessing Inferno.Fires().ConvexHull2D() in InfernoExpired event handler

**To Reproduce**
reproducible with recent faceit demos (exmaple from kennyS demo): https://storage.googleapis.com/demos-europe-west2.faceit-cdn.net/cs2/1-b262129e-114e-4cfa-8125-e9881edb3cb7-1-1.dem.gz

accessing in InfernoExpired event handler
Code:
```go
p.RegisterEventHandler(func(e events.InfernoExpired) {
    infernoHulls[e.Inferno.UniqueID()] = e.Inferno.Fires().ConvexHull2D()
})
```

**Expected behavior**
function returning 2D hull of Inferno.

**Library version**
v4.0.0-beta.5

**Additional context**
Works with older CS2 demos and CS2-beta demos.

**Comment by BestAwperEver** [comment]
Fixed in #453
