### ISSUE TITLE
Question: how to get time elapsed since round start?

### ISSUE THREAD

**Issue by ysomad** [markus-wa/demoinfocs-golang#471]
Hello! I'm tracking round state between RoundStart and RoundEnd events. Is there any way to get ingame time of round?

**Comment by markus-wa** [comment]
Hi - you can store `x := parser.CurrentTime()` at `RoundStart` and then do `parser.CurrentTime() - x` at `RoundEnd` :slightly_smiling_face: 

Feel free to reopen if this doesn't answer the question completely
