### ISSUE TITLE
Player equipment incorrect

### ISSUE THREAD

**Issue by micvbang** [markus-wa/demoinfocs-golang#472]
I'm currently investigating players having incorrect equipment reported by both `GameState().Weapons()` and `GameState(),Participants().Playing() -> player.Weapons()`.
I've got a few demos where this is incorrect. I've specifically looked at inferno for this match: https://www.hltv.org/matches/2367571/virtuspro-vs-ecstatic-cct-east-europe-series-3

It happens during bomb time in round 8:

Second 1183.69 "Nodios" has knife, glock, ak47, **flash** but `Player.Weapons()` reports it as knife, glock, ak47, **smoke** (incorrectly reporting smoke instead of flash)

Then "Nodios" picks drops his glock and picks up a desert eagle. 

Second 1185.09 "Nodios" has knife, desert eagle, ak47, flash but `Player.Weapons()` reports it as knife, desert eagle, smoke (missing ak47 and incorrectly reporting smoke instead of flash).

Side note:
For some reason the demo crashes when I play it in the CS2 demo viewer, but I found it on this stream: https://www.twitch.tv/videos/1960641122?t=11h56m08s

**Library version**
master @ aa1b925

**Comment by markus-wa** [comment]
Interesting 🤔 - is #450 related?

**Comment by micvbang** [comment]
Just skimmed it -- that seems very likely!

**Comment by markus-wa** [comment]
@micvbang  would you be able to check if #477 fixes the issue?

**Comment by micvbang** [comment]
Hmm.. For the demo I'm currently looking at, this does not seem to help.
For once I've found a demo that I can actually play in the CS2 demoviewer. It's about a month old, so I guess that has to be taken into consideration when using it for debugging.

But: I'm looking at nuke from this match: https://www.hltv.org/matches/2367264/complexity-vs-faze-iem-sydney-2023
Where karrigan in the first 15 seconds buys a flash, a molly, and then another flash.

With your changes I'm only seeing the molly in his inventory. With the changes I'm currently doing myself, I'm only seeing the flash

**Comment by micvbang** [comment]
I think I've actually got the "right" equipment now, but the equipment type of the Molotov isn't being updated. You can give my WIP a look here: https://github.com/micvbang/demoinfocs-golang/tree/micvbang/simplify-weapon-inventory

**Comment by markus-wa** [comment]
I've pushed another attempt - can you take another look? still not completely sure though :sweat:

**Comment by markus-wa** [comment]
but yeah, I think your solution might be more reliable long term

**Comment by micvbang** [comment]
Yeah - unfortunately that also doesn't work entirely. It looks like him _buying_ the grenades works, but they don't disappear when he throws them :'(

Here's a list of outputs to expect for karrigan in the demo mentioned above:
- 11    sec: buy flash
- 11.5 sec: buy molly
- 12    sec: buy flash
- 29.5 sec: throw flash
- 32    sec: throw molly
- 34    sec: throw flash

In your most recent commit, I can't see that he throws the grenades

**Comment by micvbang** [comment]
Except that I can't figure out how to determine how many flashes a player has, my branch seems to handle the above equipment for karrigan correctly. It's by no means correct for all players, but I think it's a step in the right direction

**Comment by markus-wa** [comment]
For me, that branch never seems to show the molly karrigan buys though :cry:

**Comment by markus-wa** [comment]
Ok yeah I think it works - first I thought there was another bug, but I think it looks pretty good indeed, my testing was just bad.

Can you open a PR?

**Comment by micvbang** [comment]
Give it a try now -- it's definitely starting to look like something!

I'll post a PR as well

**Comment by markus-wa** [comment]
fixed in v4.0.0
