### ISSUE TITLE
Broken after last update, missing e.Killer/e.Victim for events.Kill

### ISSUE THREAD

**Issue by Run1e** [markus-wa/demoinfocs-golang#476]
**Describe the bug**
As of the last update (as far as I can tell), matchmaking/premier demos have broken `events.Kill` events, where `e.Killer` and `e.Victim` is `nil`.

**To Reproduce**
Affected demo: http://replay125.valve.net/730/003651143327438340178_0672844519.dem.bz2

Simply set up a handler for the `events.Kill` event and check `e.Victim` or `e.Killer`

**Library version**
v4.0.0-beta.5

**Comment by akiver** [comment]
Hi, it should be fixed with https://github.com/markus-wa/demoinfocs-golang/pull/475
