### ISSUE TITLE
How to uniquely identify demo?

### ISSUE THREAD

**Issue by ysomad** [markus-wa/demoinfocs-golang#479]
Greetings!

I'm creating a system where identifying every uploaded demo as unique md5 uuid generated using fields from header. Since demo header kinda deprecated and returns all default values which values you can recommend to use for this kind of method of identifying demo? Maybe should I use some stats and user info as md5?

would be great if there such info before parsing whole demo.

https://github.com/markus-wa/demoinfocs-golang/issues/435

**Comment by micvbang** [comment]
Just hash the demo file itself :)
