### ISSUE TITLE
Parsing very slow due to Entity.BindPosition()

### ISSUE THREAD

**Issue by markus-wa** [markus-wa/demoinfocs-golang#48]
**Describe the bug**
#44 introduced `Entity.BindPosition()` for players which the parser uses internally to keep track of the players positions. This function performs very badly since it calls `Entity.FindProperty()` twice on every update.

![](https://user-images.githubusercontent.com/5138316/45520623-7a646500-b7ba-11e8-8a19-58dfe4dfafa9.png)

```
     10ms       10ms    198:func (e *Entity) positionPlayer() r3.Vector {
     110ms     42.73s    199:   xy := e.FindProperty(propVecOriginPlayerXY).value.VectorVal
      10ms     35.67s    200:   z := float64(e.FindProperty(propVecOriginPlayerZ).value.FloatVal)
      90ms       90ms    201:   return r3.Vector{
         .          .    202:           X: xy.X,
         .          .    203:           Y: xy.Y,
         .          .    204:           Z: z,
         .          .    205:   }
         .          .    206:}
```

**To Reproduce**

```
git checkout 95349a9
# Fast
go test -run _NONE_ -bench .

git checkout 4b006c8
# Slow
go test -run _NONE_ -bench .
```

**Expected behavior**
As fast as before merging #44

**Library version**
4b006c8

**Additional context**
Discovered by @micvbang

**Comment by micvbang** [comment]
I can confirm that your fix in #49 gets the performance back to normal.

Good job!
