### ISSUE TITLE
Player vanishes from connected players list, but continues to be active in the game.

### ISSUE THREAD

**Issue by sirherrbatka** [markus-wa/demoinfocs-golang#481]
**Describe the bug**
This demo https://antiochia.duckdns.org/index.php/s/ciywmyfkXe9jjxg displays curious behavior for player of steam id 76561198417781255 Namely after tick 20189 player is no longer on the connected player list, however, he also dies multiple times after this time mark, including tick 136067.
                                                                       
**To Reproduce**
https://antiochia.duckdns.org/index.php/s/ciywmyfkXe9jjxg (faceit demo)

**Expected behavior**
I reckon this is likely to be an issue with reconnected players handling.

**Library version**
v4.0.0

**Comment by JuhaKiili** [comment]
I'm seeing the same behavior on fluxo-vs-imperial-cbcs-invitational-2023 Inferno.

From round 20 onward, two players [CT]VINI and [CT]HEN1 are no longer connected, but remain active in the game.

Demo available here: https://www.hltv.org/matches/2368293/fluxo-vs-imperial-cbcs-invitational-2023

```
Round 19
PARTICIPANTS:
PLAYER Gamers Club TV (0) Team: 0 Connected: false
PLAYER [CT]decenty (76561198307171910) Team: 3 Connected: true
PLAYER [CT]VINI (76561197996370184) Team: 3 Connected: true
PLAYER [T]Lucaozy (76561198157388473) Team: 2 Connected: true
PLAYER [T]chay (76561198251931752) Team: 2 Connected: true
PLAYER Gamers Club TV (0) Team: 0 Connected: false
PLAYER [T]zevy (76561199422519262) Team: 2 Connected: true
PLAYER [CT]noway (76561198800209567) Team: 3 Connected: true
PLAYER [CT]HEN1 (76561198018027263) Team: 3 Connected: true
PLAYER [T]PKL (76561198025578864) Team: 2 Connected: true
PLAYER [CT]felps (76561197983031494) Team: 3 Connected: true
PLAYER [T]vsm (76561198011732823) Team: 2 Connected: true

Round 20
PARTICIPANTS:
PLAYER [CT]felps (76561197983031494) Team: 3 Connected: true
PLAYER [T]vsm (76561198011732823) Team: 2 Connected: true
PLAYER Gamers Club TV (0) Team: 0 Connected: false
PLAYER [T]zevy (76561199422519262) Team: 2 Connected: true
PLAYER [CT]noway (76561198800209567) Team: 3 Connected: true
PLAYER [CT]HEN1 (76561198018027263) Team: 3 Connected: false
PLAYER [T]PKL (76561198025578864) Team: 2 Connected: true
PLAYER Gamers Club TV (0) Team: 0 Connected: false
PLAYER [CT]decenty (76561198307171910) Team: 3 Connected: true
PLAYER [CT]VINI (76561197996370184) Team: 3 Connected: false
PLAYER [T]Lucaozy (76561198157388473) Team: 2 Connected: true
PLAYER [T]chay (76561198251931752) Team: 2 Connected: true
```

**Comment by markus-wa** [comment]
Thanks for the report @sirherrbatka  @JuhaKiili - can you please post your code :eyes:
