### ISSUE TITLE
Missing player in TeamState.Members()

### ISSUE THREAD

**Issue by CapekM** [markus-wa/demoinfocs-golang#492]
**Describe the bug**
I was parsing demofiles from HLTV and noticed that `parser.GameState().TeamTerrorists().Members()` does not return all players, but all players are in the `parser.GameState().Participants().All()`.
When I looked into the func `(ptcp participants) TeamMembers(team common.Team)` there were only 9 participants, but the `parser.GameState().Participants().All()` is returning 13 players and all right ones are there.
When I looked into the `p.parser.GameState().Participants().Connected/Playing()` there are the 9 players. I'm not sure if it's a problem with data or the parser, since I'm not much proficient with this library.
Thanks for any reply.

**To Reproduce**
For example:
- 1st map of https://www.hltv.org/matches/2368503/virtuspro-vs-spirit-betboom-dacha-2023
    - After 3rd round player _mir_
- Both maps of https://www.hltv.org/matches/2368419/space-vs-alternate-attax-cct-2023-online-finals-5
    - 1st map after 5th round player _fozil_
    - 2nd map after 4th round player _PerX_

**Library version**
v4.0.0

**Comment by kartol** [comment]
There seems to be an issue with disconnecting and reconnecting.
When "mir" disconnects and later reconnects he is still marked as disconnected
```
Round finished: winnerSide=T  ; size=5:5
Round finished: winnerSide=T  ; size=5:5
Round finished: winnerSide=T  ; size=5:5
player mir disconnected
player mir connected
Round finished: winnerSide=T  ; size=5:4
Round finished: winnerSide=T  ; size=5:4
```

Probably there should be some additional handling for this situation in the playerConnect method
analogically to the disconnecting
https://github.com/markus-wa/demoinfocs-golang/blob/5543f4b8241a8a525bfa9ebe2ece95b0323746fb/pkg/demoinfocs/game_events.go#L655-L662
inside the playerDisconnect method?

**Comment by markus-wa** [comment]
Sorry I'm currently a bit slow at getting back on issues - this definitely seems like an important thing to fix.
I'm not sure about `m_aPlayers` - what about using `m_iTeamNum` on the player pawns?

I don't know how quickly I'll be able to get to this so MRs are very welcome.
Happy to go with the `m_aPlayers` path if that seems to be  the most reliable

**Comment by micvbang** [comment]
> Sorry I'm currently a bit slow at getting back on issues - this definitely seems like an important thing to fix. I'm not sure about `m_aPlayers` - what about using `m_iTeamNum` on the player pawns?
> 
> I don't know how quickly I'll be able to get to this so MRs are very welcome. Happy to go with the `m_aPlayers` path if that seems to be the most reliable

This looks relevant: https://github.com/akiver/cs-demo-analyzer/blob/6c642144c19a40277e3690a3d6fc42e313f8752e/pkg/api/ebot.go#L71

**Comment by akiver** [comment]
could you try with this branch please? https://github.com/markus-wa/demoinfocs-golang/pull/499

**Comment by markus-wa** [comment]
I will be closing this for now, feel free to reopen if the issue persists with `v4.0.2`
