### ISSUE TITLE
Events are not firing in CS2 GOTV demo

### ISSUE THREAD

**Issue by milkywayfarer** [markus-wa/demoinfocs-golang#498]
**Describe the bug**
When parsing a demo that was automatically recorded with `tv_autorecord` from a local server, events are not firing at all.

**To Reproduce**
https://cloud.mway.club/s/AQDWyN6gr23GMfj

Code:
```go
f, err := os.Open("...")
if err != nil {
  log.Panic("failed to open demo file: ", err)
}
defer f.Close()

p := dem.NewParser(f)
defer p.Close()

p.RegisterEventHandler(func(event events.Kill) {
  fmt.Println("kill")
})

_, err = p.ParseHeader()
if err != nil {
  panic(err)
}

err = p.ParseToEnd()
if err != nil {
  panic(err)
}
```

**Expected behavior**
Expected events to fire for a specific enum value (Kill, PlayerJump, WeaponFire etc). This demo *works* in CS Demo Manager (outputs wrong info and includes warmup, but all the necessary events fire, including the ones that I specified) and it uses a default configuration for the parser, as do I.

**Library version**
v4/v4.0.1

**Additional context**
Developing and debugging using dlv and Visual Studio Code on latest MacOS.

**Comment by milkywayfarer** [comment]
P.S. demo link has died, there's a new one https://cloud.mway.club/s/Gp7R5nZ52LsKmCB

**Comment by markus-wa** [comment]
works as expected for me 

![image](https://github.com/markus-wa/demoinfocs-golang/assets/5138316/3be681c7-0684-487a-982f-e6265e57451b)

please post the full code including imports and main function so I can just copy paste it into a `main.go` and run it - right now I can't reproduce it with your code sample.

**Comment by markus-wa** [comment]
I did `go run ./examples/print-events/print_events.go -demo ~/Downloads/auto-20231228-1843-de_inferno-milkywayfarer_.dem` on `master`

**Comment by milkywayfarer** [comment]
This is a full listing:

```
package main

import (
	"fmt"
	"log"
	"os"

	"github.com/markus-wa/demoinfocs-golang/events"
	dem "github.com/markus-wa/demoinfocs-golang/v4/pkg/demoinfocs"
)

func main() {
	f, err := os.Open("/Users/milkywayfarer_/Downloads/auto-20231228-1843-de_inferno-milkywayfarer_.dem")
	if err != nil {
		log.Panic("failed to open demo file: ", err)
	}
	defer f.Close()

	p := dem.NewParser(f)
	defer p.Close()

	p.RegisterEventHandler(func(event events.Kill) {
		fmt.Println("pls write this I beg")
	})

	_, err = p.ParseHeader()
	if err != nil {
		panic(err)
	}

	err = p.ParseToEnd()
	if err != nil {
		panic(err)
	}
}
```

`fmt` never prints, breakpoint that I set on it is never hit, process just returns with code 0

**Comment by markus-wa** [comment]
Your import section is using an old version of the `events` pkg.

```go
import (
	"fmt"
	"log"
	"os"

	"github.com/markus-wa/demoinfocs-golang/events" // FIX: should be "github.com/markus-wa/demoinfocs-golang/v4/pkg/demoinfocs/events"
	dem "github.com/markus-wa/demoinfocs-golang/v4/pkg/demoinfocs"
)
```
