### ISSUE TITLE
Parser crashes after CS2 update 2/6/2024

### ISSUE THREAD

**Issue by JuhaKiili** [markus-wa/demoinfocs-golang#501]
**Describe the bug**
Parsing fails with `Fatal error: runtime: out of memory` for a demo after CS2 update 2/6/2024

**To Reproduce**
https://www.hltv.org/matches/2369635/sprout-vs-metizport-yalla-compass-spring-2024-contenders | Vertigo
https://www.hltv.org/matches/2369649/ecstatic-vs-tsm-european-pro-league-season-13 | Anubis

Code:
```go
package main

import (
	"fmt"
	"os"

	ex "github.com/markus-wa/demoinfocs-golang/v4/examples"
	demoinfocs "github.com/markus-wa/demoinfocs-golang/v4/pkg/demoinfocs"
	events "github.com/markus-wa/demoinfocs-golang/v4/pkg/demoinfocs/events"
)

// Run like this: go run test.go -demo /path/to/demo.dem
func main() {
	f, err := os.Open(ex.DemoPathFromArgs())
	checkError(err)
	defer f.Close()
	p := demoinfocs.NewParser(f)
	defer p.Close()

	p.RegisterEventHandler(func(e events.RoundEnd) {
		gs := p.GameState()
		fmt.Printf("Round %d parsed\n", gs.TotalRoundsPlayed())
	})

	err = p.ParseToEnd()
	checkError(err)
}

func checkError(err error) {
	if err != nil {
		panic(err)
	}
}
```
**Current behavior**
The parsing fails with `Fatal error: runtime: out of memory`

**Expected behavior**
The demos should parse without error and print out all the round numbers

**Library version**
Latest from master (e98a3fa02faa46032944acc23c3b0c0a6bf5be5d)

**Comment by makindotcc** [comment]
I can say in my parser reader gets corrupted after reading entities, especially after reading ``m_flSimulationTime``. I think it is similar case here. Probably this field decoder format has been changed.

**Comment by markus-wa** [comment]
See also https://github.com/markus-wa/demoinfocs-golang/issues/502 & https://github.com/markus-wa/demoinfocs-golang/issues/503

The underlying issue is likely the same - I will close the others in favour of this one

**Comment by spheenik** [comment]
My hunch is that it has something to do with this:
```proto
message ProtoFlattenedSerializerField_t {
	message polymorphic_field_t {
		optional int32 polymorphic_field_serializer_name_sym = 1;
		optional int32 polymorphic_field_serializer_version = 2;
	}

	optional int32 var_type_sym = 1;
	optional int32 var_name_sym = 2;
	optional int32 bit_count = 3;
	optional float low_value = 4;
	optional float high_value = 5;
	optional int32 encode_flags = 6;
	optional int32 field_serializer_name_sym = 7;
	optional int32 field_serializer_version = 8;
	optional int32 send_node_sym = 9;
	optional int32 var_encoder_sym = 10;
	repeated .ProtoFlattenedSerializerField_t.polymorphic_field_t polymorphic_types = 11;
}
```

Polymorphic fields are there for 8 months now, and in my parser (clarity) I made a weird fix for a pointer field which had a few bits I could not understand.

From a first glance, you also do not support polymorphic fields.

Now they start to use it, and this breaks it.

**Comment by thecatontheflat** [comment]
I'm not sure if it helps, but will leave it here.
I noticed that each packet (after the first 2, which are identical for whatever reason) start from the same sequence.

It looks like each packet is now prefixed with some (repeated?) data?

```
<Buffer 80 d2 01 00 00 ae 29 c0 93 a5 00 00 d6 f0 c0 46 b1 0d 6b 63 88 8d 62 da 95 9b d6 c0 3e b8 80 04 09 b1 0b 00 a8 90 8a 40 40 e8 d0 d2 dc d6 ca e4 00 28 ... 38557 more bytes>
<Buffer 80 d2 01 00 00 ae 29 c0 93 a5 00 00 d6 f0 c0 46 b1 0d 6b 63 88 8d 62 da 95 9b d6 c0 3e b8 80 04 09 b1 0b 00 a8 90 8a 40 40 e8 d0 d2 dc d6 ca e4 00 28 ... 38557 more bytes>
<Buffer 00 03 18 80 01 18 80 01 18 80 01 18 80 01 18 80 09 78 ab 99 76 10 95 b5 bd 49 95 8d bd c9 91 95 c9 01 4c c3 00 03 0c 30 c0 00 03 0c 30 c0 00 03 0c 30 ... 888 more bytes>
<Buffer 00 03 18 80 01 18 80 01 18 80 01 18 80 01 18 80 09 78 9d 76 4c c3 00 03 0c 30 c0 00 03 0c 30 c0 00 03 0c 30 c0 00 03 0c 30 c0 00 03 0c 30 c0 00 0f 0c ... 853 more bytes>
<Buffer 00 03 18 80 01 18 80 01 18 80 01 18 80 01 18 80 09 78 a1 76 4c c3 00 03 0c 30 c0 00 03 0c 30 c0 00 03 0c 30 c0 00 03 0c 30 c0 00 03 0c 30 c0 00 0f 0c ... 790 more bytes>
<Buffer 00 03 18 80 01 18 80 01 18 80 01 18 80 01 18 80 09 78 a5 76 4c c3 00 03 0c 30 c0 00 03 0c 30 c0 00 03 0c 30 c0 00 03 0c 30 c0 00 03 0c 30 c0 00 0f 0c ... 777 more bytes>
<Buffer 00 03 18 80 01 18 80 01 18 80 01 18 80 01 18 80 09 78 a9 76 4c c3 00 03 0c 30 c0 00 03 0c 30 c0 00 03 0c 30 c0 00 03 0c 30 c0 00 03 0c 30 c0 00 0f 0c ... 842 more bytes>
<Buffer 00 03 18 80 01 18 80 01 18 80 01 18 80 01 18 80 09 78 ad 76 4c c3 00 03 0c 30 c0 00 03 0c 30 c0 00 03 0c 30 c0 00 03 0c 30 c0 00 03 0c 30 c0 00 0f 0c ... 792 more bytes>
<Buffer 00 03 18 80 01 18 80 01 18 80 01 18 80 01 18 80 09 78 b1 76 4c c3 00 03 0c 30 c0 00 03 0c 30 c0 00 03 0c 30 c0 00 03 0c 30 c0 00 03 0c 30 c0 00 0f 0c ... 822 more bytes>
<Buffer 00 03 18 80 01 18 80 01 18 80 01 18 80 01 18 80 09 78 b5 76 4c c3 00 03 0c 30 c0 00 03 0c 30 c0 00 03 0c 30 c0 00 03 0c 30 c0 00 03 0c 30 c0 00 0f 0c ... 778 more bytes>
<Buffer 00 03 18 80 01 18 80 01 18 80 01 18 80 01 18 80 09 78 b9 76 4c c3 00 03 0c 30 c0 00 03 0c 30 c0 00 03 0c 30 c0 00 03 0c 30 c0 00 03 0c 30 c0 00 0f 0c ... 763 more bytes>
<Buffer 00 03 18 80 01 18 80 01 18 80 01 18 80 01 18 80 09 78 bd 76 4c c3 00 03 0c 30 c0 00 03 0c 30 c0 00 03 0c 30 c0 00 03 0c 30 c0 00 03 0c 30 c0 00 0f 0c ... 758 more bytes>
<Buffer 00 03 18 80 01 18 80 01 18 80 01 18 80 01 18 80 09 78 c1 76 4c c3 00 03 0c 30 c0 00 03 0c 30 c0 00 03 0c 30 c0 00 03 0c 30 c0 00 03 0c 30 c0 00 0f 0c ... 751 more bytes>
<Buffer 00 03 18 80 01 18 80 01 18 80 01 18 80 01 18 80 09 78 c5 76 4c c3 00 03 0c 30 c0 00 03 0c 30 c0 00 03 0c 30 c0 00 03 0c 30 c0 00 03 0c 30 c0 00 0f 0c ... 756 more bytes>
<Buffer 00 03 18 80 01 18 80 01 18 80 01 18 80 01 18 80 09 78 c9 76 4c c3 00 03 0c 30 c0 00 03 0c 30 c0 00 03 0c 30 c0 00 03 0c 30 c0 00 03 0c 30 c0 00 0f 0c ... 760 more bytes>
<Buffer 00 03 18 80 01 18 80 01 18 80 01 18 80 01 18 80 09 78 cd 76 4c c3 00 03 0c 30 c0 00 03 0c 30 c0 00 03 0c 30 c0 00 03 0c 30 c0 00 03 0c 30 c0 00 0f 0c ... 704 more bytes>
<Buffer 00 03 18 80 01 18 80 01 18 80 01 18 80 01 18 80 09 78 d1 76 4c c3 00 03 0c 30 c0 00 03 0c 30 c0 00 03 0c 30 c0 00 03 0c 30 c0 00 03 0c 30 c0 00 0f 0c ... 733 more bytes>
<Buffer 00 03 18 80 01 18 80 01 18 80 01 18 80 01 18 80 09 78 d5 76 4c c3 00 03 0c 30 c0 00 03 0c 30 c0 00 03 0c 30 c0 00 03 0c 30 c0 00 03 0c 30 c0 00 0f 0c ... 704 more bytes>
<Buffer 00 03 18 80 01 18 80 01 18 80 01 18 80 01 18 80 09 78 d9 76 4c c3 00 03 0c 30 c0 00 03 0c 30 c0 00 03 0c 30 c0 00 03 0c 30 c0 00 03 0c 30 c0 00 0f 0c ... 843 more bytes>
<Buffer 00 03 18 80 01 18 80 01 18 80 01 18 80 01 18 80 09 78 dd 76 4c c3 00 03 0c 30 c0 00 03 0c 30 c0 00 03 0c 30 c0 00 03 0c 30 c0 00 03 0c 30 c0 00 0f 0c ... 781 more bytes>
```

**Comment by markus-wa** [comment]
@spheenik that's a very good observation - I remember thinking this could come back to bite us...

**Comment by thecatontheflat** [comment]
@markus-wa they do seem to have more variability

**Comment by spheenik** [comment]
Some research results:

- polymorphic pointers are indeed a thing. There is one entity in the replay I have here `CCSGameModeRules`, which uses it
- When you decode a polymorphic pointer (if it is enabled, you can read a ubitvar to get the type it is referencing
- still does not parse however
- `var_serializer_sym` seems completely unused
- there is `pvs_view_bits` on `CSVCMsg_PacketEntities` set to 1, maybe this correlates with the "constant" data @thecatontheflat saw?

**Comment by spheenik** [comment]
To add: something goes wrong immediately when parsing `CEntityIdentity*`.

**Comment by makindotcc** [comment]
There are new PVS related entity update flags:
if two first bits (cmd == 0) and packet.has_pvs_vis_bits is true then we need to read two next bits:
https://github.com/markus-wa/demoinfocs-golang/blob/e4ab22e08840c03c21b5436ab69efbaea8948c3c/pkg/demoinfocs/sendtables2/entity.go#L479
```go
		cmd = r.readBits(2)
		if cmd == 0 && packet.HasPvsVisBits {
			cmd = r.readBits(2) << 3
		}
		if (cmd & 0x08) == 8 {
			continue
		}
		if cmd&0x01 == 0 {
			if cmd&0x02 != 0 {
```
Cs2 (version 13989) engine2.dll binary:
![](https://github.com/markus-wa/demoinfocs-golang/assets/9150636/10dfefc9-e0da-4438-9ea0-776887a0179c)
Function above is for used for latest demos, it may be different for older ones (e.g. for backwards compatibility)
![](https://github.com/markus-wa/demoinfocs-golang/assets/9150636/8d8a29ad-452a-4440-a5f4-320dfbda0d64)
![](https://github.com/markus-wa/demoinfocs-golang/assets/9150636/956b859e-4e52-4f26-80b0-e4a5d1b6a1bb)

Thanks for everyone involved ❤️

**Comment by rchh** [comment]
Great job :)

**Comment by spheenik** [comment]
Well done, @makindotcc!

**Comment by spheenik** [comment]
And regarding older demos: They do not have the flag, so as required, the two extra bits are never read, and they should work.
What is their meaning though?
Right now, they are just thrown away.
For the sake of a correct implementation, I would like to replicate what they do...

**Comment by makindotcc** [comment]
I have added source code link where they are handled in pull request. Cs2 seems to have similar functionality and I didnt notice any change compared to the pre-update version of engine2.dll. It is just some sync thing, if i didnt miss anything then it never touches entity buffer. Handling this additional updateFlag is in the function from last image (you can find it in binary by searching string from img) in engine2.dll.

**Comment by markus-wa** [comment]
Thanks everyone and especially @makindotcc :heart: 

Do we think this issue is completely resolved then? If so I will close this :slightly_smiling_face:

**Comment by markus-wa** [comment]
Good call @spheenik - I've created https://github.com/markus-wa/demoinfocs-golang/issues/506 and will close this one for now
