### ISSUE TITLE
Parsing is crashing with signal: killed (CS2 update 2/6/2024)

### ISSUE THREAD

**Issue by JuhaKiili** [markus-wa/demoinfocs-golang#502]
**Describe the bug**
Parsing fails with `signal: killed` for a demo after CS2 update 2/6/2024

**To Reproduce**
https://www.hltv.org/matches/2369635/sprout-vs-metizport-yalla-compass-spring-2024-contenders | Mirage
https://www.hltv.org/matches/2369634/endpoint-vs-permitta-yalla-compass-spring-2024-contenders | Overpass

Code:
```go
package main

import (
	"fmt"
	"os"

	ex "github.com/markus-wa/demoinfocs-golang/v4/examples"
	demoinfocs "github.com/markus-wa/demoinfocs-golang/v4/pkg/demoinfocs"
	events "github.com/markus-wa/demoinfocs-golang/v4/pkg/demoinfocs/events"
)

// Run like this: go run test.go -demo /path/to/demo.dem
func main() {
	f, err := os.Open(ex.DemoPathFromArgs())
	checkError(err)
	defer f.Close()
	p := demoinfocs.NewParser(f)
	defer p.Close()

	p.RegisterEventHandler(func(e events.RoundEnd) {
		gs := p.GameState()
		fmt.Printf("Round %d parsed\n", gs.TotalRoundsPlayed())
	})

	err = p.ParseToEnd()
	checkError(err)
}

func checkError(err error) {
	if err != nil {
		panic(err)
	}
}
```
**Current behavior**
Parsing fails with `signal: killed`

**Expected behavior**
The demos should parse without error and print out all the round numbers

**Library version**
Latest from master (https://github.com/markus-wa/demoinfocs-golang/commit/e98a3fa02faa46032944acc23c3b0c0a6bf5be5d)

**Comment by markus-wa** [comment]
Closing as duplicate in favour of https://github.com/markus-wa/demoinfocs-golang/issues/503 - the underlying cause is likely the same
