### ISSUE TITLE
panic: serializer CWorld: field path has no field (CS2 update 2/6/2024) 

### ISSUE THREAD

**Issue by JuhaKiili** [markus-wa/demoinfocs-golang#503]
**Describe the bug**
Parsing fails with `panic: serializer CWorld: field path has no field` for a demo after CS2 update 2/6/2024

**To Reproduce**
https://beta.faceit.com/en/cs2/room/1-41e08139-b7da-474a-b8d3-f25f5331532b
https://www.faceit.com/ru/cs2/room/1-1f941f0f-d7c7-49dd-b7f1-a8ecd18160ae

Code:
```go
package main

import (
	"fmt"
	"os"

	ex "github.com/markus-wa/demoinfocs-golang/v4/examples"
	demoinfocs "github.com/markus-wa/demoinfocs-golang/v4/pkg/demoinfocs"
	events "github.com/markus-wa/demoinfocs-golang/v4/pkg/demoinfocs/events"
)

// Run like this: go run test.go -demo /path/to/demo.dem
func main() {
	f, err := os.Open(ex.DemoPathFromArgs())
	checkError(err)
	defer f.Close()
	p := demoinfocs.NewParser(f)
	defer p.Close()

	p.RegisterEventHandler(func(e events.RoundEnd) {
		gs := p.GameState()
		fmt.Printf("Round %d parsed\n", gs.TotalRoundsPlayed())
	})

	err = p.ParseToEnd()
	checkError(err)
}

func checkError(err error) {
	if err != nil {
		panic(err)
	}
}
```

**Current behavior**
Parsing fails with `panic: serializer CWorld: field path has no field`

**Expected behavior**
The demos should parse without error and print out all the round numbers

**Library version**
Latest from master (https://github.com/markus-wa/demoinfocs-golang/commit/e98a3fa02faa46032944acc23c3b0c0a6bf5be5d)

**Comment by markus-wa** [comment]
See also https://github.com/markus-wa/demoinfocs-golang/issues/502 & https://github.com/markus-wa/demoinfocs-golang/issues/501

The underlying issue is likely the same - I will close the others in favour of this one
