### ISSUE TITLE
unknown equipment with index 526

### ISSUE THREAD

**Issue by Robbejj** [markus-wa/demoinfocs-golang#517]
**Describe the bug**
`unknown equipment with index 526`
messages spread randomly across the match when parsing for events.
[6069107.txt](https://github.com/markus-wa/demoinfocs-golang/files/14484059/6069107.txt)

**To Reproduce**
https://esportal.com/en/match/6069107

**Library version**
v4.0.5

**Additional context**
Does not happen in every demo.

**Comment by remy56k** [comment]
I confirm this issue ! Any hint ?

**Comment by markus-wa** [comment]
@Robbejj @remy56k can you check if this is still a problem with the latest versions?

**Comment by remy56k** [comment]
The project was abandoned, so I can not test anymore the problematic demo, sorry.

**Comment by markus-wa** [comment]
No worries, I will close this for now then :smile:
