### ISSUE TITLE
Possible panic since v4.1.0

### ISSUE THREAD

**Issue by akiver** [markus-wa/demoinfocs-golang#522]
**Describe the bug**

Since the v4.1.0 that introduced POV support for CS2 demos, many fields may be `nil` and cause panic for consumers.

**To Reproduce**

Git clone the [CS demo analyzer repo](https://github.com/akiver/cs-demo-analyzer) and run the [tests](https://github.com/akiver/cs-demo-analyzer#tests) in verbose mode (`make test-verbose`).

You will have this [output](https://github.com/akiver/cs-demo-analyzer/pull/9/checks).
There is a panic and many warnings about fields being `nil` - it was not the case before v4.1.0.

**Expected behavior**

No panic or `nil` fields.

**Library version**
v4.1.0

**Additional context**

I didn't dig into it yet, maybe we should revert commits and release a v4.2.0 until it's resolved WDYT @markus-wa ?

**Comment by markus-wa** [comment]
I think we should fix-forward on this. I do appreciate this can be a problem, but POV support is a valuable feature and we should keep supporting it while fixing all the problems with it.
