### ISSUE TITLE
Unexpected `EqUnknown`

### ISSUE THREAD

**Issue by micvbang** [markus-wa/demoinfocs-golang#53]
**Describe the bug**
Hey!

I unfortunately haven't had time to investigate this myself. I thought that I'd report it so that I don't forget :slightly_smiling_face: 

I've found that in some demos I get `EqUnknown` (i.e. uninitialized) for some player's weapons.

My gut tells me that this happens in the weapons mapping in `datatables.go`, but I have nothing else to base this on.

**To Reproduce**
Run the following code on dust2 from this match: https://www.hltv.org/matches/2322780/liquid-vs-astralis-esl-pro-league-season-7-finals

In round 2 we see that `device` has bought a scout that is being returned as `EqUnknown`.

Code:
```go
package main

import (
	"log"
	"os"

	"github.com/markus-wa/demoinfocs-golang/common"

	dem "github.com/markus-wa/demoinfocs-golang"
	"github.com/markus-wa/demoinfocs-golang/events"
	ex "github.com/markus-wa/demoinfocs-golang/examples"
)

func main() {
	f, err := os.Open(ex.DemoPathFromArgs())
	checkError(err)
	defer f.Close()

	p := dem.NewParser(f)

	_, err = p.ParseHeader()
	checkError(err)

	roundNum := 1
	const playerName = "device"

	p.RegisterEventHandler(func(ev events.RoundEnd) {
		roundNum++
	})

	// Log playerName's weapons
	p.RegisterEventHandler(func(ev events.RoundFreezetimeEnd) {
		if roundNum == 2 {
			for _, p := range p.GameState().Participants().TeamMembers(common.TeamCounterTerrorists) {
				if p.Name != playerName {
					continue
				}
				for i, wep := range p.Weapons() {
					log.Printf("%s weapon[%d]: %+v\n", playerName, i, wep.Weapon)
				}
			}
			p.Cancel()
		}
	})

	err = p.ParseToEnd()
	checkError(err)
}

func checkError(err error) {
	if err != nil {
		log.Fatal(err)
	}
}

```

**Expected behavior**
Expected to not get `EqUnknown` for known weapons.

**Library version**
I'm getting these results on 13db5217

**Comment by markus-wa** [comment]
Turns out the mapping for the scout is missing 😮

**Comment by markus-wa** [comment]
Please check with 9916e2b.

**Comment by micvbang** [comment]
That was quick! :grinning: 

Yep, seems to work here! Great job Markus!

**Comment by markus-wa** [comment]
Awesome, thanks! 😄
