### ISSUE TITLE
One of player has been written like unknown

### ISSUE THREAD

**Issue by Froctnow** [markus-wa/demoinfocs-golang#533]
**Describe the bug**
There is demo, where one of player hasn't been triggered event PlayerConnected, but triggered PlayerDisconnected and he is wrote there like a unknown player
But if we investigate next events, we will find him there. For example event RoundEnd, we can find him in winners/losers and all okay

**To Reproduce**
Download link to an affected demo:  http://replay272.valve.net/730/003681822564448993333_0996605818.dem.bz2

**Expected behavior**
Player has been connected and written like normal player, and not unknown

**Library version**
v4.1.3

**Comment by Markxy** [comment]
another more recent example: http://replay274.valve.net/730/003683095105276739793_0287984549.dem.bz2
with steamId `76561198327600344`

**Comment by BestAwperEver** [comment]
There's a chance #537 will fix it. Could you try it and share the results?

**Comment by Markxy** [comment]
> There's a chance #537 will fix it. Could you try it and share the results?

Worked for my case above 🙌

**Comment by akiver** [comment]
Fixed with https://github.com/markus-wa/demoinfocs-golang/pull/537
