### ISSUE TITLE
Panic at botTakeover game event

### ISSUE THREAD

**Issue by ekolovertnykh** [markus-wa/demoinfocs-golang#541]
**Describe the bug**
In game_events.go in the **botTakeover** function variable taker is nil. [Access to a struct value by nil pointer makes panic](https://github.com/markus-wa/demoinfocs-golang/blame/11dd3de7cf874c8b0cb96abab798dd68a4bcf5ae/pkg/demoinfocs/game_events.go#L394)

**To Reproduce**
Download link http://replay189.valve.net/730/003684805981876781234_1124755660.dem.bz2

**Expected behavior**
Demo was parsed correctly without pointer errors  

**Library version**
v4.1.3

**Comment by akiver** [comment]
Fixed with https://github.com/markus-wa/demoinfocs-golang/pull/537
