### ISSUE TITLE
events: PlayerFlashed lack of info (Attacker / FlashDuration)

### ISSUE THREAD

**Issue by quancore** [markus-wa/demoinfocs-golang#70]
**Higher goal**
I need to know who is flashed, who did it and the duration of being blind. It is an important feature for my machine learning model.

**Describe the solution you'd like**
Probably, there should be alteration for event of PlayerFlashed like:
```go
type PlayerFlashed struct {
    Attacker *common.Player
    Defender *common.Player
    duration int
}
```

**Comment by markus-wa** [comment]
Duration should be `PlayerFlashed.Player.FlashDuration`. But I agree it should be easier to access this on the event, a 'shortcut' would be helpful.

I'll deffo look into adding the Attacker, seems useful.

**Comment by markus-wa** [comment]
I have pushed the improvement to the `dev` branch if you would like to check it out.

It also includes a fix for `FlashDuration` being 0 in most cases.
