### ISSUE TITLE
events: Is player blinded during Kill event?

### ISSUE THREAD

**Issue by quancore** [markus-wa/demoinfocs-golang#71]
**Higher goal**
It would be wonderful to know whether a player has been killed in a blinded situation or not. Therefore, I can update the blinded kill features.

**Describe the solution you'd like**
Probably, there should be an addition in event of Kill like:
```go
type Kill struct {
    Weapon            *common.Equipment
    Victim            *common.Player
    Killer            *common.Player
    Assister          *common.Player
    PenetratedObjects int
    IsHeadshot        bool
    IsBlinded         bool
}
```

**Comment by markus-wa** [comment]
Maybe you could check `if Victim.FlashDuration > 0`. Does that work?

**Comment by markus-wa** [comment]
I just discovered that `Victim.FlashDuration` doesn't always seem to work :/

Most times it's just `0` for me. Have you noticed this issue as well?

**Comment by markus-wa** [comment]
I've added a helper function `Player.IsBlinded()`

**Comment by quancore** [comment]
I did not test extensively for a moment, I will give feedback when done.
