### ISSUE TITLE
events: is Kill triggered for suicides etc.? (playerdeath event)

### ISSUE THREAD

**Issue by quancore** [markus-wa/demoinfocs-golang#75]
Main aim: FInd out clutch situations
I can upload alive player not for each tick but for each player dead event, however, I am not sure kill event is triggered when a player dead not for killed (ex: jumping in high)? (ex: jumping in somewhere))

**Comment by markus-wa** [comment]
It should be. The `Killer` will be the same as `Victim` in this case.

**Comment by markus-wa** [comment]
Closing, let me know if there's still something unclear about it.
