### ISSUE TITLE
team state and team

### ISSUE THREAD

**Issue by quancore** [markus-wa/demoinfocs-golang#76]
**Higher goal**
Getting complete team information.

**Describe the solution you'd like**
The problem is that some events return team state which has nothing about the side of the team which is expected. However, there is no connection between team states and team sides (Team). For example, if I trigger scoreUpdated event, it returns me teamstate which I have no idea whether it is t or ct team. Fast solution would be adding a method in gamestate to retrieve team side by using team id.

**Comment by markus-wa** [comment]
Thanks for all your great suggestions! 😄

See #78 for my proposed implementation.

**Comment by quancore** [comment]
For scoreUpdated event, it seems working because it returns teamstate however, there are other events which return team only like RoundEnd, PlayerTeamChange etc. I suggest you return teamstate for all events for consistency as well as reachability of properties described above.

**Comment by markus-wa** [comment]
Sorry for the delay, hoping to get to this over the weekend.
Thanks for your input.
