### ISSUE TITLE
Is AdditionalPlayerInfo struct always up to date?

### ISSUE THREAD

**Issue by quancore** [markus-wa/demoinfocs-golang#79]
Is additionalPlayerInfo struct always up to date? I could not find where the fields of the struct are updated for each dispatched events.

**Comment by markus-wa** [comment]
They are updated from entity-updates, not when events are dispatched.

Here: https://github.com/markus-wa/demoinfocs-golang/blob/master/datatables.go#L187

**Comment by markus-wa** [comment]
Closing, let me know if there's still something unclear about it.
