### ISSUE TITLE
MatchEnded event?

### ISSUE THREAD

**Issue by quancore** [markus-wa/demoinfocs-golang#80]
How can I know the match is ended so I can discard any event happened after the match ended?

**Comment by markus-wa** [comment]
See [`events.GamePhaseChanged`](https://godoc.org/github.com/markus-wa/demoinfocs-golang/events#GamePhaseChanged)

And the [possible `GamePhase`s](https://godoc.org/github.com/markus-wa/demoinfocs-golang/common#GamePhase)

**Comment by markus-wa** [comment]
Closing, let me know if there's still something unclear about it.
