### ISSUE TITLE
player reconnect

### ISSUE THREAD

**Issue by quancore** [markus-wa/demoinfocs-golang#81]
When a player connects/disconnect, which fields get reset and which fields get a newly assigned value? I collect information about players and I need to transmit info to a player who reconnected. I am using SteamID to identify players. Any suggestions to do this task in an easy way?
And also it would be wonderful to the creation of playerReconnect event.

**Comment by markus-wa** [comment]
That depends entierly on the demo (entity-update packages).

So I think this can't be answered correctly. Your best bet is looking at a specific case where it happens but I'd suggest you don't do that as it's probably unreliable.

**Comment by quancore** [comment]
By definition, SteamID would be reliable because it cannot be changed for reconnection. Is there any possible case SteamID can change as well?

**Comment by markus-wa** [comment]
No, the Steam-ID will be fixed unless there's a bug in either CS:GO or the lib or the demo is somehow corrupt.

**Comment by markus-wa** [comment]
Closing, let me know if there's still something unclear about it.
