### ISSUE TITLE
roundEnd vs roundOfficiallyEnd

### ISSUE THREAD

**Issue by quancore** [markus-wa/demoinfocs-golang#83]
1. What is all of the differences of round end and round officially ended event?
2. As far as I read, these events could be in deficit for some of the demo files but Are we sure that on of events will be definitely called to identify a round has been ended such as round end, round officially end or score updated?

**Comment by markus-wa** [comment]
1) see godoc

2) I'm not sure what you mean, they should both occur after each round.

**Comment by quancore** [comment]
> 1. see godoc
> 2. I'm not sure what you mean, they should both occur after each round.

For question 2, I mean are we ensure that one of the events (round end, round officially end or score updated) will be called to indicate a round has been ended that has been started already? I am asking because I am observing some rounds that have no indication of the round end and after that new round is started.

**Comment by markus-wa** [comment]
This could be due to eBot or some other plugin on the server. Normal MM games will always have one of the events.

This library only parses the demo as-is. Due to server plugins sending strange events etc. this can lead to almost anything happening even if it doesn't make sense.

So yeah it's possible none of the events are sent out.

Can you upload the debug output (`-tags debugdemoinfocs` somewhere (pastebin)? Then it's easier for me to tell what's happening.

**Comment by quancore** [comment]
When I changed my demofile with default one and rename by default and then run : `go test -tags debugdemoinfocs -v`,  it gives an error:
https://ibb.co/zSfxT6S

**Comment by markus-wa** [comment]
If you want to run tests of this lib you need to [download the test-demos](https://github.com/markus-wa/demoinfocs-golang#running-tests)

But to get debug output for only your demo you can either do:
`go run -tags debugdemoinfocs my_app.go` where my_app.go is your code that parses the demo in question

or you can do `go run -tags debugdemoinfocs examples/print-events/print_events.go -demo /path/to/your/replay.dem`

**Comment by quancore** [comment]
> If you want to run tests of this lib you need to [download the test-demos](https://github.com/markus-wa/demoinfocs-golang#running-tests)
> 
> But to get debug output for only your demo you can either do:
> `go run -tags debugdemoinfocs my_app.go` where my_app.go is your code that parses the demo in question
> 
> or you can do `go run -tags debugdemoinfocs examples/print-events/print_events.go -demo /path/to/your/replay.dem`

It creates a long output in the console which is truncated. Is there any log file created by the library?

**Comment by markus-wa** [comment]
Just redirect it to a file.

e.g. `go run -tags debugdemoinfocs examples/print-events/print_events.go -demo /path/to/your/replay.dem > out.log`

**Comment by quancore** [comment]
Here

**Comment by quancore** [comment]
> Just redirect it to a file.
> 
> e.g. `go run -tags debugdemoinfocs examples/print-events/print_events.go -demo /path/to/your/replay.dem > out.log`

Here is the file: 
[out.log](https://github.com/markus-wa/demoinfocs-golang/files/2764346/out.log)

**Comment by markus-wa** [comment]
Yeah the demo just does whatever it wants as it seems.


```
GameEvent: round_prestart Data: map[]
GameEvent: round_start Data: map[timelimit:120 fraglimit:0 objective:BOMB TARGET]
GameEvent: round_poststart Data: map[]
IngameTick=9264
--
IngameTick=9891
GameEvent: round_freeze_end Data: map[]
GameEvent: round_announce_match_start Data: map[]
IngameTick=9893
--
IngameTick=10591
GameEvent: round_end Data: map[reason:8 message:#SFUI_Notice_CTs_Win legacy:0 player_count:10 nomusic:0 winner:3]
IngameTick=10593
--
IngameTick=11229
GameEvent: round_officially_ended Data: map[]
GameEvent: round_prestart Data: map[]
GameEvent: round_start Data: map[timelimit:120 fraglimit:0 objective:BOMB TARGET]
GameEvent: round_poststart Data: map[]
IngameTick=11237
--
IngameTick=11870
GameEvent: round_freeze_end Data: map[]
IngameTick=11872
--
IngameTick=12355
GameEvent: round_officially_ended Data: map[]
GameEvent: round_prestart Data: map[]
GameEvent: round_start Data: map[timelimit:115 fraglimit:0 objective:BOMB TARGET]
GameEvent: round_poststart Data: map[]
IngameTick=12360
--
IngameTick=12605
GameEvent: round_prestart Data: map[]
GameEvent: round_start Data: map[fraglimit:0 objective:BOMB TARGET timelimit:115]
GameEvent: round_poststart Data: map[]
IngameTick=12612
--
IngameTick=12990
GameEvent: round_prestart Data: map[]
GameEvent: round_start Data: map[timelimit:115 fraglimit:0 objective:BOMB TARGET]
GameEvent: round_poststart Data: map[]
IngameTick=12997
--
IngameTick=14911
GameEvent: round_freeze_end Data: map[]
GameEvent: round_announce_match_start Data: map[]
IngameTick=14913
--
IngameTick=22499
GameEvent: round_end Data: map[message:#SFUI_Notice_Terrorists_Win legacy:0 player_count:10 nomusic:0 winner:2 reason:9]
IngameTick=22501
--
IngameTick=23141
GameEvent: round_officially_ended Data: map[]
```

I assume it's due to eBot or something setting up the game which causes unusual round restarts.

So
> As far as I read, these events could be in deficit for some of the demo files but Are we sure that on of events will be definitely called to identify a round has been ended such as round end, round officially end or score updated?

no

pinging @micvbang again, any idea what to do? (also considering this in relation to #84, so `ScoreUpdated` doesn't seem to always do the trick)

**Comment by quancore** [comment]
Interestingly, there are several match start event so that how can we know that the actual match is starting?

**Comment by micvbang** [comment]
Sorry for the major delay in my reponses - It's very busy here!

Yeah, like most other events, `RoundEnd` and `RoundEndOfficial` are (ab)used by tournaments everywhere. As far as I've experienced, the right solution seems to be to use combinations of all of the events available to create some fuzzy logic that determines if a round has ended. I haven't been able to find a fixed in-game event that tells us this with certainty. It gets really messy really quickly!
