### ISSUE TITLE
base class for events

### ISSUE THREAD

**Issue by quancore** [markus-wa/demoinfocs-golang#86]
I decided to store all events in an array per round before dispatching them directly with a registered event handler, therefore, after I checked several parameters for the current round, I can decide to discard or dispatch events. However, I do not see a base interface implementation for all events. My question is that how can I store all events in a single event container for delayed dispatch?

**Comment by markus-wa** [comment]
Using `interface{}`: https://tour.golang.org/methods/14

I think this kind of question would be better suited for Gitter as it's not really about the library. Otherwise the searchability of issues gets a bit difficult at some point.

**Comment by quancore** [comment]
Of course, I will use gitter for further questions for later.
