### ISSUE TITLE
round end loser state

### ISSUE THREAD

**Issue by quancore** [markus-wa/demoinfocs-golang#90]
**Describe the bug**
When round end has been called, getting score by using loser team state return always 0.

**To Reproduce**
I think it will be produced for all demo files

Code:
Initiate round end event and get loser score by `e.LoserState.Score`

**Expected behavior**
Correct score for losing team as well.
**Library version**
Latest

**Comment by quancore** [comment]
Waiting for consideration of this issue.

**Comment by markus-wa** [comment]
Should be fixed now, please confirm
