### ISSUE TITLE
How do I get the round time and not the game time?

### ISSUE THREAD

**Issue by Sivx** [markus-wa/demoinfocs-golang#91]

**Comment by markus-wa** [comment]
just subtract the game time between the two events

**Comment by Sivx** [comment]
Hey, I am trying to do it but im getting compiler errors of the var being
undefined.

**Comment by Sivx** [comment]
Figured it out. Strange go syntax :P. thnx

**Comment by markus-wa** [comment]
Haha, yeah it takes a moment to get used to :D

Glad you figured it out,  happy coding!
